-- DDL Export
-- Server: 10.253.50.28
-- Database: CLASSLOG
-- Exported: 2026-02-04T02:30:24.856758

USE CLASSLOG;
GO

-- --------------------------------------------------
-- TABLE dbo.APPLOG
-- --------------------------------------------------
CREATE TABLE [dbo].[APPLOG]
(
    [UID] VARCHAR(200) NULL,
    [SESSIONID] VARCHAR(200) NULL,
    [TIMESTAMP] VARCHAR(200) NULL,
    [USERNAME] VARCHAR(200) NULL,
    [EXCHANGE] VARCHAR(200) NULL,
    [SEGMENT] VARCHAR(200) NULL,
    [STATUSID] VARCHAR(200) NULL,
    [STATUSNAME] VARCHAR(200) NULL,
    [IP] VARCHAR(200) NULL,
    [PREVIOUSPAGE] VARCHAR(500) NULL,
    [CLASSNAME] VARCHAR(500) NULL,
    [METHOD] VARCHAR(200) NULL,
    [REPCODE] INT NULL,
    [ISERROR] BIT NULL DEFAULT ((0)),
    [SRNO] BIGINT IDENTITY(0,1) NOT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.APPLOG_TRG
-- --------------------------------------------------
CREATE TABLE [dbo].[APPLOG_TRG]
(
    [UID] VARCHAR(200) NULL,
    [SESSIONID] VARCHAR(200) NULL,
    [TIMESTAMP] VARCHAR(200) NULL,
    [USERNAME] VARCHAR(200) NULL,
    [EXCHANGE] VARCHAR(200) NULL,
    [SEGMENT] VARCHAR(200) NULL,
    [STATUSID] VARCHAR(200) NULL,
    [STATUSNAME] VARCHAR(200) NULL,
    [IP] VARCHAR(200) NULL,
    [PREVIOUSPAGE] VARCHAR(500) NULL,
    [CLASSNAME] VARCHAR(500) NULL,
    [METHOD] VARCHAR(200) NULL,
    [REPCODE] INT NULL,
    [ISERROR] BIT NULL,
    [EXECUTEDON] DATETIME NULL,
    [ACTION] VARCHAR(2) NULL
);

GO

-- --------------------------------------------------
-- TRIGGER dbo.APPLOG_DELETE
-- --------------------------------------------------

CREATE TRIGGER [dbo].[APPLOG_DELETE] ON [dbo].[APPLOG] FOR DELETE
AS
BEGIN
	SET NOCOUNT ON
	INSERT INTO APPLOG_TRG ([UID],SESSIONID,[TIMESTAMP],USERNAME,EXCHANGE,SEGMENT,STATUSID,
							STATUSNAME,IP,PREVIOUSPAGE,CLASSNAME,METHOD,REPCODE,ISERROR,EXECUTEDON,[ACTION])
	SELECT [UID],SESSIONID,[TIMESTAMP],USERNAME,EXCHANGE,SEGMENT,STATUSID,
							STATUSNAME,IP,PREVIOUSPAGE,CLASSNAME,METHOD,REPCODE,ISERROR,EXECUTEDON = GETDATE(), [ACTION] = 'D' FROM DELETED
END

GO

-- --------------------------------------------------
-- TRIGGER dbo.APPLOG_UPDATE
-- --------------------------------------------------

CREATE TRIGGER [dbo].[APPLOG_UPDATE] ON [dbo].[APPLOG] FOR UPDATE
AS
BEGIN
	SET NOCOUNT ON
	INSERT INTO APPLOG_TRG ([UID],SESSIONID,[TIMESTAMP],USERNAME,EXCHANGE,SEGMENT,STATUSID,
							STATUSNAME,IP,PREVIOUSPAGE,CLASSNAME,METHOD,REPCODE,ISERROR,EXECUTEDON,[ACTION])
	SELECT [UID],SESSIONID,[TIMESTAMP],USERNAME,EXCHANGE,SEGMENT,STATUSID,
							STATUSNAME,IP,PREVIOUSPAGE,CLASSNAME,METHOD,REPCODE,ISERROR,EXECUTEDON = GETDATE(), [ACTION] = 'M' FROM DELETED
END

GO

-- --------------------------------------------------
-- TABLE yatin.APPLOG
-- --------------------------------------------------
CREATE TABLE [yatin].[APPLOG]
(
    [UID] VARCHAR(200) NULL,
    [SESSIONID] VARCHAR(200) NULL,
    [TIMESTAMP] VARCHAR(200) NULL,
    [USERNAME] VARCHAR(200) NULL,
    [EXCHANGE] VARCHAR(200) NULL,
    [SEGMENT] VARCHAR(200) NULL,
    [STATUSID] VARCHAR(200) NULL,
    [STATUSNAME] VARCHAR(200) NULL,
    [IP] VARCHAR(200) NULL,
    [PREVIOUSPAGE] VARCHAR(500) NULL,
    [CLASSNAME] VARCHAR(500) NULL,
    [METHOD] VARCHAR(200) NULL,
    [REPCODE] INT NULL,
    [ISERROR] BIT NULL DEFAULT ((0)),
    [SRNO] BIGINT IDENTITY(0,1) NOT NULL
);

GO

-- --------------------------------------------------
-- TABLE yatin.APPLOG_TRG
-- --------------------------------------------------
CREATE TABLE [yatin].[APPLOG_TRG]
(
    [UID] VARCHAR(200) NULL,
    [SESSIONID] VARCHAR(200) NULL,
    [TIMESTAMP] VARCHAR(200) NULL,
    [USERNAME] VARCHAR(200) NULL,
    [EXCHANGE] VARCHAR(200) NULL,
    [SEGMENT] VARCHAR(200) NULL,
    [STATUSID] VARCHAR(200) NULL,
    [STATUSNAME] VARCHAR(200) NULL,
    [IP] VARCHAR(200) NULL,
    [PREVIOUSPAGE] VARCHAR(500) NULL,
    [CLASSNAME] VARCHAR(500) NULL,
    [METHOD] VARCHAR(200) NULL,
    [REPCODE] INT NULL,
    [ISERROR] BIT NULL,
    [EXECUTEDON] DATETIME NULL,
    [ACTION] VARCHAR(2) NULL
);

GO

