-- DDL Export
-- Server: 10.254.33.28
-- Database: APIDetails
-- Exported: 2026-02-05T11:34:32.909330

USE APIDetails;
GO

-- --------------------------------------------------
-- INDEX dbo.API_PAYMENT_DETAILS
-- --------------------------------------------------
CREATE NONCLUSTERED INDEX [IX_API_PAYMENT_DETAILS_TRANSACTION_ID] ON [dbo].[API_PAYMENT_DETAILS] ([TRANSACTION_ID])

GO

-- --------------------------------------------------
-- INDEX dbo.API_PAYMENT_DETAILS
-- --------------------------------------------------
CREATE NONCLUSTERED INDEX [IX_EXCHANGE] ON [dbo].[API_PAYMENT_DETAILS] ([CLIENT_CODE]) INCLUDE ([EXCHANGE], [SEGMENT])

GO

-- --------------------------------------------------
-- INDEX dbo.API_PAYMENT_DETAILS
-- --------------------------------------------------
CREATE NONCLUSTERED INDEX [NCIDX_POST_DATE] ON [dbo].[API_PAYMENT_DETAILS] ([POST_DATE])

GO

-- --------------------------------------------------
-- INDEX dbo.API_RESULT_DETAILS
-- --------------------------------------------------
CREATE NONCLUSTERED INDEX [uname] ON [dbo].[API_RESULT_DETAILS] ([UNAME])

GO

-- --------------------------------------------------
-- PROCEDURE dbo.API_RECEIPT_BANK_POSTING
-- --------------------------------------------------

CREATE PROCEDURE [dbo].[API_RECEIPT_BANK_POSTING]
(
	@TRANSACTION_ID VARCHAR(20), -- UNIQUE TRANSACTION NUMBER RECEIVED IN API
	@EFFECTIVE_DATE VARCHAR(20), -- RECEIPT EFFECTIVE DATE IN DD/MM/YYYY FORMAT
	@VOUCHER_DATE VARCHAR(20), -- RECEIPT VOUCHER DATE IN DD/MM/YYYY FORMAT
	@CLIENT_CODE VARCHAR(50), -- CLIENT OR GL ACCOUNT
	@AMOUNT MONEY, -- RECEIPT AMOUNT
	@NARRATION VARCHAR(234), -- RECEIPT NARRATION
	@BANK_CODE VARCHAR(10), -- BROKER BANK ACCOUNT
	@BANK_NAME VARCHAR(100), -- RECEIPT BANK NAME
	@REFERENCE_NO VARCHAR(28), -- RECEIPT REFERENCE NO
	@BRANCHCODE VARCHAR(20), -- CLIENT OR GL BRANCH CODE SPECIFIED IN BROKERS SYSTEM
	@BRANCH_NAME VARCHAR(50), -- RECEIPT BRANCH NAME
	@CHQ_MODE VARCHAR(1), -- RECEIPT CHEQUE MODE (C - CHEQUE , D - DD, I - INTERSEGMENT, N -NEFT/RTGS'
	@CHQ_DATE VARCHAR(20), -- RECEIPT CHEQUE DATE
	@CHQ_NAME VARCHAR(100), -- NAME OF CLIENT IN CASE THE RECEIVED FROM CLIENT
	@CL_MODE VARCHAR(1), -- CHEQUE CLEARING MODE
	@ACC_NO VARCHAR(20),
	@EXCHANGE VARCHAR(10), -- EXCHANGE FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@SEGMENT VARCHAR(10),-- SEGMENT FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@UNAME VARCHAR(25) -- LOGIN USER NAME
)
AS


--RETURN 0



DECLARE
	@@SQL VARCHAR(500),
	@@ACCOUNTSERVER VARCHAR(100),
	@@ACCOUNTDB VARCHAR(100),
	@@ERROR_COUNT AS INT,
	@@APIACCOUNTDB varchar(100)

	IF @CHQ_MODE ='A' 
	  BEGIN 
	   SET @CHQ_MODE ='C'
      END 
  
  	IF @SEGMENT ='MFSS' AND @UNAME ='TPR'
	  BEGIN 
	   SET @UNAME ='TPR1'
      END


SELECT @@ERROR_COUNT = COUNT(1) FROM APIDETAILS..API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID AND POST_STATUS = 'SUCCESS'

IF @@ERROR_COUNT > 0
BEGIN
	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS' WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
	SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS'
	RETURN
END	

SET @@ERROR_COUNT = 0

SELECT @@ERROR_COUNT = DATEDIFF(D, CONVERT(DATETIME, @VOUCHER_DATE, 103), GETDATE())

IF @@ERROR_COUNT > 7
BEGIN
       UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'BACKDATED ENTRIES MORE THAN 7 DAYS' WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
       SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'BACKDATED ENTRIES MORE THAN 7 DAYS'
RETURN

END





	
INSERT INTO API_PAYMENT_DETAILS
	(TRANSACTION_ID, EFFECTIVE_DATE, VOUCHER_DATE, CLIENT_CODE, AMOUNT, DRCR, NARRATION, BANK_CODE, BANK_NAME, REFERENCE_NO, BRANCHCODE, BRANCH_NAME,
	 CHQ_MODE, CHQ_DATE, CHQ_NAME, CL_MODE, ACC_NO,EXCHANGE, SEGMENT, UNAME, POST_DATE, ACTION_FLAG)
VALUES
(
	@TRANSACTION_ID,
	@EFFECTIVE_DATE,
	@VOUCHER_DATE,
	@CLIENT_CODE,
	@AMOUNT,
	'C',
	@NARRATION,
	@BANK_CODE,
	@BANK_NAME,
	@REFERENCE_NO,
	@BRANCHCODE,
	@BRANCH_NAME,
	@CHQ_MODE,
	@CHQ_DATE,
	@CHQ_NAME,
	@CL_MODE,
	@ACC_NO,
	@EXCHANGE,
	@SEGMENT,
	@UNAME,
	GETDATE(),
	'I'
)	


SET @@ERROR_COUNT = 0

SELECT @@ERROR_COUNT = COUNT(1) FROM APIDETAILS..API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(REFERENCE_NO,0) = '0'

IF @@ERROR_COUNT > 0
BEGIN
       UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'INVALID REFERENCE NUMBER' 
	   WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
       SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'INVALID REFERENCE NUMBER'
RETURN

END

SET @@ERROR_COUNT = 0

SELECT @@ERROR_COUNT = COUNT(1) FROM APIDETAILS..API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID AND ( ISNULL(CLIENT_CODE,'') = '' OR ISNULL(BANK_CODE,'')='')

IF @@ERROR_COUNT > 0
BEGIN
       UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CODE CANNOT BE BLANK' 
	   WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
       SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CODE CANNOT BE BLANK'
RETURN

END




/*SET @@SQL = "CREATE TABLE API_RESULT_" + @UNAME
SET @@SQL = @@SQL + " ("
SET @@SQL = @@SQL + " 	POST_STATUS VARCHAR(50),"
SET @@SQL = @@SQL + " 	EXECUTION_REMARK VARCHAR(500)"
SET @@SQL = @@SQL + " )"

EXEC (@@SQL)*/
	
	
SELECT @@ACCOUNTSERVER = ACCOUNTSERVER, @@ACCOUNTDB = ACCOUNTDB FROM PRADNYA.DBO.MULTICOMPANY
WHERE EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT AND PrimaryServer =1 


/*

 IF (@@ACCOUNTSVR +ISNULL('\'+@@SERVICENAME,'')<> @@SERVERNAME  )
	BEGIN
		SELECT 'LINK SERVER'
	END
ELSE 
	BEGIN
	SELECT 'local'
	END
*/

SELECT @@APIACCOUNTDB = @@SERVICENAME
	
IF @SEGMENT <> 'MFSS'
BEGIN	
	--SET @@SQL = "INSERT INTO #API_RESULT "
	SET @@SQL = " EXEC " + @@ACCOUNTSERVER + "." + @@ACCOUNTDB + ".DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
	SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
	SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
	SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
	SET @@SQL = @@SQL + "'" + @NARRATION + "', "
	SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
	SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
	SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
	SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
	SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
	SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
	SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
	SET @@SQL = @@SQL + "'" + @UNAME + "',"
	SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
	--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"
END
ELSE
BEGIN
	--SET @@SQL = "INSERT INTO #API_RESULT "
	--SET @@SQL = " EXEC " + @@ACCOUNTSERVER + ".BBO_FA.DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = " EXEC ANGELFO.BBO_FA.DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
	SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
	SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
	SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
	SET @@SQL = @@SQL + "'" + @NARRATION + "', "
	SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
	SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
	SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
	SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
	SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
	SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
	SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
	SET @@SQL = @@SQL + "'" + @UNAME + "',"
	SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
	--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"
END

EXEC (@@SQL)
--PRINT @@SQL
--RETURN
 

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_PAYMENT_DETAILS RD, API_RESULT_DETAILS AR 
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
AND AR.UNAME = @UNAME

DELETE FROM API_RESULT_DETAILS WHERE UNAME = @UNAME


SELECT DISTINCT POST_STATUS,EXECUTION_REMARK FROM 
API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID


/*SET @@SQL = "DROP TABLE API_RESULT_" + @UNAME

EXEC (@@SQL)*/

/*
SELECT * FROM #API_RESULT

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_RECEIPT_DETAILS RD, #API_RESULT AR
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
*/

GO

-- --------------------------------------------------
-- PROCEDURE dbo.API_RECEIPT_BANK_POSTING_backup01Oct2017
-- --------------------------------------------------


CREATE PROCEDURE [dbo].[API_RECEIPT_BANK_POSTING_backup01Oct2017]
(
	@TRANSACTION_ID VARCHAR(20), -- UNIQUE TRANSACTION NUMBER RECEIVED IN API
	@EFFECTIVE_DATE VARCHAR(20), -- RECEIPT EFFECTIVE DATE IN DD/MM/YYYY FORMAT
	@VOUCHER_DATE VARCHAR(20), -- RECEIPT VOUCHER DATE IN DD/MM/YYYY FORMAT
	@CLIENT_CODE VARCHAR(50), -- CLIENT OR GL ACCOUNT
	@AMOUNT MONEY, -- RECEIPT AMOUNT
	@NARRATION VARCHAR(234), -- RECEIPT NARRATION
	@BANK_CODE VARCHAR(10), -- BROKER BANK ACCOUNT
	@BANK_NAME VARCHAR(100), -- RECEIPT BANK NAME
	@REFERENCE_NO VARCHAR(15), -- RECEIPT REFERENCE NO
	@BRANCHCODE VARCHAR(20), -- CLIENT OR GL BRANCH CODE SPECIFIED IN BROKERS SYSTEM
	@BRANCH_NAME VARCHAR(50), -- RECEIPT BRANCH NAME
	@CHQ_MODE VARCHAR(1), -- RECEIPT CHEQUE MODE (C - CHEQUE , D - DD, I - INTERSEGMENT, N -NEFT/RTGS'
	@CHQ_DATE VARCHAR(20), -- RECEIPT CHEQUE DATE
	@CHQ_NAME VARCHAR(100), -- NAME OF CLIENT IN CASE THE RECEIVED FROM CLIENT
	@CL_MODE VARCHAR(1), -- CHEQUE CLEARING MODE
	@ACC_NO VARCHAR(20),
	@EXCHANGE VARCHAR(10), -- EXCHANGE FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@SEGMENT VARCHAR(10),-- SEGMENT FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@UNAME VARCHAR(25) -- LOGIN USER NAME
)
AS

DECLARE
	@@SQL VARCHAR(500),
	@@ACCOUNTSERVER VARCHAR(100),
	@@ACCOUNTDB VARCHAR(100),
	@@ERROR_COUNT AS INT,
	@@APIACCOUNTDB varchar(100)
	
SELECT @@ERROR_COUNT = COUNT(1) FROM APIDETAILS..API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID AND POST_STATUS = 'SUCCESS'

IF @@ERROR_COUNT > 0
BEGIN
	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS' WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
	SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS'
	RETURN
END	
	
INSERT INTO API_PAYMENT_DETAILS
	(TRANSACTION_ID, EFFECTIVE_DATE, VOUCHER_DATE, CLIENT_CODE, AMOUNT, DRCR, NARRATION, BANK_CODE, BANK_NAME, REFERENCE_NO, BRANCHCODE, BRANCH_NAME,
	 CHQ_MODE, CHQ_DATE, CHQ_NAME, CL_MODE, ACC_NO,EXCHANGE, SEGMENT, UNAME, POST_DATE, ACTION_FLAG)
VALUES
(
	@TRANSACTION_ID,
	@EFFECTIVE_DATE,
	@VOUCHER_DATE,
	@CLIENT_CODE,
	@AMOUNT,
	'C',
	@NARRATION,
	@BANK_CODE,
	@BANK_NAME,
	@REFERENCE_NO,
	@BRANCHCODE,
	@BRANCH_NAME,
	@CHQ_MODE,
	@CHQ_DATE,
	@CHQ_NAME,
	@CL_MODE,
	@ACC_NO,
	@EXCHANGE,
	@SEGMENT,
	@UNAME,
	GETDATE(),
	'I'
)	

/*SET @@SQL = "CREATE TABLE API_RESULT_" + @UNAME
SET @@SQL = @@SQL + " ("
SET @@SQL = @@SQL + " 	POST_STATUS VARCHAR(50),"
SET @@SQL = @@SQL + " 	EXECUTION_REMARK VARCHAR(500)"
SET @@SQL = @@SQL + " )"

EXEC (@@SQL)*/
	
	
SELECT @@ACCOUNTSERVER = ACCOUNTSERVER, @@ACCOUNTDB = ACCOUNTDB FROM PRADNYA.DBO.MULTICOMPANY
WHERE EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT AND PrimaryServer =1 


SELECT @@APIACCOUNTDB = @@SERVERNAME
	
IF @SEGMENT <> 'MFSS'
BEGIN	
	--SET @@SQL = "INSERT INTO #API_RESULT "
	SET @@SQL = " EXEC " + @@ACCOUNTSERVER + "." + @@ACCOUNTDB + ".DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
	SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
	SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
	SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
	SET @@SQL = @@SQL + "'" + @NARRATION + "', "
	SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
	SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
	SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
	SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
	SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
	SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
	SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
	SET @@SQL = @@SQL + "'" + @UNAME + "',"
	SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
	--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"
END
ELSE
BEGIN
	--SET @@SQL = "INSERT INTO #API_RESULT "
	--SET @@SQL = " EXEC " + @@ACCOUNTSERVER + ".BBO_FA.DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = " EXEC ANGELFO.BBO_FA.DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
	SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
	SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
	SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
	SET @@SQL = @@SQL + "'" + @NARRATION + "', "
	SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
	SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
	SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
	SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
	SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
	SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
	SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
	SET @@SQL = @@SQL + "'" + @UNAME + "',"
	SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
	--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"
END

EXEC (@@SQL)
--PRINT @@SQL
--RETURN
 

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_PAYMENT_DETAILS RD, API_RESULT_DETAILS AR 
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
AND AR.UNAME = @UNAME

DELETE FROM API_RESULT_DETAILS WHERE UNAME = @UNAME


SELECT DISTINCT POST_STATUS,EXECUTION_REMARK FROM 
API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID


/*SET @@SQL = "DROP TABLE API_RESULT_" + @UNAME

EXEC (@@SQL)*/

/*
SELECT * FROM #API_RESULT

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_RECEIPT_DETAILS RD, #API_RESULT AR
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
*/

GO

-- --------------------------------------------------
-- PROCEDURE dbo.API_RECEIPT_BANK_POSTING_bkp27062017
-- --------------------------------------------------

create PROCEDURE [dbo].[API_RECEIPT_BANK_POSTING_bkp27062017]
(
	@TRANSACTION_ID VARCHAR(20), -- UNIQUE TRANSACTION NUMBER RECEIVED IN API
	@EFFECTIVE_DATE VARCHAR(20), -- RECEIPT EFFECTIVE DATE IN DD/MM/YYYY FORMAT
	@VOUCHER_DATE VARCHAR(20), -- RECEIPT VOUCHER DATE IN DD/MM/YYYY FORMAT
	@CLIENT_CODE VARCHAR(50), -- CLIENT OR GL ACCOUNT
	@AMOUNT MONEY, -- RECEIPT AMOUNT
	@NARRATION VARCHAR(234), -- RECEIPT NARRATION
	@BANK_CODE VARCHAR(10), -- BROKER BANK ACCOUNT
	@BANK_NAME VARCHAR(100), -- RECEIPT BANK NAME
	@REFERENCE_NO VARCHAR(15), -- RECEIPT REFERENCE NO
	@BRANCHCODE VARCHAR(20), -- CLIENT OR GL BRANCH CODE SPECIFIED IN BROKERS SYSTEM
	@BRANCH_NAME VARCHAR(50), -- RECEIPT BRANCH NAME
	@CHQ_MODE VARCHAR(1), -- RECEIPT CHEQUE MODE (C - CHEQUE , D - DD, I - INTERSEGMENT, N -NEFT/RTGS'
	@CHQ_DATE VARCHAR(20), -- RECEIPT CHEQUE DATE
	@CHQ_NAME VARCHAR(100), -- NAME OF CLIENT IN CASE THE RECEIVED FROM CLIENT
	@CL_MODE VARCHAR(1), -- CHEQUE CLEARING MODE
	@ACC_NO VARCHAR(20),
	@EXCHANGE VARCHAR(10), -- EXCHANGE FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@SEGMENT VARCHAR(10),-- SEGMENT FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@UNAME VARCHAR(25) -- LOGIN USER NAME
)
AS

DECLARE
	@@SQL VARCHAR(500),
	@@ACCOUNTSERVER VARCHAR(100),
	@@ACCOUNTDB VARCHAR(100),
	@@ERROR_COUNT AS INT,
	@@APIACCOUNTDB varchar(100)
	
SELECT @@ERROR_COUNT = COUNT(1) FROM APIDETAILS..API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID AND POST_STATUS = 'SUCCESS'

IF @@ERROR_COUNT > 0
BEGIN
	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS' WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
	SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS'
	RETURN
END	
	
INSERT INTO API_PAYMENT_DETAILS
	(TRANSACTION_ID, EFFECTIVE_DATE, VOUCHER_DATE, CLIENT_CODE, AMOUNT, DRCR, NARRATION, BANK_CODE, BANK_NAME, REFERENCE_NO, BRANCHCODE, BRANCH_NAME,
	 CHQ_MODE, CHQ_DATE, CHQ_NAME, CL_MODE, ACC_NO,EXCHANGE, SEGMENT, UNAME, POST_DATE, ACTION_FLAG)
VALUES
(
	@TRANSACTION_ID,
	@EFFECTIVE_DATE,
	@VOUCHER_DATE,
	@CLIENT_CODE,
	@AMOUNT,
	'C',
	@NARRATION,
	@BANK_CODE,
	@BANK_NAME,
	@REFERENCE_NO,
	@BRANCHCODE,
	@BRANCH_NAME,
	@CHQ_MODE,
	@CHQ_DATE,
	@CHQ_NAME,
	@CL_MODE,
	@ACC_NO,
	@EXCHANGE,
	@SEGMENT,
	@UNAME,
	GETDATE(),
	'I'
)	

/*SET @@SQL = "CREATE TABLE API_RESULT_" + @UNAME
SET @@SQL = @@SQL + " ("
SET @@SQL = @@SQL + " 	POST_STATUS VARCHAR(50),"
SET @@SQL = @@SQL + " 	EXECUTION_REMARK VARCHAR(500)"
SET @@SQL = @@SQL + " )"

EXEC (@@SQL)*/
	
	
SELECT @@ACCOUNTSERVER = ACCOUNTSERVER, @@ACCOUNTDB = ACCOUNTDB FROM PRADNYA.DBO.MULTICOMPANY
WHERE EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT


SELECT @@APIACCOUNTDB = @@SERVERNAME
	
	
--SET @@SQL = "INSERT INTO #API_RESULT "
SET @@SQL = " EXEC " + @@ACCOUNTSERVER + "." + @@ACCOUNTDB + ".DBO.RECEIPT_BANK_POSTING "
SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
SET @@SQL = @@SQL + "'" + @NARRATION + "', "
SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
SET @@SQL = @@SQL + "'" + @UNAME + "',"
SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"

EXEC (@@SQL)
PRINT @@SQL
--RETURN
 

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_PAYMENT_DETAILS RD, API_RESULT_DETAILS AR 
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
AND AR.UNAME = @UNAME

DELETE FROM API_RESULT_DETAILS WHERE UNAME = @UNAME


SELECT DISTINCT POST_STATUS,EXECUTION_REMARK FROM 
API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID


/*SET @@SQL = "DROP TABLE API_RESULT_" + @UNAME

EXEC (@@SQL)*/

/*
SELECT * FROM #API_RESULT

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_RECEIPT_DETAILS RD, #API_RESULT AR
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
*/

GO

-- --------------------------------------------------
-- PROCEDURE dbo.API_RECEIPT_BANK_POSTING_testofracces
-- --------------------------------------------------


CREATE PROCEDURE [dbo].[API_RECEIPT_BANK_POSTING_testofracces]
(
	@TRANSACTION_ID VARCHAR(20), -- UNIQUE TRANSACTION NUMBER RECEIVED IN API
	@EFFECTIVE_DATE VARCHAR(20), -- RECEIPT EFFECTIVE DATE IN DD/MM/YYYY FORMAT
	@VOUCHER_DATE VARCHAR(20), -- RECEIPT VOUCHER DATE IN DD/MM/YYYY FORMAT
	@CLIENT_CODE VARCHAR(50), -- CLIENT OR GL ACCOUNT
	@AMOUNT MONEY, -- RECEIPT AMOUNT
	@NARRATION VARCHAR(234), -- RECEIPT NARRATION
	@BANK_CODE VARCHAR(10), -- BROKER BANK ACCOUNT
	@BANK_NAME VARCHAR(100), -- RECEIPT BANK NAME
	@REFERENCE_NO VARCHAR(15), -- RECEIPT REFERENCE NO
	@BRANCHCODE VARCHAR(20), -- CLIENT OR GL BRANCH CODE SPECIFIED IN BROKERS SYSTEM
	@BRANCH_NAME VARCHAR(50), -- RECEIPT BRANCH NAME
	@CHQ_MODE VARCHAR(1), -- RECEIPT CHEQUE MODE (C - CHEQUE , D - DD, I - INTERSEGMENT, N -NEFT/RTGS'
	@CHQ_DATE VARCHAR(20), -- RECEIPT CHEQUE DATE
	@CHQ_NAME VARCHAR(100), -- NAME OF CLIENT IN CASE THE RECEIVED FROM CLIENT
	@CL_MODE VARCHAR(1), -- CHEQUE CLEARING MODE
	@ACC_NO VARCHAR(20),
	@EXCHANGE VARCHAR(10), -- EXCHANGE FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@SEGMENT VARCHAR(10),-- SEGMENT FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@UNAME VARCHAR(25) -- LOGIN USER NAME
)
AS

DECLARE
	@@SQL VARCHAR(500),
	@@ACCOUNTSERVER VARCHAR(100),
	@@ACCOUNTDB VARCHAR(100),
	@@ERROR_COUNT AS INT,
	@@APIACCOUNTDB varchar(100)
	
SELECT @@ERROR_COUNT = COUNT(1) FROM APIDETAILS..API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID AND POST_STATUS = 'SUCCESS'

IF @@ERROR_COUNT > 0
BEGIN
	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS' WHERE TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(POST_STATUS, '') = ''
	SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'SPECIFIED TRANSACTION ID ALREADY EXISTS'
	RETURN
END	
	
INSERT INTO API_PAYMENT_DETAILS
	(TRANSACTION_ID, EFFECTIVE_DATE, VOUCHER_DATE, CLIENT_CODE, AMOUNT, DRCR, NARRATION, BANK_CODE, BANK_NAME, REFERENCE_NO, BRANCHCODE, BRANCH_NAME,
	 CHQ_MODE, CHQ_DATE, CHQ_NAME, CL_MODE, ACC_NO,EXCHANGE, SEGMENT, UNAME, POST_DATE, ACTION_FLAG)
VALUES
(
	@TRANSACTION_ID,
	@EFFECTIVE_DATE,
	@VOUCHER_DATE,
	@CLIENT_CODE,
	@AMOUNT,
	'C',
	@NARRATION,
	@BANK_CODE,
	@BANK_NAME,
	@REFERENCE_NO,
	@BRANCHCODE,
	@BRANCH_NAME,
	@CHQ_MODE,
	@CHQ_DATE,
	@CHQ_NAME,
	@CL_MODE,
	@ACC_NO,
	@EXCHANGE,
	@SEGMENT,
	@UNAME,
	GETDATE(),
	'I'
)	

SELECT 'INSERT INTO API_PAYMENT_DETAILS DONE '
/*SET @@SQL = "CREATE TABLE API_RESULT_" + @UNAME
SET @@SQL = @@SQL + " ("
SET @@SQL = @@SQL + " 	POST_STATUS VARCHAR(50),"
SET @@SQL = @@SQL + " 	EXECUTION_REMARK VARCHAR(500)"
SET @@SQL = @@SQL + " )"

EXEC (@@SQL)*/
	
	
SELECT @@ACCOUNTSERVER = ACCOUNTSERVER, @@ACCOUNTDB = ACCOUNTDB FROM PRADNYA.DBO.MULTICOMPANY
WHERE EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT


SELECT @@APIACCOUNTDB = @@SERVERNAME
	
IF @SEGMENT <> 'MFSS'
BEGIN	

SELECT 'UNDER IF CASE '

	--SET @@SQL = "INSERT INTO #API_RESULT "
	SET @@SQL = " EXEC " + @@ACCOUNTSERVER + "." + @@ACCOUNTDB + ".DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
	SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
	SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
	SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
	SET @@SQL = @@SQL + "'" + @NARRATION + "', "
	SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
	SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
	SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
	SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
	SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
	SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
	SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
	SET @@SQL = @@SQL + "'" + @UNAME + "',"
	SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
	--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"
END
ELSE
BEGIN

SELECT 'UNDER ELSE CASE '

	--SET @@SQL = "INSERT INTO #API_RESULT "
	--SET @@SQL = " EXEC " + @@ACCOUNTSERVER + ".BBO_FA.DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = " EXEC ANGELFO.BBO_FA.DBO.RECEIPT_BANK_POSTING "
	SET @@SQL = @@SQL + "'" + @TRANSACTION_ID + "', "
	SET @@SQL = @@SQL + "'" + @EFFECTIVE_DATE + "', "
	SET @@SQL = @@SQL + "'" + @VOUCHER_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CLIENT_CODE + "', "
	SET @@SQL = @@SQL + CONVERT(VARCHAR, @AMOUNT) + ", "
	SET @@SQL = @@SQL + "'" + @NARRATION + "', "
	SET @@SQL = @@SQL + "'" + @BANK_CODE + "', "
	SET @@SQL = @@SQL + "'" + @BANK_NAME + "', "
	SET @@SQL = @@SQL + "'" + @REFERENCE_NO + "', "
	SET @@SQL = @@SQL + "'" + @BRANCHCODE + "', "
	SET @@SQL = @@SQL + "'" + @BRANCH_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_MODE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_DATE + "', "
	SET @@SQL = @@SQL + "'" + @CHQ_NAME + "', "
	SET @@SQL = @@SQL + "'" + @CL_MODE + "', "
	SET @@SQL = @@SQL + "'" + @EXCHANGE + "', "
	SET @@SQL = @@SQL + "'" + @SEGMENT + "', "
	SET @@SQL = @@SQL + "'" + @UNAME + "',"
	SET @@SQL = @@SQL + "'" + @@APIACCOUNTDB + "'"
	--SET @@SQL = @@SQL + "'API_RESULT_" + @UNAME + "'"
END

SELECT 'CASE 1 ', @@SQL

			EXEC (@@SQL)

					SELECT 
					ERROR_NUMBER() AS ErrorNumber,
					ERROR_SEVERITY() AS ErrorSeverity,
					ERROR_STATE() as ErrorState,
					ERROR_PROCEDURE() as ErrorProcedure,
					ERROR_LINE() as ErrorLine,
					ERROR_MESSAGE() as ErrorMessage;    

SELECT 'CASE 2 ', @@SQL
--RETURN
 

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_PAYMENT_DETAILS RD, API_RESULT_DETAILS AR 
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
AND AR.UNAME = @UNAME

DELETE FROM API_RESULT_DETAILS WHERE UNAME = @UNAME


SELECT DISTINCT POST_STATUS,EXECUTION_REMARK FROM 
API_PAYMENT_DETAILS WHERE TRANSACTION_ID = @TRANSACTION_ID


/*SET @@SQL = "DROP TABLE API_RESULT_" + @UNAME

EXEC (@@SQL)*/

/*
SELECT * FROM #API_RESULT

UPDATE RD SET RD.POST_STATUS = AR.POST_STATUS, RD.EXECUTION_REMARK = AR.EXECUTION_REMARK 
FROM API_RECEIPT_DETAILS RD, #API_RESULT AR
WHERE RD.TRANSACTION_ID = @TRANSACTION_ID AND ISNULL(RD.POST_STATUS, '') = ''
*/

GO

-- --------------------------------------------------
-- PROCEDURE dbo.Auto_Entry_verification
-- --------------------------------------------------


CREATE Proc Auto_Entry_verification
as

declare @date varchar(11),@cnt int

SELECT @date=CONVERT(VARCHAR(11),GETDATE(),103)
select @cnt=COUNT(*) from API_PAYMENT_DETAILS WHERE VOUCHER_DATE=@date AND isnull(POST_STATUS,'')='' and EXCHANGE <> ''

IF @CNT >0
  BEGIN 


UPDATE A SET POST_STATUS ='SUCCESS' FROM API_PAYMENT_DETAILS A,ACCOUNT_AB.DBO.LEDGER L,ACCOUNT_AB.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO AND VOUCHER_DATE=@date AND POST_STATUS IS NULL
 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'

 UPDATE A SET POST_STATUS ='SUCCESS' FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO AND VOUCHER_DATE=@date AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'

 UPDATE A SET POST_STATUS ='SUCCESS' FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO AND VOUCHER_DATE=@date AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'

 UPDATE A SET POST_STATUS ='SUCCESS' FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO AND VOUCHER_DATE=@date AND POST_STATUS IS NULL
 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'

 UPDATE A SET POST_STATUS ='SUCCESS' FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO AND VOUCHER_DATE=@date AND POST_STATUS IS NULL
 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'

 UPDATE A SET POST_STATUS ='SUCCESS' FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO AND VOUCHER_DATE=@date AND POST_STATUS IS NULL
 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES'
 END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.rebuild_index
-- --------------------------------------------------
create procedure [dbo].[rebuild_index]  
@database varchar(100)  
as  
begin  
  
declare @db_id int  
Select @db_id = db_id(@database)  
  
if @db_id is Null  
return  
  
SET NOCOUNT ON;  
DECLARE @objectid int;  
DECLARE @indexid int;  
DECLARE @partitioncount bigint;  
DECLARE @schemaname nvarchar(130);  
DECLARE @objectname nvarchar(130);  
DECLARE @indexname nvarchar(130);  
DECLARE @partitionnum bigint;  
DECLARE @partitions bigint;  
DECLARE @frag float;  
DECLARE @command nvarchar(4000);  
-- Conditionally select tables and indexes from the sys.dm_db_index_physical_stats function  
-- and convert object and index IDs to names.  
  
SELECT  
object_id AS objectid,  
index_id AS indexid,  
partition_number AS partitionnum,  
avg_fragmentation_in_percent AS frag  
INTO #work_to_do  
FROM sys.dm_db_index_physical_stats (@db_id, NULL, NULL , NULL, 'LIMITED')  
WHERE avg_fragmentation_in_percent > 10.0 AND index_id > 0;  
  
-- Declare the cursor for the list of partitions to be processed.  
DECLARE partitions CURSOR FOR SELECT objectid,indexid,partitionnum,frag FROM #work_to_do;  
  
-- Open the cursor.  
OPEN partitions;  
  
-- Loop through the partitions.  
WHILE (1=1)  
BEGIN;  
FETCH NEXT  
FROM partitions  
INTO @objectid, @indexid, @partitionnum, @frag;  
IF @@FETCH_STATUS < 0 BREAK;  
SELECT @objectname = QUOTENAME(o.name), @schemaname = QUOTENAME(s.name)  
FROM sys.objects AS o  
JOIN sys.schemas as s ON s.schema_id = o.schema_id  
WHERE o.object_id = @objectid;  
SELECT @indexname = QUOTENAME(name)  
FROM sys.indexes  
WHERE object_id = @objectid AND index_id = @indexid;  
SELECT @partitioncount = count (*)  
FROM sys.partitions  
WHERE object_id = @objectid AND index_id = @indexid;  
  
-- 30 is an arbitrary decision point at which to switch between reorganizing and rebuilding.  
IF @frag < 30.0  
      SET @command = N'ALTER INDEX ' + @indexname + N' ON ' + @schemaname + N'.' + @objectname + N' REORGANIZE';  
IF @frag >= 30.0  
      SET @command = N'ALTER INDEX ' + @indexname + N' ON ' + @schemaname + N'.' + @objectname + N' REBUILD';  
IF @partitioncount > 1  
      SET @command = @command + N' PARTITION=' + CAST(@partitionnum AS nvarchar(10));  
IF @frag >= 30.0  
      set @command = @command +N' WITH (SORT_IN_TEMPDB = ON)' 
 
EXEC (@command);  
PRINT N'Executed: ' + @command;  
END;  
  
-- Close and deallocate the cursor.  
CLOSE partitions;  
DEALLOCATE partitions;  
  
-- Drop the temporary table.  
DROP TABLE #work_to_do;  
  
end

GO

-- --------------------------------------------------
-- PROCEDURE dbo.SP_Pending_Auto_Entry_Status
-- --------------------------------------------------
CREATE proc [dbo].[SP_Pending_Auto_Entry_Status] ( @TRANSACTION_ID VARCHAR(50) ) ---,@EXCHANGE VARCHAR(3),@SEGMENT VARCHAR(15))
as

------EXEC SP_Pending_Auto_Entry_Status 'F02011932347','NSE','FUTURES'
-- /**


DECLARE @CNT INT

 SELECT @CNT = COUNT(1) FROM  API_PAYMENT_DETAILS WHERE TRANSACTION_ID =@TRANSACTION_ID

  IF( @CNT =0 )
    BEGIN 

	SELECT TRANSACTION_ID =''	,VOUCHER_DATE='',	CLIENT_CODE='' ,	AMOUNT='',	BANK_CODE ='',	REFERENCE_NO ='',	EXCHANGE ='',	SEGMENT	='' ,STATUS =''

	
	RETURN
	
	END

	 


IF @TRANSACTION_ID =''
 BEGIN 

select TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' from  ( 
 SELECT A.* FROM API_PAYMENT_DETAILS A with(nolock),ACCOUNT_AB.DBO.LEDGER L with(nolock),ACCOUNT_AB.DBO.LEDGER1 L1 with(nolock)
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO   --AND POST_STATUS IS NULL 
 AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
 UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  --AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   ---AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   ---AND POST_STATUS IS NULL
 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  ---AND POST_STATUS IS NULL
 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   ---AND POST_STATUS IS NULL
 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES' ) a
 RETURN
 END 

 --------------******* Output required based on transaction id ***/

 DECLARE @EXCHANGE VARCHAR(10),@SEGMENT VARCHAR(15)

  SELECT  TOP 1 * Into #API_PAYMENT_DETAILS FROM API_PAYMENT_DETAILS WHERE TRANSACTION_ID =@TRANSACTION_ID

 SELECT TOP 1 @EXCHANGE=EXCHANGE,@SEGMENT=SEGMENT  FROM #API_PAYMENT_DETAILS WHERE TRANSACTION_ID =@TRANSACTION_ID

 IF @EXCHANGE ='BSE' AND @SEGMENT ='CAPITAL'
  BEGIN
	 SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	 FROM #API_PAYMENT_DETAILS A with(nolock),ACCOUNT_AB.DBO.LEDGER L with(nolock),ACCOUNT_AB.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
	 AND L1.DDNO=REFERENCE_NO  -- AND POST_STATUS IS NULL
	  AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
	  AND TRANSACTION_ID =@TRANSACTION_ID
   END 
-- UNION ALL

 IF @EXCHANGE ='NSE' AND @SEGMENT ='CAPITAL'
  BEGIN

	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	  FROM #API_PAYMENT_DETAILS A with(nolock),ANAND1.ACCOUNT.DBO.LEDGER L with(nolock),ANAND1.ACCOUNT.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  --AND POST_STATUS IS NULL
	 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
	  AND TRANSACTION_ID =@TRANSACTION_ID
 END 
---  UNION ALL

 IF @EXCHANGE ='NSE' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	   FROM #API_PAYMENT_DETAILS A with(nolock),ANGELFO.ACCOUNTFO.DBO.LEDGER L with(nolock),ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  -- AND POST_STATUS IS NULL
	 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END 
  -- UNION ALL

 IF @EXCHANGE ='NSX' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	  FROM #API_PAYMENT_DETAILS A with(nolock),ANGELFO.ACCOUNTCURFO.DBO.LEDGER L with(nolock),ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO   --AND POST_STATUS IS NULL
	 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
	 AND TRANSACTION_ID =@TRANSACTION_ID
  END
 ---- UNION ALL

  IF @EXCHANGE ='MCX' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	   FROM #API_PAYMENT_DETAILS A with(nolock),ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L with(nolock),ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  ---AND POST_STATUS IS NULL
	 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END 
------------  UNION ALL

 IF @EXCHANGE ='NCX' AND @SEGMENT ='FUTURES'
  BEGIN
	 SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	 FROM #API_PAYMENT_DETAILS A with(nolock),ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L with(nolock),ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  --- AND POST_STATUS IS NULL
	 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES'  
	  AND TRANSACTION_ID =@TRANSACTION_ID
 END 
 IF @EXCHANGE ='BSE' AND @SEGMENT ='MFSS'
  BEGIN
   
    SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,A.EXCHANGE,A.SEGMENT,STATUS ='SUCCESS'
	 FROM #API_PAYMENT_DETAILS A with(nolock),ANGELFO.BBO_FA.DBO.V2_OFFLINE_LEDGER_ENTRIES V with(nolock)
	 WHERE A.CLIENT_CODE = V.CLTCODE AND AMOUNT=CREDITAMT  
	 AND VOUCHERTYPE='2' AND  VDATE >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND  DDNO=REFERENCE_NO  --- AND POST_STATUS IS NULL
	 AND A.EXCHANGE ='BSE' AND A.SEGMENT ='MFSS'  
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END
 

 Drop table #API_PAYMENT_DETAILS

GO

-- --------------------------------------------------
-- PROCEDURE dbo.SP_Pending_Auto_Entry_Status_Bak_120920
-- --------------------------------------------------
Create proc [dbo].[SP_Pending_Auto_Entry_Status_Bak_120920] ( @TRANSACTION_ID VARCHAR(50) ) ---,@EXCHANGE VARCHAR(3),@SEGMENT VARCHAR(15))
as

------EXEC SP_Pending_Auto_Entry_Status 'F02011932347','NSE','FUTURES'
-- /**


DECLARE @CNT INT

 SELECT @CNT = COUNT(1) FROM  API_PAYMENT_DETAILS WHERE TRANSACTION_ID =@TRANSACTION_ID

  IF( @CNT =0 )
    BEGIN 

	SELECT TRANSACTION_ID =''	,VOUCHER_DATE='',	CLIENT_CODE='' ,	AMOUNT='',	BANK_CODE ='',	REFERENCE_NO ='',	EXCHANGE ='',	SEGMENT	='' ,STATUS =''

	
	RETURN
	
	END

	 


IF @TRANSACTION_ID =''
 BEGIN 

select TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' from  ( 
 SELECT A.* FROM API_PAYMENT_DETAILS A with(nolock),ACCOUNT_AB.DBO.LEDGER L with(nolock),ACCOUNT_AB.DBO.LEDGER1 L1 with(nolock)
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO   --AND POST_STATUS IS NULL 
 AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
 UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  --AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   ---AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   ---AND POST_STATUS IS NULL
 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  ---AND POST_STATUS IS NULL
 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   ---AND POST_STATUS IS NULL
 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES' ) a
 RETURN
 END 

 --------------******* Output required based on transaction id ***/

 DECLARE @EXCHANGE VARCHAR(10),@SEGMENT VARCHAR(15)

 SELECT TOP 1 @EXCHANGE=EXCHANGE,@SEGMENT=SEGMENT  FROM API_PAYMENT_DETAILS WHERE TRANSACTION_ID =@TRANSACTION_ID

 IF @EXCHANGE ='BSE' AND @SEGMENT ='CAPITAL'
  BEGIN
	 SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	 FROM API_PAYMENT_DETAILS A with(nolock),ACCOUNT_AB.DBO.LEDGER L with(nolock),ACCOUNT_AB.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
	 AND L1.DDNO=REFERENCE_NO  -- AND POST_STATUS IS NULL
	  AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
	  AND TRANSACTION_ID =@TRANSACTION_ID
   END 
-- UNION ALL

 IF @EXCHANGE ='NSE' AND @SEGMENT ='CAPITAL'
  BEGIN

	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	  FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  --AND POST_STATUS IS NULL
	 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
	  AND TRANSACTION_ID =@TRANSACTION_ID
 END 
---  UNION ALL

 IF @EXCHANGE ='NSE' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	   FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  -- AND POST_STATUS IS NULL
	 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END 
  -- UNION ALL

 IF @EXCHANGE ='NSX' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	  FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO   --AND POST_STATUS IS NULL
	 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
	 AND TRANSACTION_ID =@TRANSACTION_ID
  END
 ---- UNION ALL

  IF @EXCHANGE ='MCX' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	   FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  ---AND POST_STATUS IS NULL
	 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END 
------------  UNION ALL

 IF @EXCHANGE ='NCX' AND @SEGMENT ='FUTURES'
  BEGIN
	 SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	 FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  --- AND POST_STATUS IS NULL
	 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES'  
	  AND TRANSACTION_ID =@TRANSACTION_ID
 END 
 IF @EXCHANGE ='BSE' AND @SEGMENT ='MFSS'
  BEGIN
   
    SELECT DISTINCT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,A.EXCHANGE,A.SEGMENT,STATUS ='SUCCESS'
	 FROM API_PAYMENT_DETAILS A,ANGELFO.BBO_FA.DBO.V2_OFFLINE_LEDGER_ENTRIES V
	 WHERE A.CLIENT_CODE = V.CLTCODE AND AMOUNT=CREDITAMT  
	 AND VOUCHERTYPE='2' AND  VDATE >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND  DDNO=REFERENCE_NO  --- AND POST_STATUS IS NULL
	 AND A.EXCHANGE ='BSE' AND A.SEGMENT ='MFSS'  
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.SP_SUCCESS_Auto_Entry_Status
-- --------------------------------------------------



CREATE  proc [dbo].[SP_SUCCESS_Auto_Entry_Status] ( @TRANSACTION_ID VARCHAR(50) ) ---,@EXCHANGE VARCHAR(3),@SEGMENT VARCHAR(15))
as

------EXEC SP_Pending_Auto_Entry_Status 'F230718796903','NSE','FUTURES'
-- /**

IF @TRANSACTION_ID =''
 BEGIN 

select TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' from  ( 
 SELECT A.* FROM API_PAYMENT_DETAILS A with(nolock),ACCOUNT_AB.DBO.LEDGER L with(nolock),ACCOUNT_AB.DBO.LEDGER1 L1 with(nolock)
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS' AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
 




 
 UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  AND POST_STATUS ='SUCCESS'
 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS'
 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS'
 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  AND POST_STATUS ='SUCCESS'
 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS'
 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES' ) a
 RETURN
 END 

 --------------******* Output required based on transaction id ***/

 DECLARE @EXCHANGE VARCHAR(10),@SEGMENT VARCHAR(15)

 SELECT TOP 1 @EXCHANGE=EXCHANGE,@SEGMENT=SEGMENT  FROM API_PAYMENT_DETAILS WHERE TRANSACTION_ID =@TRANSACTION_ID

 IF @EXCHANGE ='BSE' AND @SEGMENT ='CAPITAL'
  BEGIN
	 SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	 FROM API_PAYMENT_DETAILS A with(nolock),ACCOUNT_AB.DBO.LEDGER L with(nolock),ACCOUNT_AB.DBO.LEDGER1 L1 with(nolock)
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
	 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS' AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
	  AND TRANSACTION_ID =@TRANSACTION_ID
   END 
-- UNION ALL

 IF @EXCHANGE ='NSE' AND @SEGMENT ='CAPITAL'
  BEGIN

	  SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	  FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  AND POST_STATUS ='SUCCESS'
	 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
	  AND TRANSACTION_ID =@TRANSACTION_ID
 END 
---  UNION ALL

 IF @EXCHANGE ='NSE' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	   FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS'
	 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END 
  -- UNION ALL

 IF @EXCHANGE ='NSX' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' 
	  FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS'
	 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
	 AND TRANSACTION_ID =@TRANSACTION_ID
  END
 ---- UNION ALL

  IF @EXCHANGE ='MCX' AND @SEGMENT ='FUTURES'
  BEGIN
	  SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	   FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO  AND POST_STATUS ='SUCCESS'
	 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
	  AND TRANSACTION_ID =@TRANSACTION_ID
  END 
------------  UNION ALL

 IF @EXCHANGE ='NCX' AND @SEGMENT ='FUTURES'
  BEGIN
	 SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS'
	 FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
	 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
	 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
	 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS ='SUCCESS'
	 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES'  
	  AND TRANSACTION_ID =@TRANSACTION_ID
 END

GO

-- --------------------------------------------------
-- TABLE dbo.API_PAYMENT_DETAILS
-- --------------------------------------------------
CREATE TABLE [dbo].[API_PAYMENT_DETAILS]
(
    [TRANSACTION_ID] VARCHAR(20) NULL,
    [EFFECTIVE_DATE] VARCHAR(20) NULL,
    [VOUCHER_DATE] VARCHAR(20) NULL,
    [CLIENT_CODE] VARCHAR(50) NULL,
    [AMOUNT] MONEY NULL,
    [DRCR] VARCHAR(1) NULL,
    [NARRATION] VARCHAR(234) NULL,
    [BANK_CODE] VARCHAR(10) NULL,
    [BANK_NAME] VARCHAR(100) NULL,
    [REFERENCE_NO] VARCHAR(30) NULL,
    [BRANCHCODE] VARCHAR(20) NULL,
    [BRANCH_NAME] VARCHAR(50) NULL,
    [CHQ_MODE] VARCHAR(1) NULL,
    [CHQ_DATE] VARCHAR(20) NULL,
    [CHQ_NAME] VARCHAR(100) NULL,
    [CL_MODE] VARCHAR(1) NULL,
    [ACC_NO] VARCHAR(20) NULL,
    [EXCHANGE] VARCHAR(10) NULL,
    [SEGMENT] VARCHAR(10) NULL,
    [UNAME] VARCHAR(25) NULL,
    [POST_DATE] DATETIME NULL,
    [ACTION_FLAG] CHAR(1) NULL,
    [POST_STATUS] VARCHAR(20) NULL,
    [EXECUTION_REMARK] VARCHAR(500) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.API_PAYMENT_DETAILS_Hisotry
-- --------------------------------------------------
CREATE TABLE [dbo].[API_PAYMENT_DETAILS_Hisotry]
(
    [TRANSACTION_ID] VARCHAR(20) NULL,
    [EFFECTIVE_DATE] VARCHAR(20) NULL,
    [VOUCHER_DATE] VARCHAR(20) NULL,
    [CLIENT_CODE] VARCHAR(50) NULL,
    [AMOUNT] MONEY NULL,
    [DRCR] VARCHAR(1) NULL,
    [NARRATION] VARCHAR(234) NULL,
    [BANK_CODE] VARCHAR(10) NULL,
    [BANK_NAME] VARCHAR(100) NULL,
    [REFERENCE_NO] VARCHAR(30) NULL,
    [BRANCHCODE] VARCHAR(20) NULL,
    [BRANCH_NAME] VARCHAR(50) NULL,
    [CHQ_MODE] VARCHAR(1) NULL,
    [CHQ_DATE] VARCHAR(20) NULL,
    [CHQ_NAME] VARCHAR(100) NULL,
    [CL_MODE] VARCHAR(1) NULL,
    [ACC_NO] VARCHAR(20) NULL,
    [EXCHANGE] VARCHAR(10) NULL,
    [SEGMENT] VARCHAR(10) NULL,
    [UNAME] VARCHAR(25) NULL,
    [POST_DATE] DATETIME NULL,
    [ACTION_FLAG] CHAR(1) NULL,
    [POST_STATUS] VARCHAR(20) NULL,
    [EXECUTION_REMARK] VARCHAR(500) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.API_RESULT_DETAILS
-- --------------------------------------------------
CREATE TABLE [dbo].[API_RESULT_DETAILS]
(
    [POST_STATUS] VARCHAR(50) NULL,
    [EXECUTION_REMARK] VARCHAR(500) NULL,
    [UNAME] VARCHAR(100) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.Fragmentaion_after_reorg
-- --------------------------------------------------
CREATE TABLE [dbo].[Fragmentaion_after_reorg]
(
    [Schema] NVARCHAR(128) NOT NULL,
    [Table] NVARCHAR(128) NOT NULL,
    [Index] NVARCHAR(128) NULL,
    [avg_fragmentation_in_percent] FLOAT NULL,
    [page_count] BIGINT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.Fragmentaion_before_reorg
-- --------------------------------------------------
CREATE TABLE [dbo].[Fragmentaion_before_reorg]
(
    [Schema] NVARCHAR(128) NOT NULL,
    [Table] NVARCHAR(128) NOT NULL,
    [Index] NVARCHAR(128) NULL,
    [avg_fragmentation_in_percent] FLOAT NULL,
    [page_count] BIGINT NULL
);

GO

-- --------------------------------------------------
-- VIEW dbo.Fragmentaion_details
-- --------------------------------------------------
create view Fragmentaion_details
as 

SELECT S.name as 'Schema',
T.name as 'Table',
I.name as 'Index',
DDIPS.avg_fragmentation_in_percent,
DDIPS.page_count
FROM sys.dm_db_index_physical_stats (DB_ID(), NULL, NULL, NULL, NULL) AS DDIPS
INNER JOIN sys.tables T on T.object_id = DDIPS.object_id
INNER JOIN sys.schemas S on T.schema_id = S.schema_id
INNER JOIN sys.indexes I ON I.object_id = DDIPS.object_id
AND DDIPS.index_id = I.index_id
WHERE DDIPS.database_id = DB_ID()
and I.name is not null
AND DDIPS.avg_fragmentation_in_percent > 0

GO

-- --------------------------------------------------
-- VIEW dbo.FUND_TRANS_MF
-- --------------------------------------------------
CREATE VIEW FUND_TRANS_MF
AS
SELECT TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,EXCHANGE,SEGMENT,POST_STATUS,EXECUTION_REMARK,REFERENCE_NO   
FROM API_PAYMENT_DETAILS WITH(NOLOCK) WHERE EXCHANGE ='BSE' AND SEGMENT ='MFSS'

GO

-- --------------------------------------------------
-- VIEW dbo.ONline_Entry_Vw
-- --------------------------------------------------

 
CREATE View ONline_Entry_Vw
as
select  * from API_PAYMENT_DETAILS (nolock) where POST_STATUS ='SUCCESS'
and POST_DATE>=convert(varchar(11),getdate(),120)

GO

-- --------------------------------------------------
-- VIEW dbo.Pending_Auto_Entry_Status
-- --------------------------------------------------
CREATE  view Pending_Auto_Entry_Status
as

select TRANSACTION_ID,VOUCHER_DATE,CLIENT_CODE,AMOUNT,BANK_CODE,REFERENCE_NO,EXCHANGE,SEGMENT,STATUS ='SUCCESS' from  ( 
 SELECT A.* FROM API_PAYMENT_DETAILS A,ACCOUNT_AB.DBO.LEDGER L,ACCOUNT_AB.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType 
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS IS NULL AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND EXCHANGE ='BSE' AND SEGMENT ='CAPITAL'
 UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANAND1.ACCOUNT.DBO.LEDGER L,ANAND1.ACCOUNT.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='CAPITAL'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTFO.DBO.LEDGER L,ANGELFO.ACCOUNTFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS IS NULL
 AND EXCHANGE ='NSE' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS IS NULL
 AND EXCHANGE ='NSX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO  AND POST_STATUS IS NULL
 AND EXCHANGE ='MCX' AND SEGMENT ='FUTURES'
  UNION ALL
  SELECT A.* FROM API_PAYMENT_DETAILS A,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 L1
 WHERE A.CLIENT_CODE =L.CLTCODE AND AMOUNT=VAMT 
 AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.BOOKTYPE =L1.BookType AND VDT >= CONVERT(vARCHAR(11),GETDATE()-5,120)
 AND L1.DDNO=REFERENCE_NO   AND POST_STATUS IS NULL
 AND EXCHANGE ='NCX' AND SEGMENT ='FUTURES' ) a

GO

