-- DDL Export
-- Server: 10.253.50.28
-- Database: mClass
-- Exported: 2026-02-04T11:48:04.492888

USE mClass;
GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.MoboEmailStore
-- --------------------------------------------------
ALTER TABLE [dbo].[MoboEmailStore] ADD CONSTRAINT [PK_dbo.tblemail_store] PRIMARY KEY ([Id])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.MoboMemberRegistration
-- --------------------------------------------------
ALTER TABLE [dbo].[MoboMemberRegistration] ADD CONSTRAINT [PK__MoboMemb__8DF91CAE060DEAE8] PRIMARY KEY ([MEMBERCODE])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.MoboSmsStore
-- --------------------------------------------------
ALTER TABLE [dbo].[MoboSmsStore] ADD CONSTRAINT [PK_dbo.tblsms_store] PRIMARY KEY ([Id])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.owner
-- --------------------------------------------------
ALTER TABLE [dbo].[owner] ADD CONSTRAINT [PK_dbo.owner] PRIMARY KEY ([Id])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.tblcategory
-- --------------------------------------------------
ALTER TABLE [dbo].[tblcategory] ADD CONSTRAINT [PK_dbo.tblcategory] PRIMARY KEY ([Id])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.tblglobalparams
-- --------------------------------------------------
ALTER TABLE [dbo].[tblglobalparams] ADD CONSTRAINT [PK_dbo.tblglobalparams] PRIMARY KEY ([Id])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.tblmessage_master
-- --------------------------------------------------
ALTER TABLE [dbo].[tblmessage_master] ADD CONSTRAINT [PK_dbo.tblmessage_master] PRIMARY KEY ([Id])

GO

-- --------------------------------------------------
-- PROCEDURE dbo.API_MOBILE_LEDGER_bak
-- --------------------------------------------------
CREATE PROCEDURE [dbo].[API_MOBILE_LEDGER_bak]
	@FROM_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@PARTY_CODE VARCHAR(10)
AS
--EXEC API_MOBILE_LEDGER 'APR  1 2015', 'MAR 31 2016', '0A147' 


DECLARE
	@@MAINREC1 AS CURSOR,
	@@SQL VARCHAR(MAX),
	@@SEGORD1 INT,
	@@ACCOUNTDB1 VARCHAR(30)
	,@@EXCHANGE1 VARCHAR(10)
	,@@SEGMENT1 VARCHAR(10)
	,@@ACCOUNTSVR1 VARCHAR(30)
	,@@SHAREDB1 VARCHAR(20)

CREATE TABLE #API_LEDGER
(
	VDT VARCHAR(10),
	EDT VARCHAR(10),
	NARRATION VARCHAR(500),
	DDNO VARCHAR(30),
	DEBIT_AMT MONEY,
	CREDIT_AMT MONEY,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	SNO INT IDENTITY(1, 1)
)

SET @@MAINREC1 = CURSOR
FOR

SELECT ACCOUNTDB
	,EXCHANGE
	,SEGMENT
	,ACCOUNTSERVER
	,SHAREDB
FROM PRADNYA.DBO.MULTICOMPANY WHERE PRIMARYSERVER = 1
AND EXCHANGE + '-' + SEGMENT IN('NSE-CAPITAL', 'BSE-CAPITAL')

SET @@SEGORD1 = 1

OPEN @@MAINREC1

FETCH NEXT
FROM @@MAINREC1
INTO @@ACCOUNTDB1
	,@@EXCHANGE1
	,@@SEGMENT1
	,@@ACCOUNTSVR1
	,@@SHAREDB1


WHILE @@FETCH_STATUS = 0
BEGIN
	SET @@SQL = "INSERT INTO #API_LEDGER (VDT, EDT,	NARRATION,	DDNO,	DEBIT_AMT,	CREDIT_AMT, EXCHANGE, SEGMENT) "
	SET @@SQL = @@SQL + " EXEC " + @@ACCOUNTDB1 + ".DBO.API_LEDGER_DETAILS '" + @FROM_DATE + "','" + @TO_DATE + "','" + @PARTY_CODE + "','" + @@EXCHANGE1 + "','" + @@SEGMENT1 + "'"
	PRINT @@SQL
	EXEC (@@SQL)

	FETCH NEXT
	FROM @@MAINREC1
	INTO @@ACCOUNTDB1
		,@@EXCHANGE1
		,@@SEGMENT1
		,@@ACCOUNTSVR1
		,@@SHAREDB1
END


SELECT * FROM #API_LEDGER ORDER BY SNO

GO

-- --------------------------------------------------
-- PROCEDURE dbo.CLS_COMMON_CONTRACT_HEADER
-- --------------------------------------------------
create proc CLS_COMMON_CONTRACT_HEADER
(
@TODATE VARCHAR(11)
)
as

select * from pradnya..CLS_OWNER_VW

GO

-- --------------------------------------------------
-- PROCEDURE dbo.CLS_GET_USER_VALIDATE
-- --------------------------------------------------
CREATE PROCEDURE [dbo].[CLS_GET_USER_VALIDATE] (
	@USERNAME VARCHAR(30),
	@PASSWORD VARCHAR(60),
	@PIN VARCHAR(4),
	@MOBILE VARCHAR(10)
)

/*
	SELECT * FROM MOBOUSERS
	CLS_GET_USER_VALIDATE '0a147','S64','',''

	CLS_GET_USER_VALIDATE '','','','996753411'
	CLS_GET_USER_VALIDATE '0A141','S64','',''


	select * from msajag..CLS_TBLPRADNYAUSERS_VW
	select * from msajag..tbladmin

*/
AS
DECLARE @FIRSTLOGIN INT,
	@ERRCODE INT,
	@ERRMSG VARCHAR(8000)
DECLARE @FLDUSERNAME VARCHAR(30),
	@FLDCATEGORY VARCHAR(30),
	@FLDSTNAME VARCHAR(30),
	@FLDPWDEXPIRY INT,
	@FLDATTEMPTCNT INT,
	@FLDSTATUS INT,
	@FLDLOGINFLAG INT,
	@FLDACCESSLVL CHAR(1),
	@FLDIPADD VARCHAR(100),
	@FLDFIRSTLOGIN CHAR(1),
	@FLDFORCELOGOUT INT,
	@LOOPI INT,
	@SPLITIP VARCHAR(20),
	@TOKEN_RESPONSE VARCHAR(255),
	@PROFILEPHOTO VARCHAR(MAX),


	@FLDFIRSTNAME VARCHAR(25),

  @IPLOGIN BIT,
	@USERID INT,
	@PWD VARCHAR(50),
	@LASTLOGIN_LOG VARCHAR(30),
	@FLDADMIN VARCHAR(30),
	@PWD_EXPIRY_DATE VARCHAR(100),
	@FLD_MAC_ID VARCHAR(100),
	@TODAY VARCHAR(10),
	@GROUPID VARCHAR(20),
	@EXPDATE VARCHAR(20),
	@IPADDRESS VARCHAR(100),
	@MACID VARCHAR(100)

SET @ERRCODE = 0
SET @ERRMSG = ''
SET @FIRSTLOGIN = 0
SET @FLDUSERNAME = ''

SET @FLDCATEGORY = ''
SET @FLDSTNAME = ''
SET @LASTLOGIN_LOG = ''
SET @FLDADMIN = ''
SET @PWD_EXPIRY_DATE = ''
SET @USERID = ''
SET @GROUPID = 0
	
IF @PIN <> '' OR @MOBILE <> ''
	BEGIN 
		IF (
		SELECT COUNT(1)
		FROM MOBOUSERS(NOLOCK)
		WHERE Mpin = @PIN
			AND MOBILE = @MOBILE
		) = 
		0
		BEGIN
			SET @ERRCODE = - 1
			SET @ERRMSG = 'INVALID PIN / MOBILE'

			INSERT INTO MSAJAG..V2_LOGIN_LOG (
				USERID,
				USERNAME,
				STATUSNAME,
				STATUSID,
				IPADD,
				ACTION,
				ADDDT
				)
			VALUES (
				@USERID,
				@FLDUSERNAME,
				@USERNAME,
				@FLDCATEGORY,
				@IPADDRESS,
				'LOG_FL',
				GETDATE()
				)

			SELECT FLDUSERNAME = @USERNAME,
				FLDCATEGORY = @FLDCATEGORY,
				FLDSTNAME = @FLDSTNAME,
				FIRSTLOGIN = @FIRSTLOGIN,
				ERRCODE = @ERRCODE,
				ERRMSG = @ERRMSG,
				LASTLOGIN_LOG = @LASTLOGIN_LOG,
				FLDADMIN = @FLDADMIN,
				PWD_EXPIRY_DATE = @PWD_EXPIRY_DATE,
				FLDUSERID = @USERID,
				SQLSCHEMA = '',FLDCATEGORYNAME='',TODAY = '', GROUPID = '',TOKEN_RESPONSE = '', PROFILEPHOTO = ''

			RETURN
		END

		SELECT @USERNAME = A.FLDUSERNAME, @PASSWORD = FLDPASSWORD FROM MOBOUSERS(NOLOCK) A, MSAJAG..CLS_TBLPRADNYAUSERS_VW(NOLOCK) B WHERE A.FLDUSERNAME = B.FLDUSERNAME AND MPIN = @PIN AND MOBILE = @MOBILE	
	END


	

IF (
		SELECT COUNT(1)
		FROM MSAJAG..CLS_TBLPRADNYAUSERS_VW(NOLOCK) A, MSAJAG..TBLADMIN B
		WHERE A.FLDUSERNAME = @USERNAME
			AND A.FLDPASSWORD = @PASSWORD AND A.FLDADMINAUTO = B.FLDAUTO_ADMIN AND B.FLDSTNAME IN ('CLIENT','FAMILY')
		) = 
0
BEGIN
	SET @ERRCODE = - 1
	SET @ERRMSG = 'INVALID USER ID / PASSWORD'

	INSERT INTO MSAJAG..V2_LOGIN_LOG (
		USERID,
		USERNAME,
		STATUSNAME,
		STATUSID,
		IPADD,
		ACTION,
		ADDDT
		)
	VALUES (
		@USERID,
		@FLDUSERNAME,
		@USERNAME,
		@FLDCATEGORY,
		@IPADDRESS,
		'LOG_FL',
		GETDATE()
		)

	SELECT FLDUSERNAME = @USERNAME,
		FLDCATEGORY = @FLDCATEGORY,
		FLDSTNAME = @FLDSTNAME,
		FIRSTLOGIN = @FIRSTLOGIN,
		ERRCODE = @ERRCODE,
		ERRMSG = @ERRMSG,
		LASTLOGIN_LOG = @LASTLOGIN_LOG,
		FLDADMIN = @FLDADMIN,
		PWD_EXPIRY_DATE = @PWD_EXPIRY_DATE,
		FLDUSERID = @USERID,
		SQLSCHEMA = '',FLDCATEGORYNAME='',TODAY = '', GROUPID = '',TOKEN_RESPONSE = '', PROFILEPHOTO = ''

	RETURN
END

SELECT @USERID = A.FLDAUTO,
	@PWD = A.FLDPASSWORD,
	@FLDUSERNAME = A.FLDUSERNAME,
	@FLDCATEGORY = C.FLDCATEGORYCODE,
	@FLDSTNAME = A.FLDSTNAME,
	@FLDPWDEXPIRY = CASE 
		WHEN A.PWD_EXPIRY_DATE < GETDATE()
			THEN 1
		ELSE 0
		END,
	@FLDATTEMPTCNT = CASE 
		WHEN B.FLDATTEMPTCNT > B.FLDMAXATTEMPT
			THEN 1
		ELSE 0
		END,
	@FLDSTATUS = B.FLDSTATUS,
	@FLDLOGINFLAG = B.FLDLOGINFLAG,
	@FLDACCESSLVL = B.FLDACCESSLVL,
	@FLDIPADD = B.FLDIPADD,
	@FLD_MAC_ID = LTRIM(RTRIM(B.FLD_MAC_ID)),
	@FLDFIRSTLOGIN = B.FLDFIRSTLOGIN,
	@FLDFORCELOGOUT = B.FLDFORCELOGOUT,
	@FLDADMIN = D.FLDSTATUS,
	@GROUPID =  A.GROUP_ID,
	@EXPDATE=A.PWD_EXPIRY_DATE,
	@FLDFIRSTNAME =REPLACE(A.FLDFIRSTNAME, A.FLDSTNAME + ' ', '') + ' (' + A.FLDSTNAME +')',
	@TOKEN_RESPONSE = UPPER('M')+CONVERT(VARCHAR,GETDATE(),12)+RIGHT(REPLACE(CONVERT(VARCHAR,GETDATE(),114),':',''),6)+UPPER('O'),
	@PROFILEPHOTO = M.PROFILEIMAGE
FROM MSAJAG..CLS_TBLPRADNYAUSERS_VW A(NOLOCK) LEFT JOIN MSAJAG..TBLUSERCONTROLMASTER B(NOLOCK) ON (A.FLDAUTO = B.FLDUSERID) LEFT JOIN MOBOUSERS M(NOLOCK) ON A.FLDUSERNAME = M.FLDUSERNAME,
		MSAJAG..TBLCATEGORY C(NOLOCK),
		MSAJAG..TBLADMIN D(NOLOCK)
		
WHERE C.FLDCATEGORYCODE = A.FLDCATEGORY
	AND C.FLDADMINAUTO = A.FLDADMINAUTO
	AND D.FLDAUTO_ADMIN = A.FLDADMINAUTO
	AND A.FLDUSERNAME = @USERNAME




EXEC MOBO_SETTOKEN @USERNAME, @TOKEN_RESPONSE
SELECT @FLDCATEGORY = CLS_FLDCATEGORY FROM MSAJAG..CLASSPLUS_CATMAPPING WHERE FLDCATEGORY = @FLDCATEGORY

SET @FIRSTLOGIN = CASE 
		WHEN 
@FLDFIRSTLOGIN = 'N'
			THEN 0
		ELSE 1
		END

IF @FLDPWDEXPIRY > 0
BEGIN
	SET @ERRCODE = - 1
	SET @ERRMSG = 'ACCESS DENIED. YOUR PASSWORD IS EXPIRED'

	SELECT FLDUSERNAME = @FLDUSERNAME,
		FLDCATEGORY = @FLDCATEGORY,
		FLDSTNAME = @FLDSTNAME,
		FIRSTLOGIN = @FIRSTLOGIN,
		ERRCODE = @ERRCODE,
		ERRMSG = @ERRMSG,
		LASTLOGIN_LOG = @LASTLOGIN_LOG,
		FLDADMIN = @FLDADMIN,
		--PWD_EXPIRY_DATE = @PWD_EXPIRY_DATE,
		PWD_EXPIRY_DATE =@EXPDATE,
		FLDPASSWORD = @PWD,
		FLDUSERID = @USERID,
		SQLSCHEMA = '',FLDCATEGORYNAME='',TODAY = '', GROUPID = ''

	INSERT INTO MSAJAG..V2_LOGIN_LOG (
	
	USERID,
		USERNAME,
		STATUSNAME,
		STATUSID,
		IPADD,
		ACTION,
		ADDDT
		)
	VALUES (
		@USERID,
		@FLDUSERNAME,
		@USERNAME,
		@FLDCATEGORY,
		@IPADDRESS,
		'LOG_FL',
		GETDATE()
		)

	RETURN
END

IF @FLDSTATUS > 0
	OR @FLDATTEMPTCNT > 0
	OR @FLDFORCELOGOUT > 0
BEGIN
	SET @ERRCODE = - 1
	SET @ERRMSG = 'ACCESS DENIED. LOGIN ID DISABLED'

	SELECT FLDUSERNAME = @FLDUSERNAME,
		FLDCATEGORY = @FLDCATEGORY,
		FLDSTNAME = @FLDSTNAME,
		FIRSTLOGIN = @FIRSTLOGIN,
		ERRCODE = @ERRCODE,
		ERRMSG = @ERRMSG,
		LASTLOGIN_LOG = @LASTLOGIN_LOG,
		FLDADMIN = @FLDADMIN,
		PWD_EXPIRY_DATE = @PWD_EXPIRY_DATE,
		FLDUSERID = @USERID,
		FLDPASSWORD = @PWD,
		SQLSCHEMA = '',FLDCATEGORYNAME='',TODAY = '', GROUPID = '',
		TOKEN_RESPONSE = '',
		PROFILEPHOTO = ''
	INSERT INTO MSAJAG..V2_LOGIN_LOG (
		USERID,
		USERNAME,
		STATUSNAME,
		STATUSID,
		IPADD,
		ACTION,

		ADDDT
		)
	VALUES (
		@USERID,
		@FLDUSERNAME,
		@USERNAME,
		@FLDCATEGORY,
		@IPADDRESS,
		'LOG_FL',
		GETDATE()
		)

	RETURN
END

IF @FLDACCESSLVL = 'L'
BEGIN
	SET @IPLOGIN = 0

	IF LEN(@FLDIPADD) > 0
	BEGIN
		SET @LOOPI = 1

		WHILE 1 = 1
		BEGIN
		
	SET @SPLITIP =.DBO.CLS_PIECE(@FLDIPADD, '|', @LOOPI)

			IF @SPLITIP IS NULL
				OR @SPLITIP = ''
			BEGIN
				BREAK
			END

			IF LEFT(LTRIM(RTRIM(@IPADDRESS)), LEN(LTRIM(RTRIM(@SPLITIP)))) = LTRIM(RTRIM(@SPLITIP))
			BEGIN
				SET @IPLOGIN = 1

				BREAK
	
		END

			SET @LOOPI = @LOOPI + 1
		END
	END
	
	IF @IPLOGIN = 0
	BEGIN 
		IF @FLD_MAC_ID <> '' AND UPPER(@FLD_MAC_ID) = UPPER(@MACID)
		BEGIN
			SET @IPLOGIN = 1
		END
	END
	
	IF @IPLOGIN = 0
	BEGIN
		SET @ERRCODE = - 1
		SET @ERRMSG = 'ACCESS DENIED. YOUR IP ADDRESS / MAC ID IS NOT REGISTERED IN THE SYSTEM'

		SELECT FLDUSERNAME = @FLDUSERNAME,
			FLDCATEGORY = @FLDCATEGORY,
			FLDSTNAME = @FLDSTNAME,
			FIRSTLOGIN = @FIRSTLOGIN,
			ERRCODE = @ERRCODE,
			ERRMSG = @ERRMSG,
			LASTLOGIN_LOG = @LASTLOGIN_LOG,
			FLDADMIN = @FLDADMIN,
			PWD_EXPIRY_DATE = @PWD_EXPIRY_DATE,
			FLDPASSWORD = @PWD,
		  FLDUSERID = @USERID,
		  SQLSCHEMA = '',FLDCATEGORYNAME='',TODAY = '', GROUPID = ''

		INSERT INTO MSAJAG..V2_LOGIN_LOG (
			USERID,
			USERNAME,
			STATUSNAME,
			STATUSID,
			IPADD,
			ACTION,
			ADDDT
	
		)
		VALUES (
			@USERID,
			@FLDUSERNAME,
			@USERNAME,
			@FLDCATEGORY,
			@IPADDRESS,
			'LOG_FL',
			GETDATE()
			)

		RETURN
	END
END

SELECT @LASTLOGIN_LOG = CONVERT(VARCHAR(20), ADDDT, 113)
FROM MSAJAG..V2_LOGIN_LOG(NOLOCK)
WHERE SNO = (
		SELECT MAX(SNO)

		FROM MSAJAG..V2_LOGIN_LOG(NOLOCK)
		WHERE USERID = @USERID
		)

INSERT INTO MSAJAG..V2_LOGIN_LOG (
	USERID,
	USERNAME,
	STATUSNAME,
	STATUSID,
	IPADD,
	ACTION,
	ADDDT
	)
VALUES (
	@USERID,
	@FLDUSERNAME,
	@USERNAME,
	@FLDCATEGORY,
	@IPADDRESS,
	'LOG_FL',
	GETDATE()
	)


SELECT @PWD_EXPIRY_DATE = 'PASSWORD EXPIRES ON - ' + CASE 
		WHEN DATEDIFF(DD, GETDATE(), T.PWD_EXPIRY_DATE) = 2
			THEN 'THE DAY AFTER TOMORROW'
		ELSE CASE 
				WHEN DATEDIFF(DD, GETDATE(), T.PWD_EXPIRY_DATE) = 1
					THEN 'TOMORROW'
				ELSE CASE 
		
				WHEN DATEDIFF(DD, GETDATE(), T.PWD_EXPIRY_DATE) = 0
							THEN '<U>TODAY</U>'
						ELSE LEFT(CONVERT(VARCHAR, T.PWD_EXPIRY_DATE, 109), 11)
						END
				END
		END
FROM MSAJAG..CLS_TBLPRADNYAUSERS_VW T,
	MSAJAG..TBLADMIN A
WHERE T.FLDADMINAUTO = A.FLDAUTO_ADMIN	AND T.FLDUSERNAME = @FLDUSERNAME AND GETDATE() <= T.PWD_EXPIRY_DATE
 
 DECLARE @FLDCATEGORYNAME VARCHAR(50)
 
 SELECT @FLDCATEGORYNAME =FLDCATEGORYNAME FROM MSAJAG..TBLCATEGORY WHERE FLDCATEGORYCODE= @FLDCATEGORY

 IF @ERRMSG = ''
 BEGIN

	IF (SELECT COUNT(*) FROM MOBOUSERS WHERE FLDUSERNAME = @FLDUSERNAME) = 0
	BEGIN
		INSERT INTO MOBOUSERS(FLDUSERNAME,MPIN,MOBILE,PROFILEIMAGE) VALUES (@FLDUSERNAME,'','','')
	END 	
 END

 
SELECT FLDUSERNAME = @FLDUSERNAME,
	FLDCATEGORY = @FLDCATEGORY,
	FLDSTNAME = @FLDSTNAME,		-- STATUSNAME
	FIRSTLOGIN = @FIRSTLOGIN,
	ERRCODE = @ERRCODE,
	ERRMSG = @ERRMSG,
	LASTLOGIN_LOG = @LASTLOGIN_LOG,
	FLDADMIN = @FLDADMIN,		-- STATUSID
	PWD_EXPIRY_DATE = @PWD_EXPIRY_DATE,
	FLDUSERID = @USERID,
	FLDPASSWORD = @PWD,
	SQLSCHEMA = '',
	FLDCATEGORYNAME= @FLDCATEGORYNAME, 
	--TODAY = CONVERT(VARCHAR(10),GETDATE(),103), 
	TODAY = CONVERT(VARCHAR(10),'01/12/2014',103), 
	GROUPID = @GROUPID,
	FLDFIRSTNAME=@FLDFIRSTNAME,
	TOKEN_RESPONSE = @TOKEN_RESPONSE,
	PROFILEPHOTO = @PROFILEPHOTO

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_API_LEDGER
-- --------------------------------------------------
CREATE PROCEDURE [dbo].[MOBO_API_LEDGER]
	@ClientCode VARCHAR(10),
	@DateFr VARCHAR(11),
	@DateTo VARCHAR(11)
	
AS
/*
exec MOBO_CONFIG_PROCEDURES 
@MENUINDEX='2',@CLIENTCODE='0A141',@DATEFR='01/06/2016',@DATETO='24/07/2017',@SCRIPFR='',@SCRIPTO='',@SETTNOFR='',@SETTNOTO='',@SETTTYPE='',@TOKEN='M170724805853O'

	
	EXEC mClass..MOBO_API_LEDGER '0A141' , '01/04/2015' , '31/03/2016'
	EXEC MOBO_API_LEDGER '', '', '0A147' 
*/



DECLARE
	@@MAINREC1 AS CURSOR,
	@@SQL VARCHAR(MAX),
	@@SEGORD1 INT,
	@@ACCOUNTDB1 VARCHAR(30)
	,@@EXCHANGE1 VARCHAR(10)
	,@@SEGMENT1 VARCHAR(10)
	,@@ACCOUNTSVR1 VARCHAR(30)
	,@@SHAREDB1 VARCHAR(20)

CREATE TABLE #API_LEDGER
(
	VDT VARCHAR(10),
	EDT VARCHAR(10),
	NARRATION VARCHAR(500),
	DDNO VARCHAR(30),
	DEBIT_AMT MONEY,
	CREDIT_AMT MONEY,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	SNO INT IDENTITY(1, 1)
)

--SET @DateFr = 'APR  1 2015'
--SET @DateTo = 'MAR 31 2016'

IF LEN(@DateFr) = 10 AND CHARINDEX('/', @DateFr) > 0
	SET @DateFr = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateFr, 103), 109)


IF LEN(@DateTo) = 10 AND CHARINDEX('/', @DateTo) > 0
	SET @DateTo = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateTo, 103), 109)

SET @@MAINREC1 = CURSOR
FOR

SELECT ACCOUNTDB
	,EXCHANGE
	,SEGMENT
	,ACCOUNTSERVER
	,SHAREDB
FROM PRADNYA.DBO.MULTICOMPANY WHERE PRIMARYSERVER = 1
AND EXCHANGE + '-' + SEGMENT IN('NSE-CAPITAL', 'BSE-CAPITAL')

SET @@SEGORD1 = 1

OPEN @@MAINREC1

FETCH NEXT
FROM @@MAINREC1
INTO @@ACCOUNTDB1
	,@@EXCHANGE1
	,@@SEGMENT1
	,@@ACCOUNTSVR1
	,@@SHAREDB1


WHILE @@FETCH_STATUS = 0
BEGIN
	SET @@SQL = "INSERT INTO #API_LEDGER (VDT, EDT,	NARRATION,	DDNO,	DEBIT_AMT,	CREDIT_AMT, EXCHANGE, SEGMENT) VALUES ('','','#BOLD#" + @@EXCHANGE1 + ' - ' + @@SEGMENT1 + "','','','','','')"
	SET @@SQL = @@SQL + "INSERT INTO #API_LEDGER (VDT, EDT,	NARRATION,	DDNO,	DEBIT_AMT,	CREDIT_AMT, EXCHANGE, SEGMENT) " 
	SET @@SQL = @@SQL + " EXEC " + @@ACCOUNTDB1 + ".DBO.API_LEDGER_DETAILS '" + @DateFr + "','" + @DateTo + "','" + @ClientCode + "','" + @@EXCHANGE1 + "','" + @@SEGMENT1 + "'"
	PRINT @@SQL
	EXEC (@@SQL)

	FETCH NEXT
	FROM @@MAINREC1
	INTO @@ACCOUNTDB1
		,@@EXCHANGE1
		,@@SEGMENT1
		,@@ACCOUNTSVR1
		,@@SHAREDB1
END


SELECT 
	VDT, 
	REMARKS = NARRATION , 
	VOUCHERAMT = CASE WHEN DEBIT_AMT > 0 THEN DEBIT_AMT ELSE CREDIT_AMT END,
	DRCR = CASE WHEN DEBIT_AMT > 0 THEN 'D' ELSE 'C' END
FROM 
	#API_LEDGER 
ORDER BY SNO

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_API_LEDGER_1
-- --------------------------------------------------

CREATE PROCEDURE [dbo].[MOBO_API_LEDGER_1]
	@ClientCode VARCHAR(10),
	@DateFr VARCHAR(11),
	@DateTo VARCHAR(11),
	@SUM_FLAG BIT = 0
	
AS
/*
EXEC MOBO_API_LEDGER_1 '0A141', '01/04/2017', '31/03/2018', 1
exec MOBO_CONFIG_PROCEDURES 
@MENUINDEX='2',@CLIENTCODE='0A141',@DATEFR='01/06/2016',@DATETO='24/07/2017',@SCRIPFR='',@SCRIPTO='',@SETTNOFR='',@SETTNOTO='',@SETTTYPE='',@TOKEN='M170724805853O'

	
	EXEC mClass..MOBO_API_LEDGER '0A141' , '01/04/2015' , '31/03/2016'
	EXEC MOBO_API_LEDGER '', '', '0A147' 
*/



DECLARE
	@@MAINREC1 AS CURSOR,
	@@SQL VARCHAR(MAX),
	@@SEGORD1 INT,
	@@ACCOUNTDB1 VARCHAR(30)
	,@@EXCHANGE1 VARCHAR(10)
	,@@SEGMENT1 VARCHAR(10)
	,@@ACCOUNTSVR1 VARCHAR(30)
	,@@SHAREDB1 VARCHAR(20)
	,@@SESSIONID VARCHAR(20)

SELECT @@SESSIONID = CONVERT(VARCHAR, GETDATE(), 112) + REPLACE(CONVERT(VARCHAR, GETDATE(), 114), ':', '')

CREATE TABLE #API_LEDGER
(
	VDT VARCHAR(10),
	EDT VARCHAR(10),
	NARRATION VARCHAR(500),
	DDNO VARCHAR(30),
	DEBIT_AMT MONEY,
	CREDIT_AMT MONEY,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	SNO INT IDENTITY(1, 1)
)

CREATE TABLE #CLIENT_SUMMARY
(
	CLTCODE VARCHAR(10),
	PARTY_NAME VARCHAR(100),
	ENTITY_CODE VARCHAR(20),
	ENTITY_LEVEL VARCHAR(20),
	LEDGER_AMOUNT MONEY,
	EXCHANGE VARCHAR(20),
	SEGMENT VARCHAR(20),
	SESSIONID VARCHAR(20),
	POPULATE_DATE DATETIME
)

--SET @DateFr = 'APR  1 2015'
--SET @DateTo = 'MAR 31 2016'

IF LEN(@DateFr) = 10 AND CHARINDEX('/', @DateFr) > 0
	SET @DateFr = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateFr, 103), 109)


IF LEN(@DateTo) = 10 AND CHARINDEX('/', @DateTo) > 0
	SET @DateTo = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateTo, 103), 109)

SET @@MAINREC1 = CURSOR
FOR

SELECT ACCOUNTDB
	,EXCHANGE
	,SEGMENT
	,ACCOUNTSERVER
	,SHAREDB
FROM PRADNYA.DBO.MULTICOMPANY WHERE PRIMARYSERVER = 1
AND EXCHANGE + '-' + SEGMENT IN('NSE-CAPITAL', 'BSE-CAPITAL')

SET @@SEGORD1 = 1

OPEN @@MAINREC1

FETCH NEXT
FROM @@MAINREC1
INTO @@ACCOUNTDB1
	,@@EXCHANGE1
	,@@SEGMENT1
	,@@ACCOUNTSVR1
	,@@SHAREDB1


WHILE @@FETCH_STATUS = 0
BEGIN
	IF @sum_flag = 0
	BEGIN
		SET @@SQL = "INSERT INTO #API_LEDGER (VDT, EDT,	NARRATION,	DDNO,	DEBIT_AMT,	CREDIT_AMT, EXCHANGE, SEGMENT) VALUES ('','','#BOLD#" + @@EXCHANGE1 + ' - ' + @@SEGMENT1 + "','','','','','')"
		SET @@SQL = @@SQL + "INSERT INTO #API_LEDGER (VDT, EDT,	NARRATION,	DDNO,	DEBIT_AMT,	CREDIT_AMT, EXCHANGE, SEGMENT) " 
		SET @@SQL = @@SQL + " EXEC " + @@ACCOUNTDB1 + ".DBO.API_LEDGER_DETAILS '" + @DateFr + "','" + @DateTo + "','" + @ClientCode + "','" + @@EXCHANGE1 + "','" + @@SEGMENT1 + "'"
	END

	IF @sum_flag = 1
	BEGIN
		SET @@SQL = "INSERT INTO " + @@ACCOUNTDB1 + ".DBO.FORMULA_CLIENT_MASTER SELECT PARTY_CODE, LONG_NAME, 'PARTY', '', '" + @@SESSIONID + "', GETDATE() FROM MSAJAG.DBO.CLIENT_DETAILS WHERE PARTY_CODE = '" + @ClientCode + "'"
		SET @@SQL = @@SQL + " INSERT INTO #CLIENT_SUMMARY "
		SET @@SQL = @@SQL + " EXEC " + @@ACCOUNTDB1 + ".DBO.CLS_GET_LEDGER_FORMULA_BALANCES '" + @DateTo + "', '" + @@SESSIONID + "', '', 'VDTBAL', '" + @@EXCHANGE1 + "','" + @@SEGMENT1 + "'"
		SET @@SQL = @@SQL + "DELETE FROM " + @@ACCOUNTDB1 + ".DBO.FORMULA_CLIENT_MASTER WHERE CLTCODE = '" + @ClientCode + "'"
	END
	PRINT @@SQL
	EXEC (@@SQL)

	FETCH NEXT
	FROM @@MAINREC1
	INTO @@ACCOUNTDB1
		,@@EXCHANGE1
		,@@SEGMENT1
		,@@ACCOUNTSVR1
		,@@SHAREDB1
END


IF @SUM_FLAG = 1
BEGIN
	INSERT INTO #LEDGER (CLTCODE, LEDGER_AMOUNT, EXCHANGE, SEGMENT)
	SELECT CLTCODE, LEDGER_AMOUNT, EXCHANGE, SEGMENT FROM #CLIENT_SUMMARY
END
ELSE
BEGIN
	SELECT 
		VDT, 
		REMARKS = NARRATION , 
		VOUCHERAMT = CASE WHEN DEBIT_AMT > 0 THEN DEBIT_AMT ELSE CREDIT_AMT END,
		DRCR = CASE WHEN DEBIT_AMT > 0 THEN 'D' ELSE 'C' END
	FROM 
		#API_LEDGER 
	ORDER BY SNO
END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_BROK_TURN_MIS
-- --------------------------------------------------
CREATE PROC [dbo].[MOBO_BROK_TURN_MIS]
	(
	@ClientCode VARCHAR(15),
	@DateFr VARCHAR(11),
	@DateTo VARCHAR(11)

	
	)

	AS
/*
select * from moboreports
*/
	
	-- EXEC MOBO_BROK_TURN_MIS '0A141','01/01/2010','31/12/2017'

	declare @FROMPARTY	VARCHAR(15),
			@TOPARTY	VARCHAR(15)

			SET @FROMPARTY = @ClientCode
			SET @TOPARTY = @ClientCode
			SET  @DateFr = '01/01/2010'
			SET @DateTo = '31/12/2017'

	IF LEN(@FROMPARTY) = 10 AND CHARINDEX('/',@FROMPARTY) > 0
	BEGIN
		SET @FROMPARTY = LEFT(CONVERT(DATETIME,@DateFr,103),11)
	END

	IF LEN(@DateTo) = 10 AND CHARINDEX('/',@DateTo) > 0
	BEGIN
		SET @DateTo = LEFT(CONVERT(DATETIME,@DateTo,103),11)
	END

	IF @TOPARTY = ''
	BEGIN
		SET @TOPARTY = 'zzzzzzzz'
	END

	CREATE TABLE #BROK_TURN
		(
		EXCHANGE	VARCHAR(15),
		TURNOVER	NUMERIC(18,4),
		BROKERAGE	NUMERIC(18,4)
		)

	INSERT INTO #BROK_TURN
	SELECT 
		EXCHANGE	= 'NSE-CAPITAL',
		TURNOVER	= SUM(PAMTTRD + PAMTDEL)
							+ (SUM((CASE WHEN SQTYTRD = 0 AND SAMTTRD <> 0 THEN -SAMTTRD ELSE SAMTTRD END) 
							+ (CASE WHEN SQTYDEL = 0 AND SAMTDEL <> 0 THEN -SAMTDEL ELSE SAMTDEL END))),
		BROKRAGE	= SUM(PBROKTRD+PBROKDEL+SBROKTRD+SBROKDEL)
	FROM 
		MSAJAG..CMBILLVALAN C	(NOLOCK)
	WHERE 
		SAUDA_DATE BETWEEN @DateFr AND @DateTo + ' 23:59:59'
		AND C.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND TRADETYPE NOT IN ( 'SCF','ICF','IR' )


	INSERT INTO #BROK_TURN
	SELECT 
		EXCHANGE	= 'BSE-CAPITAL',
		TURNOVER	= SUM(PAMTTRD + PAMTDEL)
							+ (SUM((CASE WHEN SQTYTRD = 0 AND SAMTTRD <> 0 THEN -SAMTTRD ELSE SAMTTRD END) 
							+ (CASE WHEN SQTYDEL = 0 AND SAMTDEL <> 0 THEN -SAMTDEL ELSE SAMTDEL END))),
		BROKRAGE	= SUM(PBROKTRD+PBROKDEL+SBROKTRD+SBROKDEL)
	FROM 
		BSEDB.DBO.CMBILLVALAN C	(NOLOCK)
	WHERE 
		SAUDA_DATE BETWEEN @DateFr AND @DateTo + ' 23:59:59'
		AND C.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND TRADETYPE NOT IN ( 'SCF','ICF','IR' )


	INSERT INTO #BROK_TURN
	SELECT 
		EXCHANGE	= 'NSE-FUTURES',
		TURNOVER	= SUM(PQTY*PRATE)+SUM(SQTY*SRATE),
		BROKRAGE	= SUM(PBROKAMT+SBROKAMT)
	FROM 
		NSEFO.DBO.FOBILLVALAN C	(NOLOCK)
	WHERE 
		SAUDA_DATE BETWEEN @DateFr AND @DateTo + ' 23:59:59'
		AND C.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND TRADETYPE = 'BT'


	INSERT INTO #BROK_TURN
	SELECT 
		EXCHANGE	= 'NSX-FUTURES',
		TURNOVER	= SUM(PQTY*PRATE)+SUM(SQTY*SRATE),
		BROKRAGE	= SUM(PBROKAMT+SBROKAMT)
	FROM 
		NSECURFO.DBO.FOBILLVALAN C	(NOLOCK)
	WHERE 
		SAUDA_DATE BETWEEN @DateFr AND @DateTo + ' 23:59:59'
		AND C.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND TRADETYPE = 'BT'

	SELECT 
		EXCHANGE,
		TURNOVER	= CONVERT(NUMERIC(18,2),ROUND(ISNULL(SUM(TURNOVER),0),2)),
		BROKERAGE	= CONVERT(NUMERIC(18,2),ROUND(ISNULL(SUM(BROKERAGE),0),2))
	FROM 
		#BROK_TURN
	GROUP BY
		EXCHANGE
	HAVING 
		(ISNULL(SUM(TURNOVER),0)+ISNULL(SUM(BROKERAGE),0)) <> 0
	ORDER BY 
		EXCHANGE

	DROP TABLE #BROK_TURN

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_CLIENTINFO
-- --------------------------------------------------
CREATE PROC [dbo].[MOBO_CLIENTINFO]
(
	@CLIENTCODE VARCHAR(20),
	@SNO INT = 0
)

/*
	EXEC MOBO_CLIENTINFO '0A141'
*/

AS

CREATE TABLE #TEMP
(
	NAME VARCHAR(100),
	VALUE VARCHAR(100)
)
 
IF @SNO = 1 OR @SNO = 0
	BEGIN
		SELECT	PARTY_CODE = @CLIENTCODE, PARTY_NAME = LONG_NAME,
				PARTY_ADDRESS = L_ADDRESS1 + CASE WHEN L_ADDRESS1 <> '' AND L_ADDRESS2 <> '' THEN ',' ELSE CASE WHEN L_ADDRESS1 = '' THEN '' ELSE ' ' END END + L_ADDRESS2
								+ CASE WHEN L_ADDRESS2 <> '' AND L_ADDRESS3 <> '' THEN ',' ELSE CASE WHEN L_ADDRESS2 = '' THEN '' ELSE ' ' END END + L_ADDRESS3
								+ CASE WHEN L_ADDRESS3 <> '' AND L_CITY <> '' THEN ',' ELSE CASE WHEN L_ADDRESS3 = '' THEN '' ELSE ' ' END END + L_CITY
								+ CASE WHEN L_CITY <> '' AND L_ZIP <> '' THEN '-' ELSE CASE WHEN L_CITY = '' THEN '' ELSE ' ' END END + L_ZIP
								+ CASE WHEN L_ZIP <> '' AND L_STATE <> '' THEN ',' ELSE CASE WHEN L_ZIP = '' THEN '' ELSE ' ' END END + L_STATE
								+ CASE WHEN L_STATE <> '' AND L_NATION <> '' THEN ',' ELSE CASE WHEN L_STATE = '' THEN '' ELSE ' ' END END + L_NATION,
				PAN_GIR_NO, DOB = CASE WHEN DOB = '' THEN '' ELSE CONVERT(VARCHAR(11), DOB, 109) END, CL_TYPE,
				PHONE_NO =	RES_PHONE1 + CASE WHEN RES_PHONE1 <> '' AND RES_PHONE2 <> '' THEN ',' ELSE '' END + RES_PHONE2
							+ CASE WHEN RES_PHONE2 <> '' AND OFF_PHONE1 <> '' THEN ',' ELSE '' END + OFF_PHONE1
							+ CASE WHEN OFF_PHONE1 <> '' AND OFF_PHONE2 <> '' THEN ',' ELSE '' END + OFF_PHONE2,
				MOBILE_NO = MOBILE_PAGER, EMAIL_ID = EMAIL, AREA, REGION, BRANCH_CD, SUB_BROKER, TRADER, FAMILY
		FROM
			MSAJAG..CLIENT_DETAILS
		WHERE
			PARTY_CODE = @CLIENTCODE
	END
IF @SNO = 2 OR @SNO = 0
	BEGIN
		SELECT NAME = EXCHANGE + '-' + SEGMENT, VALUE = CONVERT(VARCHAR(10), ACTIVE_DATE, 103) FROM MSAJAG..CLIENT_BROK_DETAILS WHERE CL_CODE = @CLIENTCODE AND GETDATE() <= INACTIVE_FROM
	END

IF @SNO = 3 OR @SNO = 0
	BEGIN
		/*SELECT
			P.BANK_NAME,
			P.BRANCH_NAME,
			B.ACCTYPE,
			B.ACCNO,
			P.IFSCCODE,
			B.DEFAULTBANK
		FROM ACCOUNT..MULTIBANKID B, MSAJAG..POBANK P WHERE P.BANKID = B.BANKID AND B.CLTCODE = @CLIENTCODE*/

		SELECT
			NAME = P.BANK_NAME + ' ' + P.BRANCH_NAME + '-' + P.IFSCCODE,
			VALUE = 'Account Num : - ' + B.ACCNO +  case when B.DEFAULTBANK = 1 then  ' ( Default )' else '' end 			
		FROM ACCOUNT..MULTIBANKID B, MSAJAG..POBANK P WHERE P.BANKID = B.BANKID AND B.CLTCODE = @CLIENTCODE
	END

IF @SNO = 4 OR @SNO = 0
	BEGIN
		SELECT
			DEPOSITORY = C.DPTYPE,
			C.DPID,
			DP_NAME = C.INTRODUCER,
			ACC_NO = C.CLTDPNO,
			ISDEFAULT = case when C4.DEFDP = 1 Then 'Yes' Else '' end
		FROM
			MSAJAG..MULTICLTID C,
			MSAJAG..CLIENT4 C4
		WHERE
			C.PARTY_CODE = C4.PARTY_CODE
			AND C.DPID = C4.BANKID
			AND C.PARTY_CODE = @CLIENTCODE
	END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_CLIENTMARGIN
-- --------------------------------------------------


CREATE PROC [dbo].[MOBO_CLIENTMARGIN]
(
	@CLIENTCODE VARCHAR(10),
	@FORNOTIFICATION VARCHAR(1) = 'N'
)

AS
/*
	EXEC MOBO_CLIENTMARGIN '0C018'
*/

BEGIN TRY
	CREATE TABLE #MARGINSTMT
	(
		SRNO INT IDENTITY(1, 1),
		EXCHANGE VARCHAR(5),
		SEGMENT VARCHAR(10),
		STRREPROTORDER VARCHAR(30),
		INTREPORTORDER2 VARCHAR(30),
		MARGINDATE VARCHAR(11),
		BILLDATE VARCHAR(11),
		PARENTCODE VARCHAR(10),
		PARTY_CODE VARCHAR(10),
		BRANCH_CD VARCHAR(30),
		SUB_BROKER VARCHAR(30),
		TRADER VARCHAR(30),
		SHORT_NAME VARCHAR(100),
		BILLAMOUNT NUMERIC(18, 2),
		PREMIUM NUMERIC(18, 2),
		LEDGERAMOUNT NUMERIC(18, 2),
		CASH_COLL NUMERIC(18, 2),
		NONCASH_COLL NUMERIC(18, 2),
		INITIALMARGIN NUMERIC(18, 2),
		MTMMARGIN NUMERIC(18, 2),
		ADDMARGIN NUMERIC(18, 2),
		MYR NUMERIC(4),
		MMTH NUMERIC(2),
		MDT NUMERIC(2),
		UNCLEARAMOUNT NUMERIC(18, 2),
		MRG_REP_COLL_CASH NUMERIC(18, 2),
		MRG_REP_COLL_NCASH NUMERIC(18, 2)
	)

	CREATE TABLE #FORDATE
	(
		FORDATE VARCHAR(11)
	)

	DECLARE
		@CUR CURSOR,
		@SHRDB VARCHAR(30),
		@EXCHANGE VARCHAR(10),
		@SEGMENT VARCHAR(10),
		@QRY VARCHAR(MAX),
		@FORDATE VARCHAR(11)
	SET @CUR = CURSOR FOR
		SELECT SHAREDB, EXCHANGE, SEGMENT FROM PRADNYA..MULTICOMPANY WHERE SEGMENT = 'FUTURES' AND PRIMARYSERVER = 1
	OPEN @CUR
	FETCH NEXT FROM @CUR INTO @SHRDB, @EXCHANGE, @SEGMENT
	WHILE @@FETCH_STATUS = 0
		BEGIN
			TRUNCATE TABLE #FORDATE
			SET @QRY = 'INSERT INTO #FORDATE (FORDATE) SELECT CONVERT(VARCHAR(11), MAX(MARGINDATE), 109) FROM ' + @SHRDB + '..TBL_CLIENTMARGIN'
			EXEC (@QRY)
			SELECT @FORDATE = FORDATE FROM #FORDATE
			IF @@ROWCOUNT > 0
				BEGIN
					IF @SHRDB = 'BSEFO'
						BEGIN
							SET @QRY = 'INSERT INTO #MARGINSTMT (STRREPROTORDER, INTREPORTORDER2, MARGINDATE, BILLDATE, PARTY_CODE, BRANCH_CD,
										SUB_BROKER, TRADER, SHORT_NAME, BILLAMOUNT, LEDGERAMOUNT, CASH_COLL, NONCASH_COLL, INITIALMARGIN,
										MTMMARGIN, ADDMARGIN, MYR, MMTH, MDT) '
							SET @QRY = @QRY + 'EXEC ' + @SHRDB + '..SP_CLIENTMARGINDETAILS `CLIENT`, `' + @CLIENTCODE + '`, `' + @CLIENTCODE + '`, `' + @CLIENTCODE + '`, `' + @FORDATE + '`, `' + @FORDATE + '`, `%`, `%`, 1,0'
							SET @QRY = REPLACE(@QRY, '`', '''')
							print @QRY
							EXEC(@QRY)
							UPDATE #MARGINSTMT SET EXCHANGE = @EXCHANGE, SEGMENT = @SEGMENT WHERE EXCHANGE IS NULL AND SEGMENT IS NULL
						END
					ELSE IF @SHRDB = 'NSEFO'
						BEGIN
							SET @QRY = 'INSERT INTO #MARGINSTMT (STRREPROTORDER, INTREPORTORDER2, MARGINDATE, BILLDATE, PARENTCODE, PARTY_CODE, BRANCH_CD,
										SUB_BROKER, TRADER, SHORT_NAME, BILLAMOUNT, PREMIUM, LEDGERAMOUNT, CASH_COLL, NONCASH_COLL, INITIALMARGIN,
										MTMMARGIN, ADDMARGIN, MYR, MMTH, MDT, UNCLEARAMOUNT, MRG_REP_COLL_CASH, MRG_REP_COLL_NCASH) '
							SET @QRY = @QRY + 'EXEC ' + @SHRDB + '..SP_CLIENTMARGINDETAILS `CLIENT`, `' + @CLIENTCODE + '`, `' + @CLIENTCODE + '`, `' + @CLIENTCODE + '`, `' + @FORDATE + '`, `' + @FORDATE + '`, `%`, `%`, 1'
							SET @QRY = REPLACE(@QRY, '`', '''')
							print @QRY
							EXEC(@QRY)
							UPDATE #MARGINSTMT SET EXCHANGE = @EXCHANGE, SEGMENT = @SEGMENT WHERE EXCHANGE IS NULL AND SEGMENT IS NULL
						END
					/*ELSE IF @SHRDB = 'BSECURFO'
						BEGIN
							SET @QRY = 'INSERT INTO #MARGINSTMT (STRREPROTORDER, INTREPORTORDER2, MARGINDATE, BILLDATE, PARENTCODE, PARTY_CODE, BRANCH_CD,
										SUB_BROKER, TRADER, SHORT_NAME, BILLAMOUNT, PREMIUM, LEDGERAMOUNT, CASH_COLL, NONCASH_COLL, INITIALMARGIN,
										MTMMARGIN, ADDMARGIN, MYR, MMTH, MDT, UNCLEARAMOUNT) '
							SET @QRY = @QRY + 'EXEC ' + @SHRDB + '..SP_CLIENTMARGINDETAILS `CLIENT`, `' + @CLIENTCODE + '`, `' + @CLIENTCODE + '`, `' + @CLIENTCODE + '`, `' + @FORDATE + '`, `' + @FORDATE + '`, `%`, `%`, 1,0'
							SET @QRY = REPLACE(@QRY, '`', '''')
							print @QRY
							EXEC(@QRY)
							UPDATE #MARGINSTMT SET EXCHANGE = @EXCHANGE, SEGMENT = @SEGMENT WHERE EXCHANGE IS NULL AND SEGMENT IS NULL
						END*/
				END
			FETCH NEXT FROM @CUR INTO @SHRDB, @EXCHANGE, @SEGMENT
		END
	IF @FORNOTIFICATION = 'Y'
		BEGIN
			INSERT INTO #MARGIN (EXCHANGE, SEGMENT, STRREPROTORDER, INTREPORTORDER2, MARGINDATE, BILLDATE, PARENTCODE, PARTY_CODE, BRANCH_CD,
				SUB_BROKER, TRADER, SHORT_NAME, BILLAMOUNT, PREMIUM, LEDGERAMOUNT, CASH_COLL, NONCASH_COLL, INITIALMARGIN, MTMMARGIN, ADDMARGIN,
				MYR, MMTH, MDT, UNCLEARAMOUNT, MRG_REP_COLL_CASH, MRG_REP_COLL_NCASH)
			SELECT EXCHANGE, SEGMENT, STRREPROTORDER, INTREPORTORDER2, MARGINDATE, BILLDATE, PARENTCODE, PARTY_CODE, BRANCH_CD,
				SUB_BROKER, TRADER, SHORT_NAME, BILLAMOUNT, PREMIUM, LEDGERAMOUNT, CASH_COLL, NONCASH_COLL, INITIALMARGIN, MTMMARGIN, ADDMARGIN,
				MYR, MMTH, MDT, UNCLEARAMOUNT, MRG_REP_COLL_CASH, MRG_REP_COLL_NCASH
			FROM #MARGINSTMT
		END
	ELSE
		SELECT * FROM #MARGINSTMT

	DROP TABLE #MARGINSTMT
	DROP TABLE #FORDATE
END TRY
BEGIN CATCH
	DECLARE @ERR_MSG nvarchar(2048) 
		SET @ERR_MSG = ERROR_MESSAGE()
		RAISERROR (@ERR_MSG, 16, 1)
END CATCH

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_COLL_DETAILS
-- --------------------------------------------------
CREATE PROC[dbo].[MOBO_COLL_DETAILS](@CLIENTCODE VARCHAR(10), @DATEFR VARCHAR(11))
AS
/* 
  MOBO_COLL_DETAILS '0A141', 'APR 14 2007' 
  SELECT * FROM MSAJAG..COLLATERALDETAILS 
*/
IF LEN(@DATEFR) <= 10
AND CHARINDEX('/', @DATEFR) > 0
SET @DATEFR = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DATEFR, 103), 109)

CREATE TABLE #TEMP
(
	ID INT IDENTITY(1,1),
	PARTY_CODE VARCHAR(200),
	EXCHANGE VARCHAR(25),
	SEGMENT VARCHAR(25),
	BEFORE_HC MONEY,
	AFTER_HC MONEY,
	CASHCOLL MONEY,
	NONCASHCOLL MONEY,
	FDCOLL MONEY,
	BGCOLL MONEY
)

INSERT INTO #TEMP
	SELECT
	PARTY_CODE, EXCHANGE ,SEGMENT,
	BEFORE_HC = SUM(FINALAMOUNT),
	AFTER_HC = SUM(FINALAMOUNT),
	CASHCOLL = SUM(CASE WHEN COLL_TYPE = 'MARGIN' THEN FINALAMOUNT ELSE 0 END),
	NONCASHCOLL = SUM(CASE WHEN COLL_TYPE = 'SEC' THEN FINALAMOUNT ELSE 0 END),
	FDCOLL = SUM(CASE WHEN COLL_TYPE = 'FD' THEN FINALAMOUNT ELSE 0 END),
	BGCOLL = SUM(CASE WHEN COLL_TYPE = 'BG' THEN FINALAMOUNT ELSE 0 END)
FROM 
	MSAJAG..COLLATERALDETAILS
	/*WHERE EFFDATE LIKE @DATEFR + '%'
	AND PARTY_CODE =
		CASE
	WHEN @CLIENTCODE = ''
	THEN PARTY_CODE
	ELSE @CLIENTCODE
	END*/
GROUP BY 
	EXCHANGE,
	SEGMENT,
	PARTY_CODE	


SELECT ID ,1 AS SRNO, '#BOLD#' + EXCHANGE AS BEFORE_HC ,'#BOLD#'+SEGMENT AS AFTER_HC ,'' AS CASHCOLL,'' AS NONCASHCOLL,'' AS FDCOLL,'' AS BGCOLL FROM #TEMP
UNION ALL
SELECT ID,2, CONVERT(VARCHAR,BEFORE_HC),CONVERT(VARCHAR,AFTER_HC),CONVERT(VARCHAR,CASHCOLL),CONVERT(VARCHAR,NONCASHCOLL),CONVERT(VARCHAR,FDCOLL),CONVERT(VARCHAR,BGCOLL) FROM #TEMP ORDER BY  1,2

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_COLLATERAL
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_COLLATERAL]
(
	@CLTCODE VARCHAR(10)
)
AS
/*
	EXEC MOB_COLLATERAL '0A141'
*/

DECLARE
	@FORDATE VARCHAR(11)
CREATE TABLE #COLLATERAL
(
	CASH MONEY,
	NON_CASH MONEY
)

SELECT @FORDATE = CONVERT(VARCHAR(11), MAX(TRANS_DATE), 109) FROM MSAJAG..COLLATERAL WHERE EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'
IF @@ROWCOUNT > 0
	BEGIN
		INSERT INTO #COLLATERAL (CASH, NON_CASH) SELECT SUM(ACTUALCASH), SUM(ACTUALNONCASH) FROM MSAJAG..COLLATERAL
		WHERE EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL' AND PARTY_CODE = @CLTCODE
		AND TRANS_DATE LIKE @FORDATE + '%'
	END
SELECT @FORDATE = CONVERT(VARCHAR(11), MAX(TRANS_DATE), 109) FROM MSAJAG..COLLATERAL WHERE EXCHANGE = 'BSE' AND SEGMENT = 'CAPITAL'
IF @@ROWCOUNT > 0
	BEGIN
		INSERT INTO #COLLATERAL (CASH, NON_CASH) SELECT SUM(ACTUALCASH), SUM(ACTUALNONCASH) FROM MSAJAG..COLLATERAL
		WHERE EXCHANGE = 'BSE' AND SEGMENT = 'CAPITAL' AND PARTY_CODE = @CLTCODE
		AND TRANS_DATE LIKE @FORDATE + '%'
	END
SELECT SUM(ISNULL(CASH, 0)), SUM(ISNULL(NON_CASH, 0)) FROM #COLLATERAL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_CONFIG_PROCEDURES
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_CONFIG_PROCEDURES]
(
	@MENUINDEX INT,
	@CLIENTCODE VARCHAR(10),
	@DATEFR VARCHAR(11),
	@DATETO VARCHAR(11), 
	@SCRIPFR VARCHAR(10),
	@SCRIPTO VARCHAR(6),
	@SETTNOFR VARCHAR(7),
	@SETTNOTO VARCHAR(7), 
	@SETTTYPE VARCHAR(2),
	@TOKEN VARCHAR(255)
)
/*
	EXEC MOBO_CONFIG_PROCEDURES 2,'0A141','','','','','','','',''

	SP_HELPTEXT MOBO_GET_LEDGER
*/
AS
DECLARE 
	@@SQL VARCHAR(8000),
	@@SPNAME VARCHAR(100),
	@@SP_IN_PARAMS VARCHAR(1000),
	@@SP_OUT_PARAMS VARCHAR(1000),
	@@CONNECTION VARCHAR(50)

if (SELECT COUNT(*) FROM MOBOTOKEN WHERE LOGINID = @CLIENTCODE AND TOKEN = @TOKEN) = 0
	BEGIN
		SELECT 'REQUEST SOURCE IS INVALID!'
	END
ELSE
	BEGIN
		SELECT @@SPNAME = SP_NAME, @@SP_IN_PARAMS = SP_IN_PARAMS, @@SP_OUT_PARAMS =  SP_OUT_PARAMS, @@CONNECTION = CONNECTION FROM MOBOREPORTS WHERE MENU_INDEX = @MENUINDEX
		
		IF @@CONNECTION = ''
			SET @@CONNECTION = DB_name()


		SET @@SQL = ""
		SET @@SQL = @@SQL + "EXEC " + @@CONNECTION + '..' + @@SPNAME 
		SET @@SQL = @@SQL + " '@" + REPLACE(@@SP_IN_PARAMS, '±',''' , ''@') + ''''
		SET @@SQL = REPLACE(@@SQL, '@CLIENTCODE',@CLIENTCODE)
		SET @@SQL = REPLACE(@@SQL, '@DATEFR',@DATEFR)
		SET @@SQL = REPLACE(@@SQL, '@DATETO',@DATETO)
		SET @@SQL = REPLACE(@@SQL, '@SCRIPFR',@SCRIPFR)
		SET @@SQL = REPLACE(@@SQL, '@SCRIPTO',@SCRIPTO)
		SET @@SQL = REPLACE(@@SQL, '@SETTNOFR',@SETTNOFR)
		SET @@SQL = REPLACE(@@SQL, '@SETTNOTO',@SETTNOTO)
		SET @@SQL = REPLACE(@@SQL, '@SETTTYPE',@SETTTYPE)
 
		PRINT @@SQL
		exec(@@SQL)
	END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_DASHBOARD
-- --------------------------------------------------
CREATE PROC [dbo].[MOBO_DASHBOARD]
(
	@CLIENTCODE VARCHAR(10),
	@DATEFR VARCHAR(11)
)
AS
/*
	EXEC MOBo_DASHBOARD '0A141',''
	select * from moboreports
	select * from MoboMemberRegistration
	

*/
CREATE TABLE #DASHBOARD
(
	SRNO INT IDENTITY(0, 1),
	PARTICULARS VARCHAR(40),
	AMOUNT NUMERIC(18, 2),
	REPORT_LINK INT
)
CREATE TABLE #COLLAT
(
	CASH MONEY,
	NON_CASH MONEY
)

CREATE TABLE #SHORT
(
	AMT MONEY
)


IF @DATEFR = ''
	SET @DATEFR = CONVERT(VARCHAR(11), GETDATE(), 109)
IF LEN(@DATEFR) = 10 AND CHARINDEX('/', @DATEFR) > 0
	SET @DATEFR = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DATEFR, 103), 109)

INSERT INTO #DASHBOARD (AMOUNT) EXEC MOBO_LEDGER_BALANCE @DATEFR, @CLIENTCODE
UPDATE #DASHBOARD SET PARTICULARS = 'LEDGER BALANCE',REPORT_LINK = 2 WHERE SRNO = (SELECT MAX(SRNO) FROM #DASHBOARD)

INSERT INTO #DASHBOARD (AMOUNT) EXEC MOBO_LEDGER_BILL @DATEFR, @CLIENTCODE
UPDATE #DASHBOARD SET PARTICULARS = 'TODAY`S BILL',REPORT_LINK = 0 WHERE SRNO = (SELECT MAX(SRNO) FROM #DASHBOARD)

INSERT INTO #COLLAT (CASH, NON_CASH) EXEC MOBO_COLLATERAL @CLIENTCODE

INSERT INTO #DASHBOARD (PARTICULARS, AMOUNT,REPORT_LINK) SELECT 'CASH COLLATERAL', CASH,5 FROM #COLLAT
INSERT INTO #DASHBOARD (PARTICULARS, AMOUNT,REPORT_LINK) SELECT 'NON-CASH COLLATERAL', NON_CASH,5 FROM #COLLAT

INSERT INTO #DASHBOARD (PARTICULARS, AMOUNT,REPORT_LINK) VALUES ('MARGIN REQUIREMENT', 0,7)

INSERT #SHORT EXEC NSEFO..MOBO_MARGIN_RPT @CLIENTCODE,@DATEFR,1

IF (SELECT COUNT(1) FROM #SHORT) > 0
INSERT INTO #DASHBOARD (PARTICULARS, AMOUNT,REPORT_LINK) SELECT 'SHORTFALL/EXCESS', ISNULL(AMT,0),10 FROM #SHORT --VALUES (, 0,10)
ELSE
INSERT INTO #DASHBOARD (PARTICULARS, AMOUNT,REPORT_LINK) VALUES ('SHORTFALL/EXCESS', 0,10)


SELECT * FROM #DASHBOARD ORDER BY SRNO

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_EDIT_CLIENTINFO
-- --------------------------------------------------

---MOBO_EDIT_CLIENTINFO '0A141','',''

CREATE PROC [dbo].[MOBO_EDIT_CLIENTINFO]
(
	@CLIENTCODE VARCHAR(20),
	@MOBILE		VARCHAR(20),
	@EMAIL		VARCHAR(100)
)

AS

BEGIN TRY
    UPDATE 
		MSAJAG..CLIENT_DETAILS 
	SET 
		MOBILE_PAGER = CASE WHEN @MOBILE = '' THEN MOBILE_PAGER ELSE @MOBILE END , 
		EMAIL = CASE WHEN @EMAIL = '' THEN EMAIL ELSE @EMAIL END 
	WHERE 
		CL_CODE = @CLIENTCODE

	IF(@@ROWCOUNT > 0)
		SELECT [MESSAGE] = 'CLIENT MASTER UPDATED SUCCESSFULLY'
	ELSE
		SELECT [MESSAGE] =  'NO DATA TO UPDATE IN CLIENT MASTER'
END TRY
BEGIN CATCH
    SELECT ERROR_MESSAGE() AS [Message];
END CATCH

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_GET_MARGINS
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_GET_MARGINS] 
(
	@CLIENTCODE VARCHAR(15),
	@DATEFR VARCHAR(11)
)

AS
/*
 Exec nsefo..MOBO_GET_MARGINS '0a141', 'Jan  1 2011'


*/
DECLARE @FROMPARTY VARCHAR(15),
		@TOPARTY VARCHAR(15),
		@SEGMENTGROUP VARCHAR(10)

IF @SEGMENTGROUP='' SET @SEGMENTGROUP='ALL'

SET @FROMPARTY = @CLIENTCODE
SET @TOPARTY = @CLIENTCODE



CREATE TABLE #FOMARGIN (
	EXCHANGE VARCHAR(25),
	MDATE VARCHAR(11),
	PARTY_CODE VARCHAR(15),
	INIT_MARGIN MONEY,
	EXPO_MARGIN MONEY,
	ADHOC_MARGIN MONEY,
	CASH MONEY,
	NONCASH MONEY,
	FLAG VARCHAR(10)
	)

CREATE TABLE #COLLATERAL (
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	COLLDATE VARCHAR(11),
	PARTY_CODE VARCHAR(15),
	CASH MONEY,
	NONCASH MONEY
	)

DECLARE @MMDATE VARCHAR(11)

IF (
		SELECT COUNT(1)
		FROM SYS.DATABASES
		WHERE NAME = 'NSEFO' AND (@SEGMENTGROUP ='EQ' OR @SEGMENTGROUP = 'ALL')
		) > 0
BEGIN
	SELECT @MMDATE = LEFT(MAX(TRADE_DATE), 11)
	FROM NSEFO.DBO.FOCLOSING(NOLOCK)
	WHERE TRADE_DATE <= @DATEFR + ' 23:59:59'
       
	INSERT INTO #FOMARGIN
	SELECT EXCHANGE = 'NSEFO',
		MDATE = LEFT(MDATE, 11),
		PARTY_CODE,
		INIT_MARGIN = ISNULL(SUM(PSPANMARGIN), 0),
		EXPO_MARGIN = ISNULL(SUM(MTOM), 0),
		ADHOC_MARGIN = 0,
		CASH = 0,
		NONCASH = 0,
		FLAG = 'M'
	FROM NSEFO.DBO.FOMARGINNEW(NOLOCK)
	WHERE /*PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND LEFT(MDATE, 11) = @MMDATE
		AND */CL_TYPE <> 'TM'
	GROUP BY LEFT(MDATE, 11),
		PARTY_CODE
END


IF (
		SELECT COUNT(1)
		FROM SYS.DATABASES
		WHERE NAME = 'NSECURFO' AND (@SEGMENTGROUP ='EQ' OR @SEGMENTGROUP = 'ALL')
		) > 0
BEGIN
	SELECT @MMDATE = LEFT(MAX(TRADE_DATE), 11)
	FROM NSECURFO.DBO.FOCLOSING(NOLOCK)
	WHERE TRADE_DATE < @DATEFR + ' 23:59:59'

	INSERT INTO #FOMARGIN
	SELECT EXCHANGE = 'NSECURFO',
		MDATE = LEFT(MDATE, 11),
		PARTY_CODE,
		INIT_MARGIN = ISNULL(SUM(PSPANMARGIN), 0),
		EXPO_MARGIN = ISNULL(SUM(MTOM), 0),
		ADHOC_MARGIN = ISNULL(SUM(ADDMARGIN), 0),
		CASH = 0,
		NONCASH = 0,
		FLAG = 'M'
	FROM NSECURFO.DBO.FOMARGINNEW(NOLOCK)
	WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND LEFT(MDATE, 11) = @MMDATE
		AND CL_TYPE <> 'TM'
	GROUP BY LEFT(MDATE, 11),
		PARTY_CODE
END

IF (
		SELECT COUNT(1)
		FROM SYS.DATABASES
		WHERE NAME = 'MCDXCDS' AND (@SEGMENTGROUP ='EQ' OR @SEGMENTGROUP = 'ALL')
		) > 0
BEGIN
	SELECT @MMDATE = LEFT(MAX(TRADE_DATE), 11)
	FROM MCDXCDS.DBO.FOCLOSING(NOLOCK)
	WHERE TRADE_DATE < @DATEFR + ' 23:59:59'

	INSERT INTO #FOMARGIN
	SELECT EXCHANGE = 'MCDXCDS',
		MDATE = LEFT(MDATE, 11),
		PARTY_CODE,
		INIT_MARGIN = ISNULL(SUM(TOTALMARGIN), 0),
		EXPO_MARGIN = ISNULL(SUM(MTOM), 0),
		ADHOC_MARGIN = ISNULL(SUM(ADDMARGIN), 0),
		CASH = 0,
		NONCASH = 0,
		FLAG = 'M'
	FROM MCDXCDS.DBO.FOMARGINNEW(NOLOCK)
	WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND LEFT(MDATE, 11) = @MMDATE
		AND CL_TYPE <> 'TM'
	GROUP BY LEFT(MDATE, 11),
		PARTY_CODE
END

IF (
		SELECT COUNT(1)
		FROM SYS.DATABASES
		WHERE NAME = 'MCDX' AND (@SEGMENTGROUP ='COMM' OR @SEGMENTGROUP = 'ALL')
		) > 0
BEGIN
	SELECT @MMDATE = LEFT(MAX(TRADE_DATE), 11)
	FROM MCDX.DBO.FOCLOSING(NOLOCK)
	WHERE TRADE_DATE < @DATEFR + ' 23:59:59'

	INSERT INTO #FOMARGIN
	SELECT EXCHANGE = 'MCDX',
		MDATE = LEFT(MDATE, 11),
		PARTY_CODE,
		INIT_MARGIN = ISNULL(SUM(PMARGIN), 0),
		EXPO_MARGIN = ISNULL(SUM(ADDMARGIN), 0),
		ADHOC_MARGIN = ISNULL(SUM(ADDMARGIN), 0),
		CASH = 0,
		NONCASH = 0,
		FLAG = 'M'
	FROM MCDX.DBO.FOMARGINNEW(NOLOCK)
	WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND LEFT(MDATE, 11) = @MMDATE
		AND CL_TYPE <> 'TM'
	GROUP BY LEFT(MDATE, 11),
		PARTY_CODE
END

IF (
		SELECT COUNT(1)
		FROM SYS.DATABASES
		WHERE NAME = 'NCDX' AND (@SEGMENTGROUP ='COMM' OR @SEGMENTGROUP = 'ALL')
		) > 0
BEGIN
	SELECT @MMDATE = LEFT(MAX(TRADE_DATE), 11)
	FROM NCDX.DBO.FOCLOSING(NOLOCK)
	WHERE TRADE_DATE < @DATEFR + ' 23:59:59'

	INSERT INTO #FOMARGIN
	SELECT EXCHANGE = 'NCDX',
		MDATE = LEFT(MDATE, 11),
		PARTY_CODE,
		INIT_MARGIN = ISNULL(SUM(PSPANMARGIN), 0),
		EXPO_MARGIN = ISNULL(SUM(MTOM), 0),
		ADHOC_MARGIN = ISNULL(SUM(ADDMARGIN), 0),
		CASH = 0,
		NONCASH = 0,
		FLAG = 'M'
	FROM NCDX.DBO.FOMARGINNEW(NOLOCK)
	WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND LEFT(MDATE, 11) = @MMDATE
		AND CL_TYPE <> 'TM'
	GROUP BY LEFT(MDATE, 11),
		PARTY_CODE
END

DELETE
FROM #FOMARGIN
WHERE (INIT_MARGIN + EXPO_MARGIN + ADHOC_MARGIN) = 0

/*
SELECT @MMDATE = LEFT(MAX(TRANS_DATE), 11)
FROM MSAJAG.DBO.COLLATERAL(NOLOCK)

INSERT INTO #COLLATERAL
SELECT EXCHANGE,
	SEGMENT,
	COLLDATE = LEFT(TRANS_DATE, 11),
	PARTY_CODE,
	CASH = ISNULL(SUM(CASH), 0),
	NONCASH = ISNULL(SUM(NONCASH), 0)
FROM MSAJAG.DBO.COLLATERAL(NOLOCK)
WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND LEFT(TRANS_DATE, 11) = @MMDATE
GROUP BY EXCHANGE,
	SEGMENT,
	LEFT(TRANS_DATE, 11),
	PARTY_CODE

INSERT INTO #FOMARGIN
SELECT EXCHANGE = CASE WHEN EXCHANGE IN ('MCX','NCX') THEN EXCHANGE + 'COM'
						WHEN EXCHANGE IN ('NSX','MCD') THEN EXCHANGE + 'CUR'
						ELSE EXCHANGE + LEFT(SEGMENT,3) END,
	COLLDATE,
	PARTY_CODE,
	INIT_MARGIN = 0,
	EXPO_MARGIN = 0,
	ADHOC_MARGIN = 0,
	CASH = CASH,
	NONCASH = NONCASH,
	FLAG = 'C'
FROM #COLLATERAL
*/

SELECT EXCHANGE,MDATE,PARTY_CODE,INIT_MARGIN,EXPO_MARGIN,ADHOC_MARGIN
FROM #FOMARGIN
ORDER BY PARTY_CODE, FLAG 

DROP TABLE #FOMARGIN
DROP TABLE #COLLATERAL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_HOLDPARTY
-- --------------------------------------------------
CREATE PROC [dbo].[MOBO_HOLDPARTY] 
(
	@CLIENTCODE VARCHAR(10)
)

AS

CREATE TABLE #TEMP
(
	SCRIP_CD VARCHAR(12),
	SERIES VARCHAR(10),
	SETT_NO VARCHAR(7),
	SETT_TYPE VARCHAR(2),
	QTY NUMERIC,
	CERTNO VARCHAR(16),
	HOLDQTY NUMERIC,
	PQTY NUMERIC
)

INSERT INTO #TEMP (SCRIP_CD,SERIES,SETT_NO,SETT_TYPE,QTY,CERTNO,HOLDQTY,PQTY)
exec BSEDB..mobo_rpt_nsedelholdparty @STATUSID='CLIENT',@STATUSNAME=@CLIENTCODE,@FROMPARTY=@CLIENTCODE,@TOPARTY=@CLIENTCODE,@FROMSCRIP='0',@TOSCRIP='ZZ',@BDPID='',@BCLTDPID='',@BRANCH='%',@CL_TYPE='%'

SELECT SCRIPT_DETAILS = SCRIP_CD + ' - ' + SERIES + ' - ' + SETT_NO + ' - ' + SETT_TYPE, QTY,HOLDQTY,PQTY  FROM #TEMP

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_LEDGER_BALANCE
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_LEDGER_BALANCE]
(
	@FORDATE VARCHAR(11),
	@CLTCODE VARCHAR(10)
)
AS
/*
	EXEC MOBo_LEDGER_BALANCE '31/05/2017', '0A147'
*/
IF LEN(@FORDATE) = 10 AND CHARINDEX('/', @FORDATE) > 0
	SET @FORDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FORDATE, 103), 109)

DECLARE
	@SDATE VARCHAR(11),
	@CUR CURSOR,
	@ACCDB VARCHAR(15),
	@SQL VARCHAR(MAX)
CREATE TABLE #BALANCE
(
	AMOUNT MONEY
)
CREATE TABLE #PARAMETER
(
	SDT_CUR VARCHAR(11)
)
SET @CUR = CURSOR FORWARD_ONLY FOR
	SELECT ACCOUNTDB FROM PRADNYA..MULTICOMPANY WHERE PRIMARYSERVER = 1
OPEN @CUR
FETCH NEXT FROM @CUR INTO @ACCDB
WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @ACCDB <> 'BBO_FA' AND @ACCDB <> 'ACCOUNTMCDXCDSP' AND @ACCDB <> 'ACCOUNTCURBFOPC'
			BEGIN
				SET @SQL = 'INSERT INTO #PARAMETER (SDT_CUR) SELECT CONVERT(VARCHAR(11), SDTCUR, 109) FROM ' + @ACCDB + '..PARAMETER WHERE ''' + CONVERT(VARCHAR(11), GETDATE(), 109) + ''' BETWEEN SDTCUR AND LDTCUR'
				PRINT @SQL
				EXEC (@SQL)
				SELECT @SDATE = SDT_CUR FROM #PARAMETER
				SET @SQL = 'INSERT INTO #BALANCE (AMOUNT) SELECT SUM(CASE WHEN DRCR = ''D'' THEN VAMT ELSE -VAMT END) FROM ' + @ACCDB + '..LEDGER WHERE CLTCODE = '''+ @CLTCODE +''' AND  VDT >= ''' + @SDATE + ''' AND VDT <= ''' + @FORDATE + ' 23:59'''
				EXEC(@SQL)
				PRINT @SQL
			END
		TRUNCATE TABLE #PARAMETER
		FETCH NEXT FROM @CUR INTO @ACCDB
	END
SELECT SUM(ISNULL(AMOUNT, 0)) FROM #BALANCE

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_LEDGER_BILL
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_LEDGER_BILL]
(
	@FORDATE VARCHAR(11),
	@CLTCODE VARCHAR(10)
)
AS
/*
	EXEC MOB_LEDGER_BILL '31/05/2012', '0A141'
*/
IF LEN(@FORDATE) = 10 AND CHARINDEX('/', @FORDATE) > 0
	SET @FORDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FORDATE, 103), 109)

DECLARE
	@CUR CURSOR,
	@ACCDB VARCHAR(15),
	@SQL VARCHAR(MAX)
CREATE TABLE #BALANCE
(
	AMOUNT MONEY
)
SET @CUR = CURSOR FORWARD_ONLY FOR
	SELECT ACCOUNTDB FROM PRADNYA..MULTICOMPANY WHERE PRIMARYSERVER = 1
OPEN @CUR
FETCH NEXT FROM @CUR INTO @ACCDB
WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @ACCDB <> 'BBO_FA' AND @ACCDB <> 'ACCOUNTMCDXCDSP' AND @ACCDB <> 'ACCOUNTCURBFOPC'
			BEGIN
				SET @SQL = 'INSERT INTO #BALANCE (AMOUNT) SELECT SUM(CASE WHEN DRCR = ''D'' THEN VAMT ELSE -VAMT END) FROM ' + @ACCDB + '..LEDGER WHERE CLTCODE = '''+ @CLTCODE +''' AND VTYP IN (''15'', ''21'') AND VDT LIKE ''' + @FORDATE + '%'''
				EXEC(@SQL)
				PRINT @SQL
			END
		FETCH NEXT FROM @CUR INTO @ACCDB
	END
SELECT SUM(ISNULL(AMOUNT, 0)) FROM #BALANCE

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_NOTIFICATION_BY_USER
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_NOTIFICATION_BY_USER]
(
	@CLIENTCODE VARCHAR(20)
)

AS

UPDATE MOBO_USER_NOTIFICATION SET [STATUS] = 1 WHERE USERID = @CLIENTCODE 

SELECT * FROM MOBO_USER_NOTIFICATION WHERE USERID = @CLIENTCODE ORDER BY GENERATION_DATE DESC

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_SETTOKEN
-- --------------------------------------------------
CREATE PROC [dbo].[MOBO_SETTOKEN]
(
	@LOGINID VARCHAR(25),
	@TOKEN NVARCHAR(255)
)

AS

IF((SELECT COUNT(*) FROM MOBOTOKEN WHERE LOGINID = @LOGINID) = 0)
	BEGIN
		INSERT INTO MOBOTOKEN VALUES (@LOGINID, @TOKEN)
	END
ELSE
	BEGIN
		DELETE FROM MOBOTOKEN WHERE LOGINID = @LOGINID
		INSERT INTO MOBOTOKEN VALUES (@LOGINID, @TOKEN)
	END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_SHORTAGE_PAYINSHRT_COMBINE
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_SHORTAGE_PAYINSHRT_COMBINE]
(
	@CLIENTCODE VARCHAR(10),
	@DateFr VARCHAR(11)
)
AS
DECLARE
	@SETT_NO VARCHAR(7),
	@SETT_TYPE VARCHAR(2),
	@SETTCUR CURSOR

/*
EXEC MOBO_SHORTAGE_PAYINSHRT_COMBINE 'Sep  7 2011', '0a141'
select * from msajag..DELTRANS where party_code = '0a141'

SELECT SETT_NO, SETT_TYPE FROM MSAJAG..SETT_MST
WHERE SEC_PAYIN LIKE 'Sep  7 2011' + '%'
AND SETT_TYPE IN ('N', 'W')


*/


IF @DateFr = '' 
	SET @DateFr = convert(varchar(11),Getdate(),109)
	 	 
IF LEN(@DateFr) <= 10 AND CHARINDEX('/', @DateFr) > 0
	BEGIN
		SET @DateFr = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateFr, 103), 109)
	END

CREATE TABLE #SHORTAGE
(
	SETT_NO VARCHAR(7),
	SETT_TYPE VARCHAR(2),
	PARTY_CODE VARCHAR(10),
	SCRIP_CD  VARCHAR(12),
	SERIES VARCHAR(3),
	BUYTRADEQTY INT,
	BUYREDQTY INT,
	SELLTRADEQTY INT,
	SELLRECQTY INT,
	BUYSHORTAGE INT,
	SELLSHORTAGE INT,
	CL_RATE NUMERIC(18, 4),
	FLAG INT,
	ISIN VARCHAR(12)
)

CREATE TABLE #SHORTAGE_FINAL
(
	SETT_NO VARCHAR(7),
	SETT_TYPE VARCHAR(2),
	PARTY_CODE VARCHAR(10),
	SCRIP_CD  VARCHAR(12),
	SERIES VARCHAR(3),
	BUYTRADEQTY INT,
	BUYREDQTY INT,
	SELLTRADEQTY INT,
	SELLRECQTY INT,
	BUYSHORTAGE INT,
	SELLSHORTAGE INT,
	CL_RATE NUMERIC(18, 4),
	FLAG INT,
	ISIN VARCHAR(12),
	SCRIP_NAME VARCHAR(50)
)
SET @SETTCUR = CURSOR FOR
SELECT SETT_NO, SETT_TYPE FROM MSAJAG..SETT_MST
WHERE SEC_PAYIN LIKE @DateFr + '%'
AND SETT_TYPE IN ('N', 'W')
OPEN @SETTCUR
FETCH NEXT FROM @SETTCUR INTO @SETT_NO, @SETT_TYPE
WHILE @@FETCH_STATUS = 0
	BEGIN
		set @SETT_NO = '2006020'
		set @SETT_TYPE = 'N'
		INSERT INTO #SHORTAGE
		EXEC MSAJAG..MOBO_RPT_SHORTAGEPAYIN  @SETT_NO, @SETT_NO, @SETT_TYPE, @CLIENTCODE
		FETCH NEXT FROM @SETTCUR INTO @SETT_NO, @SETT_TYPE
	END
CLOSE @SETTCUR
DEALLOCATE @SETTCUR

INSERT INTO #SHORTAGE_FINAL
SELECT *, SCRIP_CD FROM #SHORTAGE

SET @SETTCUR = CURSOR FOR
SELECT SETT_NO, SETT_TYPE FROM BSEDB..SETT_MST
WHERE SEC_PAYIN LIKE @DateFr + '%'
AND SETT_TYPE IN ('D', 'C')
OPEN @SETTCUR
FETCH NEXT FROM @SETTCUR INTO @SETT_NO, @SETT_TYPE
WHILE @@FETCH_STATUS = 0
	BEGIN
		INSERT INTO #SHORTAGE_FINAL
		EXEC BSEDB..MOBO_RPT_SHORTAGEPAYIN @SETT_NO, @SETT_NO, @SETT_TYPE, @CLIENTCODE
		FETCH NEXT FROM @SETTCUR INTO @SETT_NO, @SETT_TYPE
	END
CLOSE @SETTCUR
DEALLOCATE @SETTCUR

SELECT EXCHANGE = (CASE WHEN SETT_TYPE IN ('N', 'W') THEN 'NSE' ELSE 'BSE' END),
SETT_NO + '-' + SETT_TYPE + '  ' +SCRIP_NAME AS SETTNO, BUYSHORTAGE, SELLSHORTAGE, CL_RATE
FROM #SHORTAGE_FINAL
ORDER BY PARTY_CODE, SCRIP_NAME, SETT_NO, SETT_TYPE

DROP TABLE #SHORTAGE
DROP TABLE #SHORTAGE_FINAL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_USER_LOG
-- --------------------------------------------------


CREATE PROC [dbo].[MOBO_USER_LOG]
(
	@CLIENTCODE [varchar](20),
	@MOBILE [varchar](10),
	@EMAIL [varchar](10),
	@MEMBERCODE [varchar](15),
	@DEVICEINFO [varchar](8000),
	@LOGTIME varchar(50) 
)
AS


INSERT INTO MOBO_LOGGED_USERS (USERID,CAT,STNAME,MEMBERCODE,DEVICE_INFO,LOGGED_IN_TIME) VALUES (@CLIENTCODE,@MOBILE,@EMAIL,@MEMBERCODE,@DEVICEINFO,@LOGTIME)

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_USER_UPDATEPIN
-- --------------------------------------------------
CREATE PROC [dbo].[MOBO_USER_UPDATEPIN] 
(
		@USERNAME VARCHAR(30),
		@PASSWORD VARCHAR(60),
		@MOBILE VARCHAR(10),
		@PIN VARCHAR(4)
)
AS	

DECLARE 
	@@UNAME VARCHAR(30),
	@@PWD VARCHAR(60),
	@@MOB VARCHAR(10)
/*
select * from mobousers
SELECT CL_CODE, MOBILE_PAGER FROM MSAJAG..CLIENT_DETAILS WHERE CL_CODE = '0A141' AND MOBILE_PAGER = '9967534119' 
SELECT * FROM MSAJAG..TBLPRADNYAUSERS WHERE FLDUSERNAME = '0A141'
EXEC MOBO_USER_UPDATEPIN '0A141','S64','9967534119','1234'

*/
SET @@UNAME = ''
SET @@MOB = ''

SELECT @@UNAME = FLDUSERNAME FROM MSAJAG..TBLPRADNYAUSERS WHERE FLDUSERNAME = @USERNAME AND FLDPASSWORD = @PASSWORD
IF @@UNAME = '' 
	BEGIN
		SELECT RESULT = UPPER('USER CREDENTIAL IS INVALID!'), ERROR = LOWER('true')
		RETURN
	END
ELSE
	BEGIN
		SELECT @@MOB = MOBILE_PAGER FROM MSAJAG..CLIENT_DETAILS(NOLOCK) WHERE CL_CODE = @@UNAME AND MOBILE_PAGER = @MOBILE
		PRINT @@ROWCOUNT
		IF(@@ROWCOUNT = 0 AND @@MOB = '')
			BEGIN
				SELECT RESULT = UPPER('MOBILE NO IS INVALID!'), ERROR = LOWER('true')
				RETURN	
			END
		ELSE
			BEGIN
				IF (SELECT COUNT(*) FROM MOBOUSERS WHERE FLDUSERNAME = @USERNAME) = 0
				BEGIN
					INSERT INTO MOBOUSERS(FLDUSERNAME,MPIN,MOBILE,PROFILEIMAGE) VALUES (@USERNAME,@PIN,@MOBILE,'')
				END
				ELSE 
				BEGIN
					UPDATE MOBOUSERS SET MPIN = @PIN, MOBILE = @MOBILE WHERE FLDUSERNAME = @USERNAME
				END  
				SELECT RESULT = UPPER('PIN IS UPDATED SUCCESSFULLY!'), ERROR = LOWER('FALSE')
				RETURN
			END

	END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBO_USER_VALIDATION
-- --------------------------------------------------

CREATE PROC [dbo].[MOBO_USER_VALIDATION]
(
	@USERNAME VARCHAR(30),
	@PASSWORD VARCHAR(60),
	@PIN VARCHAR(4),
	@MOBILE VARCHAR(10)
)

AS
/*
EXEC MOBO_USER_VALIDATION 'bhrt','s64'
*/
EXEC CLS_GET_USER_VALIDATE @USERNAME, @PASSWORD, @PIN, @MOBILE

GO

-- --------------------------------------------------
-- PROCEDURE dbo.moboCheckUserOfNewMember
-- --------------------------------------------------
CREATE PROC [dbo].[moboCheckUserOfNewMember]
(
	@USERNAME VARCHAR(30),
	@PASSWORD VARCHAR(60)
)
/*
	EXEC  moboCheckUserOfNewMember '0a141','123'
*/
as
DECLARE
	@ERRCODE VARCHar(10),
	@ERRMSG VARCHAR(8000)
IF (
		SELECT COUNT(1)
		FROM MSAJAG..CLS_TBLPRADNYAUSERS_VW(NOLOCK)
		WHERE FLDUSERNAME = @USERNAME
			AND FLDPASSWORD = @PASSWORD
		) = 
0
BEGIN
	SET @ERRCODE = 'true'
	SET @ERRMSG = 'INVALID USER ID / PASSWORD FOR NEW MEMBER'
END	
ELSE
	BEGIN
	SET @ERRCODE = 'false'
	SET @ERRMSG = ''
END

SELECT ERROR = @ERRCODE, RESULT = @ERRMSG

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MoBoGenNotification
-- --------------------------------------------------
CREATE PROC [dbo].[MoBoGenNotification]
	@DateFr VARCHAR(11) = '',
	@TYPE VARCHAR(15) = 'LEDGER',
	@UNAME VARCHAR(30) = 'SYSTEM'

/*

exec MoBoGenNotification '01/12/2017','',''
SELECT * FROM ACCOUNT..LEDGER WHERE CLTCODE = '0A143'
SELECT * FROM MOBOFCIREGID WHERE USERID = 'R91820'
INSERT INTO MOBOFCIREGID VALUES ('M90637','dDOENtpmUNI:APA91bG1n_ZFYDYe9B-PbVa71MtudsANh0ZEUV18RJ9DYPFKF-Zf9CTpDrKQzCIGy4EyMLdDWTl-BaGJfcr4dRyPwY_jh2-x_ymRv2n3r7v1_uUxDJ-OSGeCP3B02pSglyO2EunKZct8')
*/
AS
DECLARE @USERID VARCHAR(30) 
DECLARE @DEVICE VARCHAR(MAX) 
DECLARE @DateTo VARCHAR(11)

IF LEN(@DateFr) = 10 AND CHARINDEX('/', @DateFr) > 0
	SET @DateFr = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateFr, 103), 109)

	SET @DateTo = CONVERT(VARCHAR(11), CONVERT(DATETIME, @DateFr, 103), 109)

--SELECT ID, Title = 'MoBo Alerts', Body = 'Ledger Balance is 125.62', Sound = '', DeviceID FROM MOBOFCIREGID



CREATE TABLE #LEDGER
(
	CLTCODE VARCHAR(20), 
	LEDGER_AMOUNT MONEY,
	DEVICE VARCHAR(MAX), 
	EXCHANGE VARCHAR(3), 
	SEGMENT VARCHAR(30)
)

DECLARE db_cursor CURSOR FOR 
SELECT USERID, DEVICEID FROM MOBOFCIREGID 

OPEN db_cursor
	FETCH NEXT FROM db_cursor INTO @USERID, @DEVICE

	WHILE @@FETCH_STATUS = 0   
	BEGIN
		EXEC MOBO_API_LEDGER_1  @USERID, @DateFr,@DateTo, 1	

		UPDATE #LEDGER SET DEVICE = @DEVICE WHERE CLTCODE = @USERID
		FETCH NEXT FROM db_cursor INTO @USERID, @DEVICE   
	END

CLOSE db_cursor
DEALLOCATE db_cursor

INSERT INTO MOBO_USER_NOTIFICATION
SELECT CLTCODE, Title = 'MoBo Alert',  Body = 'Ledger Balance is : ' + CONVERT (VARCHAR, SUM(LEDGER_AMOUNT)), '', DEVICE, GETDATE(), @UNAME, 0 FROM #LEDGER GROUP BY CLTCODE, EXCHANGE, SEGMENT, DEVICE
--select * from MOBO_USER_NOTIFICATION where status = 0

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MOBOGETCONFIGURATION
-- --------------------------------------------------

CREATE PROC [dbo].[MOBOGETCONFIGURATION]
(
	@TOKENID VARCHAR(500),
	@MEMBERCODE VARCHAR(15)
)

AS
	DECLARE @TOKENID_DB VARCHAR(500)
	SET @TOKENID_DB  = '123456'

IF(@TOKENID = @TOKENID_DB)
BEGIN
	SELECT * FROM MOBOMEMBERREGISTRATION WHERE MEMBERCODE = CASE WHEN ISNULL(@MEMBERCODE, '') = '' THEN MEMBERCODE ELSE @MEMBERCODE END AND IS_ACTIVE = 1 
END
ELSE 
BEGIN 
	SELECT 'INVALID REQUEST!' 
END

GO

-- --------------------------------------------------
-- PROCEDURE dbo.moboGetMenu
-- --------------------------------------------------

/*
	moboGetMenu '',''
*/
CREATE PROC [dbo].[moboGetMenu]
(
	@STRCATEGORY VARCHAR(20),
	@USERID VARCHAR(20)
)
AS
SELECT ID ,MENU_INDEX,MENU_NAME,MENU_TITLE,MENU_ICON,MENU_GRP,MENU_ORDER,SP_NAME,SP_IN_PARAMS, SP_OUT_PARAMS,COLUMN_TEXT, COLUMN_WIDTH, COLUMN_COLOR,RPT_TITLE, COLUMN_ALIGN  FROM MOBOREPORTS
ORDER BY MENu_INDEX

GO

-- --------------------------------------------------
-- PROCEDURE dbo.MoBoSendNotification
-- --------------------------------------------------
CREATE PROC [dbo].[MoBoSendNotification]
/*
exec MoBoSendNotification ''
*/
as

--SELECT ID, Title = 'MoBo Alerts', Body = 'Ledger Balance is 125.62', Sound = '', DeviceID FROM MOBOFCIREGID

select * from MOBO_USER_NOTIFICATION where status = 0

GO

-- --------------------------------------------------
-- PROCEDURE dbo.moboSetFCIRegistrationID
-- --------------------------------------------------

CREATE PROC [dbo].[moboSetFCIRegistrationID]
(
	@USERNAME VARCHAR(30),
	@TOKEN VARCHAR(8000)
)

AS
/*
use mclass
exec MOBOSETFCIREGISTRATIONID '0a147','dnguHMxWfME:APA91bFBJKiZnTfjej04jpigaE3383jfKPqNEtzUplFPVGeLCRSy86IIc2LKdEQOTaTfZyk8fNWuNBZGBaiqYFjB4DxD2FSVU6ThthLApXKJdqk8RHG4RUbOaG5L6d6dPEdtkz-25Mea'
exec moboSetFCIRegistrationID 
@USERNAME='0a147',@TOKEN='dnguHMxWfME:APA91bFBJKiZnTfjej04jpigaE3383jfKPqNEtzUplFPVGeLCRSy86IIc2LKdEQOTaTfZyk8fNWuNBZGBaiqYFjB4DxD2FSVU6ThthLApXKJdqk8RHG4RUbOaG5L6d6dPEdtkz-25Mea'

	SELECT * FROM MOBOFCIREGID

truncate table MOBOFCIREGID
dnguHMxWfME:APA91bFBJKiZnTfjej04jpigaE3383jfKPqNEtzUplFPVGeLCRSy86IIc2LKdEQOTaTfZyk8fNWuNBZGBaiqYFjB4DxD2FSVU6ThthLApXKJdqk8RHG4RUbOaG5L6d6dPEdtkz-25Mea
	
*/

IF((SELECT COUNT(*) FROM MOBOFCIREGID WHERE USERID = @USERNAME OR DeviceID = @TOKEN) = 0 )
 BEGIN
	INSERT INTO MOBOFCIREGID(USERID, DeviceID) VALUES (@USERNAME,@TOKEN)
	print '1'
 END
Else IF((SELECT COUNT(*) FROM MOBOFCIREGID WHERE DeviceID = @TOKEN) > 0 )
 begin
	DELETE MOBOFCIREGID WHERE DeviceID = @TOKEN
	INSERT INTO MOBOFCIREGID(USERID, DeviceID) VALUES (@USERNAME,@TOKEN)
	print '2'
 end
ELSE
 BEGIN
	DELETE MOBOFCIREGID WHERE USERID = @USERNAME
	INSERT INTO MOBOFCIREGID(USERID, DeviceID) VALUES (@USERNAME,@TOKEN)
	print '3'
 END

 SELECT RESULT = 'UPDATED', ERROR = lower('false')

GO

-- --------------------------------------------------
-- TABLE dbo.a
-- --------------------------------------------------
CREATE TABLE [dbo].[a]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [MEMBERCODE] VARCHAR(15) NOT NULL,
    [DISPLAY_TEXT] VARCHAR(25) NULL,
    [API_PATH] VARCHAR(500) NULL,
    [LOGO_URL] VARCHAR(500) NULL,
    [SPLASH_URL] VARCHAR(500) NULL,
    [COLOR_PRIMARY] VARCHAR(7) NULL,
    [COLOR_PRIMARY_DARK] VARCHAR(7) NULL,
    [COLOR_ACCENT] VARCHAR(7) NULL,
    [IS_ACTIVE] BIT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.MOBO_LOGGED_USERS
-- --------------------------------------------------
CREATE TABLE [dbo].[MOBO_LOGGED_USERS]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [USERID] VARCHAR(20) NULL,
    [CAT] VARCHAR(10) NULL,
    [STNAME] VARCHAR(10) NULL,
    [MEMBERCODE] VARCHAR(15) NULL,
    [DEVICE_INFO] VARCHAR(8000) NULL,
    [LOGGED_IN_TIME] VARCHAR(50) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.MOBO_USER_NOTIFICATION
-- --------------------------------------------------
CREATE TABLE [dbo].[MOBO_USER_NOTIFICATION]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [USERID] VARCHAR(20) NULL,
    [TITLE] VARCHAR(20) NULL,
    [BODY] VARCHAR(100) NULL,
    [SOUND] VARCHAR(10) NULL,
    [DEVICEID] VARCHAR(8000) NULL,
    [GENERATION_DATE] DATETIME NULL,
    [GENERATED_BY] VARCHAR(30) NULL,
    [STATUS] TINYINT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.MoboEmailStore
-- --------------------------------------------------
CREATE TABLE [dbo].[MoboEmailStore]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    [user_id] BIGINT NOT NULL,
    [user_email] NVARCHAR(MAX) NULL,
    [generation_time] DATETIME NOT NULL,
    [activation_code] NVARCHAR(MAX) NULL,
    [is_valid] BIT NOT NULL,
    [request_source] NVARCHAR(MAX) NULL,
    [Otp] NVARCHAR(MAX) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.moboFCIRegID
-- --------------------------------------------------
CREATE TABLE [dbo].[moboFCIRegID]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [UserID] VARCHAR(30) NULL,
    [DeviceID] VARCHAR(8000) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.MoboMemberRegistration
-- --------------------------------------------------
CREATE TABLE [dbo].[MoboMemberRegistration]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [MEMBERCODE] VARCHAR(15) NOT NULL,
    [DISPLAY_TEXT] VARCHAR(25) NULL,
    [API_PATH] VARCHAR(500) NULL,
    [LOGO_URL] VARCHAR(500) NULL,
    [SPLASH_URL] VARCHAR(500) NULL,
    [COLOR_PRIMARY] VARCHAR(7) NULL,
    [COLOR_PRIMARY_DARK] VARCHAR(7) NULL,
    [COLOR_ACCENT] VARCHAR(7) NULL,
    [REQUEST_TOKEN] VARCHAR(255) NULL,
    [IS_ACTIVE] BIT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.moboReports
-- --------------------------------------------------
CREATE TABLE [dbo].[moboReports]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [MENU_INDEX] INT NULL,
    [MENU_NAME] VARCHAR(20) NULL,
    [MENU_TITLE] VARCHAR(25) NULL,
    [MENU_ICON] VARCHAR(500) NULL,
    [MENU_GRP] INT NULL,
    [MENU_ORDER] INT NULL,
    [SP_NAME] VARCHAR(100) NULL,
    [SP_IN_PARAMS] VARCHAR(1000) NULL,
    [SP_OUT_PARAMS] VARCHAR(1000) NULL,
    [COLUMN_TEXT] VARCHAR(500) NULL,
    [COLUMN_WIDTH] VARCHAR(500) NULL,
    [COLUMN_COLOR] VARCHAR(500) NULL,
    [RPT_TITLE] VARCHAR(100) NULL,
    [COLUMN_ALIGN] VARCHAR(500) NULL,
    [CONNECTION] VARCHAR(50) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.MoboSmsStore
-- --------------------------------------------------
CREATE TABLE [dbo].[MoboSmsStore]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    [user_id] VARCHAR(20) NOT NULL,
    [user_mobile_no] NVARCHAR(MAX) NULL,
    [generation_time] DATETIME NOT NULL,
    [activation_code] NVARCHAR(MAX) NULL,
    [is_valid] BIT NOT NULL,
    [request_source] NVARCHAR(MAX) NULL,
    [Otp] NVARCHAR(MAX) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.MOBOTOKEN
-- --------------------------------------------------
CREATE TABLE [dbo].[MOBOTOKEN]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [LOGINID] VARCHAR(25) NULL,
    [TOKEN] NVARCHAR(255) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.moboUsers
-- --------------------------------------------------
CREATE TABLE [dbo].[moboUsers]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [FldUserName] VARCHAR(25) NULL,
    [mPin] INT NULL,
    [Mobile] VARCHAR(10) NULL,
    [ProfileImage] VARCHAR(MAX) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.owner
-- --------------------------------------------------
CREATE TABLE [dbo].[owner]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    [company] NVARCHAR(MAX) NULL,
    [addr1] NVARCHAR(MAX) NULL,
    [addr2] NVARCHAR(MAX) NULL,
    [phone] NVARCHAR(MAX) NULL,
    [zip] NVARCHAR(MAX) NULL,
    [city] NVARCHAR(MAX) NULL,
    [state] NVARCHAR(MAX) NULL,
    [fax] NVARCHAR(MAX) NULL,
    [email] NVARCHAR(MAX) NULL,
    [smtp_srv_name] NVARCHAR(MAX) NULL,
    [logo_file_path] NVARCHAR(MAX) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.tblcategory
-- --------------------------------------------------
CREATE TABLE [dbo].[tblcategory]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    [category_id] INT NOT NULL,
    [category_Name] NVARCHAR(MAX) NULL,
    [short_desc] NVARCHAR(MAX) NULL,
    [Is_Active] BIT NOT NULL,
    [Is_Deleted] BIT NOT NULL,
    [created_by] BIGINT NOT NULL,
    [created_on] DATETIME NOT NULL,
    [modified_by] BIGINT NOT NULL,
    [modified_on] DATETIME NOT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.tblglobalparams
-- --------------------------------------------------
CREATE TABLE [dbo].[tblglobalparams]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    [fldpwdminlength] SMALLINT NOT NULL,
    [fldpwdmaxlength] SMALLINT NOT NULL,
    [max_rejection_allow] SMALLINT NOT NULL,
    [fldoldpassword] TINYINT NOT NULL,
    [fldspclchar] NVARCHAR(MAX) NULL,
    [fldencryption] NVARCHAR(MAX) NULL,
    [islower] BIT NOT NULL,
    [isupper] BIT NOT NULL,
    [fldblockpwd] NVARCHAR(MAX) NULL,
    [pwdexpirydays] INT NOT NULL,
    [fldcaptcha] SMALLINT NOT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.tblmessage_master
-- --------------------------------------------------
CREATE TABLE [dbo].[tblmessage_master]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    [msg_id] INT NOT NULL,
    [msg_text] NVARCHAR(MAX) NULL,
    [msg_title] NVARCHAR(MAX) NULL,
    [msg_modue] NVARCHAR(MAX) NULL
);

GO

