-- DDL Export
-- Server: 10.253.50.28
-- Database: ACCOUNTNBFC
-- Exported: 2026-01-30T16:30:13.859833

USE ACCOUNTNBFC;
GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_ACNAME_SL] CHECK (ltrim(rtrim([ACNAME]))<>'')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_BOOKTYPE_SL] CHECK (ltrim(rtrim([BOOKTYPE]))<>'')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_CLTCODE_SL] CHECK (ltrim(rtrim([CLTCODE]))<>'')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_DRCR_SL] CHECK (ltrim(rtrim([DRCR]))='D' OR ltrim(rtrim([DRCR]))='C')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_EDT_SL] CHECK ([EDT]<>'')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_VDT_SL] CHECK ([VDT]<>'')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_BLANK_VNO_SL] CHECK (ltrim(rtrim([VNO]))<>'')

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NON_ZERO_VTYP_SL] CHECK ([VTYP]<>(0))

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_ACNAME_SL] CHECK ([ACNAME] IS NOT NULL)

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_BOOKTYPE_SL] CHECK ([BOOKTYPE] IS NOT NULL)

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_CLTCODE_SL] CHECK ([CLTCODE] IS NOT NULL)

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_EDT_SL] CHECK ([EDT] IS NOT NULL)

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_VDT_SL] CHECK ([VDT] IS NOT NULL)

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_VNO_SL] CHECK ([VNO] IS NOT NULL)

GO

-- --------------------------------------------------
-- CHECK dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [NOT_NULL_VTYP_SL] CHECK ([VTYP] IS NOT NULL)

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.FORMULA_CLIENT_MASTER
-- --------------------------------------------------
ALTER TABLE [dbo].[FORMULA_CLIENT_MASTER] ADD CONSTRAINT [PK_FORMULA_CLIENT_MASTER] PRIMARY KEY ([CLTCODE], [SESSION_ID])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.Ledger
-- --------------------------------------------------
ALTER TABLE [dbo].[Ledger] ADD CONSTRAINT [PK_Ledger] PRIMARY KEY ([Vtyp], [Vno], [Lno], [Booktype])

GO

-- --------------------------------------------------
-- PK_UNIQUE dbo.ledger1
-- --------------------------------------------------
ALTER TABLE [dbo].[ledger1] ADD CONSTRAINT [PK_ledger1_yog1] PRIMARY KEY ([L1_SNo])

GO

-- --------------------------------------------------
-- PROCEDURE dbo.BANK_FUNDS_REPORTING
-- --------------------------------------------------



--EXEC BANK_FUNDS_REPORTING 'APR  1 2013', 'NOV 27 2013', 'BANK01'

CREATE PROCEDURE BANK_FUNDS_REPORTING
	@FR_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@BANK_CODE VARCHAR(10)
AS

CREATE TABLE #LEDGER_PL
(
	VDT DATETIME,
	EDT DATETIME,
	LONG_NAME VARCHAR(100),
	BANK_ACC_NO VARCHAR(30),
	UCC_CODE VARCHAR(10),
	CLTCODE VARCHAR(10),
	CLIENT_PAN VARCHAR(30),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	VTYP INT,
	BOOKTYPE VARCHAR(3),
	PDT DATETIME,
	OPBAL MONEY
)

INSERT INTO #LEDGER_PL
SELECT
	VDT, EDT, LONG_NAME, ACCNO, UCC_CODE, CL_CODE, PAN_GIR_NO, NARRATION = L.NARRATION, VNO, SETT_NO = '', CHQ_NO = '',  
	DRAMOUNT = CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END,
	CRAMOUNT = CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END, 0, EXCHANGE, SEGMENT, L.VTYP, L.BOOKTYPE, PDT, OPBAL = 0
FROM
	MSAJAG..CLIENT_DETAILS C, (SELECT CLTCODE, VAMT, DRCR, NARRATION, VDT, EDT, PDT, VTYP, VNO, BOOKTYPE FROM LEDGER WHERE VDT BETWEEN @FR_DATE AND @TO_DATE + ' 23:59') L, VMAST V, OWNER O, MULTIBANKID M
WHERE
	C.CL_CODE = L.CLTCODE
	AND C.CL_CODE = M.CLTCODE
	AND L.VTYP = V.VTYPE
	AND EXISTS(SELECT VNO FROM LEDGER LL WHERE VDT BETWEEN @FR_DATE AND @TO_DATE + ' 23:59' AND CLTCODE = @BANK_CODE AND L.VNO = LL.VNO AND L.VTYP = LL.VTYP AND L.BOOKTYPE = LL.BOOKTYPE)
	AND L.CLTCODE <> @BANK_CODE
ORDER BY L.CLTCODE, CONVERT(DATETIME, CONVERT(VARCHAR(11), VDT, 109)), PDT

UPDATE L SET L.CHQ_NO = L1.DDNO FROM #LEDGER_PL L, LEDGER1 L1
WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE

UPDATE L SET L.SETT_NO = L1.SETT_NO FROM #LEDGER_PL L, BILLPOSTED L1
WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE

UPDATE L SET BANK_ACC_NO = ACCNO FROM #LEDGER_PL L, MULTIBANKID L1
WHERE L.CLTCODE = L1.CLTCODE AND DEFAULTBANK = 1 


CREATE TABLE #OPBAL
(
	CLTCODE VARCHAR(10),
	OPBAL MONEY
)

INSERT INTO #OPBAL
SELECT CLTCODE, AMOUNT = SUM(AMOUNT) FROM
(
	SELECT CLTCODE = L.CLTCODE, AMOUNT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, PARAMETER P
	WHERE L.CLTCODE = @BANK_CODE AND L.VDT >= SDTCUR AND VDT < @FR_DATE AND @FR_DATE BETWEEN SDTCUR AND LDTCUR AND VTYP <> 18
	GROUP BY L.CLTCODE
	UNION ALL
	SELECT CLTCODE = L.CLTCODE, AMOUNT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, PARAMETER P
	WHERE L.CLTCODE = @BANK_CODE AND @FR_DATE BETWEEN SDTCUR AND LDTCUR
	AND VDT BETWEEN SDTCUR AND LDTCUR AND VTYP = 18
	GROUP BY L.CLTCODE
) L
GROUP BY CLTCODE

UPDATE L SET L.OPBAL = O.OPBAL FROM #LEDGER_PL L, #OPBAL O


SELECT VDT,
	EDT,
	LONG_NAME,
	BANK_ACC_NO,
	UCC_CODE,
	CLTCODE,
	CLIENT_PAN,
	NARRATION,
	VNO,
	SETT_NO,
	CHQ_NO,
	DRAMOUNT,
	CRAMOUNT,
	RUNNING_BALANCE,
	OPBAL,
	PDT FROM #LEDGER_PL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.CLIENT_FUNDS_REPORTING
-- --------------------------------------------------


--EXEC CLIENT_FUNDS_REPORTING 'APR  1 2018', 'NOV 27 2018'

CREATE PROCEDURE [dbo].[CLIENT_FUNDS_REPORTING]
	@FR_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@FR_CODE VARCHAR(10) = '0',
	@TO_CODE VARCHAR(10) = 'ZZZZZ'
AS

CREATE TABLE #CLIENT_DETAILS
(
	UCC_CODE VARCHAR(15), 
	CL_CODE VARCHAR(10), 
	LONG_NAME VARCHAR(100), 
	PAN_GIR_NO VARCHAR(20)
)

INSERT INTO #CLIENT_DETAILS
SELECT UCC_CODE, CL_CODE, LONG_NAME, PAN_GIR_NO 
FROM MSAJAG..CLIENT_DETAILS WHERE CL_CODE BETWEEN @FR_CODE AND @TO_CODE



CREATE TABLE #LEDGER_PL
(
	UCC_CODE VARCHAR(10),
	CLTCODE VARCHAR(10),
	LONG_NAME VARCHAR(100),
	CLIENT_PAN VARCHAR(30),
	VDT DATETIME,
	EDT DATETIME,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	VTYPE VARCHAR(30),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	VTYP INT,
	BOOKTYPE VARCHAR(3),
	OPBAL MONEY,
	PDT DATETIME,
	SNO INT IDENTITY(1, 1)
)

INSERT INTO #LEDGER_PL
SELECT
	UCC_CODE, CL_CODE, LONG_NAME, PAN_GIR_NO, VDT, EDT, EXCHANGE, SEGMENT, SETT_NO = '', CHQ_NO = '', VDESC, NARRATION = L.NARRATION, VNO, 
	DRAMOUNT = CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END,
	CRAMOUNT = CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END, 0, L.VTYP, L.BOOKTYPE, 0, PDT
FROM
	#CLIENT_DETAILS C, 
	(SELECT CLTCODE, VAMT, DRCR, NARRATION, VDT, EDT, PDT, VTYP, VNO, BOOKTYPE FROM LEDGER WHERE VDT BETWEEN @FR_DATE AND @TO_DATE + ' 23:59' AND CLTCODE BETWEEN @FR_CODE AND @TO_CODE) L, 
	VMAST V, OWNER O
WHERE
	C.CL_CODE = CLTCODE
	AND L.VTYP = V.VTYPE
ORDER BY CLTCODE, CONVERT(DATETIME, CONVERT(VARCHAR(11), VDT, 109)), PDT

UPDATE L SET L.CHQ_NO = L1.DDNO FROM #LEDGER_PL L, LEDGER1 L1
WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE

UPDATE L SET L.SETT_NO = L1.SETT_NO FROM #LEDGER_PL L, BILLPOSTED L1
WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE


CREATE TABLE #OPBAL
(
	CLTCODE VARCHAR(10),
	OPBAL MONEY
)

INSERT INTO #OPBAL
SELECT CLTCODE, AMOUNT = SUM(AMOUNT) FROM
(
	SELECT CLTCODE = L.CLTCODE, AMOUNT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, (SELECT DISTINCT CLTCODE FROM #LEDGER_PL) L1, PARAMETER P
	WHERE L.CLTCODE = L1.CLTCODE AND L.VDT >= SDTCUR AND VDT < @FR_DATE AND @FR_DATE BETWEEN SDTCUR AND LDTCUR AND VTYP <> 18
	GROUP BY L.CLTCODE
	UNION ALL
	SELECT CLTCODE = L.CLTCODE, AMOUNT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, (SELECT DISTINCT CLTCODE FROM #LEDGER_PL) L1, PARAMETER P
	WHERE L.CLTCODE = L1.CLTCODE AND @FR_DATE BETWEEN SDTCUR AND LDTCUR
	AND VDT BETWEEN SDTCUR AND LDTCUR AND VTYP = 18
	GROUP BY L.CLTCODE
) L
GROUP BY CLTCODE

UPDATE L SET L.OPBAL = O.OPBAL FROM #LEDGER_PL L, #OPBAL O WHERE L.CLTCODE = O.CLTCODE

--UPDATE L SET RUNNING_BALANCE = (SELECT SUM(CRAMOUNT - DRAMOUNT) FROM #LEDGER_PL L1 WHERE O.CLTCODE = L1.CLTCODE AND L.CLTCODE = L1.CLTCODE AND L1.SNO < L.SNO) FROM #LEDGER_PL L, #OPBAL O
--WHERE L.CLTCODE = O.CLTCODE

SELECT 
	UCC_CODE, 
	CLTCODE, 
	LONG_NAME, 
	CLIENT_PAN, 
	VDT,
	EDT,
	EXCHANGE,
	SEGMENT,
	SETT_NO,
	CHQ_NO,
	VTYPE,
	NARRATION,
	VNO,
	DRAMOUNT,
	CRAMOUNT,
	RUNNING_BALANCE,
	OPBAL,
	PDT 
FROM #LEDGER_PL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.CLS_GET_LEDGER2_FORMULA_BALANCES
-- --------------------------------------------------

--EXEC V2_GET_LEDGER_FORMULA_BALANCES 'MAR 31 2013', '9999999999', 0, ''  

/*
SELECT * FROM FORMULA_CLIENT_MASTER WHERE CLTCODE = '0A147'

INSERT INTO FORMULA_CLIENT_MASTER
SELECT PARTY_CODE, LONG_NAME, '', '', '9999999999', GETDATE() FROM MSAJAG.DBO.CLIENT_DETAILS
EXEC CLS_GET_LEDGER2_FORMULA_BALANCES 'MAR 31 2014', '', 'VDTBAL', 'NSE', 'CAPITAL'  
*/
CREATE PROCEDURE [dbo].[CLS_GET_LEDGER2_FORMULA_BALANCES]
 @EFFDATE VARCHAR(11),  
 @PROCESS_CODE VARCHAR(10),  
 @REPORT_FORMULA VARCHAR(MAX),
 @EXCHANGE VARCHAR(10) = '',
 @SEGMENT VARCHAR(50) = '',
 @REPORT_COLUMN  VARCHAR(1000) = '',
 @REPORT_GROUPING VARCHAR(1000) = ''

AS

 SELECT @REPORT_FORMULA = FORMULANAME FROM FORMULA_MASTER WHERE PROCESSCODE = @PROCESS_CODE    
    

IF @EXCHANGE = ''
BEGIN
	SELECT @EXCHANGE = EXCHANGE, @SEGMENT = SEGMENT FROM OWNER
END

DECLARE    
 @START_DATE VARCHAR(11)    

IF LEN(@EFFDATE) = 10    
BEGIN    
	SELECT @EFFDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @EFFDATE, 103), 109)    
END    

SELECT @START_DATE = CONVERT(VARCHAR(11), SDTCUR, 109)    
FROM PARAMETER    
WHERE @EFFDATE BETWEEN SDTCUR AND LDTCUR    

 

CREATE TABLE #REPORT_DATA  
(  
 CLTCODE VARCHAR(10),  
 /*PARTY_NAME VARCHAR(100),     
 ENTITY_LEVEL VARCHAR(20),  
 ENTITY_CODE VARCHAR(25),   */ 
 VDTBAL_OPBAL MONEY,  
 EDTBAL_OPBAL MONEY,    
 VDTBAL MONEY,    
 EDTBAL MONEY,    
 VDTBAL_RECEIPT MONEY,     
 T_DAY_BILL MONEY,     
 VDTBAL_BILL_DR MONEY,     
 VDTBAL_BILL_CR MONEY,    
 VDTBAL_NONBILL MONEY,     
 EDTBAL_RECEIPT MONEY,    
 EDTBAL_BILL_DR MONEY,    
 EDTBAL_BILL_CR MONEY,    
 EDTBAL_NONBILL MONEY,    
 FDT_RECEIPT MONEY,    
 FDT_CR MONEY,     
 FDT_DR MONEY,
 MARGIN_BAL MONEY  
)  

DECLARE  
 @@SQL VARCHAR(MAX)  

INSERT INTO #REPORT_DATA    
SELECT     
 CLTCODE,  
 VDTBAL_OPBAL = SUM(VDTBAL_OPBAL),    
 EDTBAL_OPBAL = SUM(EDTBAL_OPBAL),    
 VDTBAL = SUM(VDTBAL),    
 EDTBAL = SUM(EDTBAL),    
 VDTBAL_RECEIPT = SUM(VDTBAL_RECEIPT),     
 T_DAY_BILL = SUM(T_DAY_BILL),     
 VDTBAL_BILL_DR = SUM(VDTBAL_BILL_DR),     
 VDTBAL_BILL_CR = SUM(VDTBAL_BILL_CR),    
 VDTBAL_NONBILL = SUM(VDTBAL_NONBILL),     
 EDTBAL_RECEIPT = SUM(EDTBAL_RECEIPT),    
 EDTBAL_BILL_DR = SUM(EDTBAL_BILL_DR),    
 EDTBAL_BILL_CR = SUM(EDTBAL_BILL_CR),    
 EDTBAL_NONBILL = SUM(EDTBAL_NONBILL),    
 FDT_RECEIPT = SUM(FDT_RECEIPT),    
 FDT_CR = SUM(FDT_CR),     
 FDT_DR = SUM(FDT_DR),
 MARGIN_BAL = 0
FROM    
(SELECT     
 CLTCODE = L.CLTCODE,  
 VDTBAL_OPBAL = CASE WHEN VDT >= @START_DATE AND VDT < @EFFDATE THEN SUM(CASE L2.DRCR WHEN 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END,    
 EDTBAL_OPBAL = CASE WHEN EDT >= @START_DATE AND EDT < @EFFDATE THEN SUM(CASE L2.DRCR WHEN 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE L2.DRCR WHEN 'C' THEN CAMT ELSE -CAMT END) ELSE 0 END,    
 VDTBAL = CASE WHEN VDT >= @START_DATE THEN SUM(CASE L2.DRCR WHEN 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END,    
 EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' THEN SUM(CASE L2.DRCR WHEN 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE L2.DRCR WHEN 'C' THEN CAMT ELSE -CAMT END) ELSE 0 END,    
 VDTBAL_RECEIPT = CASE WHEN VDT >= @START_DATE AND VTYPE = 2 THEN SUM(CAMT) ELSE 0 END,     
 T_DAY_BILL = CASE WHEN VDT LIKE @EFFDATE + '%' AND VTYPE = 15 THEN SUM(CASE WHEN L2.DRCR = 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END,     
 VDTBAL_BILL_DR = CASE WHEN VDT >= @START_DATE AND VTYPE = 15 AND L2.DRCR = 'D' THEN SUM(CAMT) ELSE 0 END,     
 VDTBAL_BILL_CR = CASE WHEN VDT >= @START_DATE AND VTYPE = 15 AND L2.DRCR = 'C' THEN SUM(CAMT) ELSE 0 END ,    
 VDTBAL_NONBILL = CASE WHEN VDT >= @START_DATE AND VTYPE NOT IN (15, 2) THEN SUM(CASE L2.DRCR WHEN 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END,  
 EDTBAL_RECEIPT = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' AND VTYPE = 2 THEN SUM(CAMT) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE AND VTYPE = 2 THEN SUM(-CAMT) ELSE 0 END,    
 EDTBAL_BILL_DR = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' AND VTYPE = 15 AND L2.DRCR = 'D' THEN SUM(CAMT) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE AND VTYPE = 15 AND L2.DRCR = 'D' THEN SUM(-CAMT) ELSE 0 END,    
 EDTBAL_BILL_CR = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' AND VTYPE = 15 AND L2.DRCR = 'C' THEN SUM(CAMT) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE AND VTYPE = 15 AND L2.DRCR = 'C' THEN SUM(-CAMT) ELSE 0 END,    
 EDTBAL_NONBILL = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' AND VTYPE NOT IN (15, 2) THEN SUM(CASE L2.DRCR WHEN 'D' THEN CAMT ELSE -CAMT END) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE L2.DRCR WHEN 'C' THEN CAMT ELSE -CAMT END) ELSE 0 END,    
 FDT_RECEIPT = CASE WHEN EDT > @EFFDATE + ' 23:59' AND VDT <= @EFFDATE + ' 23:59' AND VTYPE = 2 THEN SUM(CAMT) ELSE 0 END,    
 FDT_CR = CASE WHEN EDT > @EFFDATE + ' 23:59' AND VDT <= @EFFDATE + ' 23:59' AND L2.DRCR = 'C' AND VTYPE <> 2 THEN SUM(CAMT) ELSE 0 END,     
 FDT_DR = CASE WHEN EDT > @EFFDATE + ' 23:59' AND VDT <= @EFFDATE + ' 23:59' AND L2.DRCR = 'D' AND VTYPE <> 2 THEN SUM(CAMT) ELSE 0 END
FROM     
 LEDGER L,
 LEDGER2 L2,  
 #FORMULA_CLIENT_MASTER A    
WHERE    
 A.CLTCODE = L2.CLTCODE --AND SESSION_ID = @SESSIONID
 AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO  
 AND (VDT >= @START_DATE OR EDT >= @START_DATE)    
 AND VDT <= @EFFDATE + ' 23:59'
 GROUP BY     
 L.CLTCODE, VDT, EDT, VTYPE, L2.DRCR    
) A    
GROUP BY CLTCODE

--HAVING SUM(VDTBAL) <> 0 AND SUM(EDTBAL) <> 0    

UPDATE RD SET MARGIN_BAL = ML.AMOUNT
FROM #REPORT_DATA RD, (
	SELECT PARTY_CODE, AMOUNT = SUM(CASE DRCR WHEN 'C' THEN AMOUNT ELSE -AMOUNT END)
	FROM MARGINLEDGER ML
	WHERE VDT >= @START_DATE AND VDT <= @EFFDATE + ' 23:59'
	GROUP BY PARTY_CODE
)ML
WHERE RD.CLTCODE = PARTY_CODE

/*IF @REPORT_COLUMN = ''
BEGIN
	SET @@SQL = " SELECT "  
	SET @@SQL = @@SQL + " CLTCODE, "  
	SET @@SQL = @@SQL + " PARTY_NAME, "  
	SET @@SQL = @@SQL + " ENTITY_LEVEL,"  
	SET @@SQL = @@SQL + " ENTITY_CODE, "  
	SET @@SQL = @@SQL + @REPORT_FORMULA + ", EXCHANGE = '" + @EXCHANGE + "', SEGMENT = '" + @SEGMENT + "', SESSIONID = '" + @SESSIONID + "', POPULATE_DATE = GETDATE() "  
	SET @@SQL = @@SQL + " FROM "  
	SET @@SQL = @@SQL + " #REPORT_DATA"  
END
ELSE
BEGIN*/
	SET @@SQL = " SELECT "  
	IF @REPORT_COLUMN <> ''
		SET @@SQL = @@SQL + @REPORT_COLUMN + ", "
	SET @@SQL = @@SQL + @REPORT_FORMULA  
	SET @@SQL = @@SQL + " FROM "  
	SET @@SQL = @@SQL + " #REPORT_DATA"  
	IF @REPORT_GROUPING <> ''
		SET @@SQL = @@SQL + " GROUP BY " + @REPORT_GROUPING
--END

  
--PRINT @@SQL
EXEC (@@SQL)

GO

-- --------------------------------------------------
-- PROCEDURE dbo.CLS_GLLEDGER
-- --------------------------------------------------
CREATE PROCEDURE [dbo].[CLS_GLLEDGER]
	@FR_DATE VARCHAR(11), /* AS ON DATE ENTERED BY USER */
	@VDT VARCHAR(11), /* AS ON DATE ENTERED BY USER */
	@FROM_GL_CODE VARCHAR(10),
	@TO_GL_CODE VARCHAR(10),
	@VIEWOPTION VARCHAR(10),
	@STATUSID VARCHAR(20), /* AS BROKER/BRANCH/CLIENT ETC. */
	@STATUSNAME VARCHAR(20), /* IN CASE OF BRANCH LOGIN BRANCHCODE */
	@SORTBYDATE VARCHAR(3), /* WHETHER REPORT IS BASED ON VDT OR EDT */
	@SHOWZEROBAL VARCHAR(1) = 'N', /* SHOW ZERO BAL   */
	@GRPCODE VARCHAR(20),
	@SHAREDB VARCHAR(20),
	@EXCHANGE VARCHAR(10),
	@SEGMENT VARCHAR(9),
	@TABLE_NAME VARCHAR(100),
	@BRANCHCODE VARCHAR(10) = '',
	@WITHOPENING BIT = 0,
	@SORT_BY VARCHAR(10) = 'ACCODE',
	@SHOW_MARGIN CHAR(1) = 'N'
AS

CREATE TABLE #FORMULA_CLIENT_MASTER
(
	CLTCODE VARCHAR(10) NOT NULL
)

ALTER TABLE #FORMULA_CLIENT_MASTER
 ADD PRIMARY KEY (CLTCODE)

DECLARE @@COSTCODE AS INT,
	@@SQL AS VARCHAR(1000)


CREATE TABLE #COSTMAST (COSTCODE INT, COSTNAME VARCHAR(100))

IF @STATUSID = 'REGION'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE ,COSTNAME FROM COSTMAST C, " + @SHAREDB + ".DBO.REGION R WHERE REGIONCODE = RTRIM('" + @STATUSNAME + "') AND COSTNAME = BRANCH_CODE "
	
	EXEC (@@SQL)
END

IF @STATUSID = 'AREA'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE ,COSTNAME FROM COSTMAST C, " + @SHAREDB + ".DBO.AREA A WHERE AREACODE = RTRIM('" + @STATUSNAME + "') AND COSTNAME = BRANCH_CODE "
	
	EXEC (@@SQL)
END

IF @STATUSID = 'BRANCH'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE ,COSTNAME FROM COSTMAST WHERE COSTNAME = RTRIM('" + @STATUSNAME + "') "
	
	EXEC (@@SQL)
END

CREATE TABLE #TB
(
	CLTCODE VARCHAR(10),
	AMOUNT MONEY
)

IF @WITHOPENING = 1
BEGIN
	ALTER TABLE #TB
	ADD
		OPENING_AMOUNT MONEY,
		PERIOD_CREDIT MONEY,
		PERIOD_DEBIT MONEY
END

DECLARE
	@AMOUNT_PARAMETER VARCHAR(200),
	@NET_AMOUNT_PARAMETER VARCHAR(200),
	@DISPLAY_AMOUNT VARCHAR(300)
	
IF UPPER(@SORTBYDATE) = 'VDT'
BEGIN
	SET @NET_AMOUNT_PARAMETER = 'VDTBAL = SUM(VDTBAL)'
	IF @WITHOPENING = 0
	BEGIN
		SET @AMOUNT_PARAMETER = 'VDTBAL'
		SET @DISPLAY_AMOUNT = '-AMOUNT'
	END
	ELSE
	BEGIN
		SET @AMOUNT_PARAMETER = 'VDTBAL,VDTBAL_OPBAL, VDTBAL_DATES_CREDIT, VDTBAL_DATES_DEBIT'
		SET @DISPLAY_AMOUNT = ' -AMOUNT,-OPENING_AMOUNT, PERIOD_CREDIT, PERIOD_DEBIT'
	END
END
ELSE
BEGIN
	SET @NET_AMOUNT_PARAMETER = 'EDTBAL = SUM(EDTBAL)'
	IF @WITHOPENING = 0
	BEGIN
		SET @AMOUNT_PARAMETER = 'EDTBAL'
		SET @DISPLAY_AMOUNT = '-AMOUNT'
	END
	ELSE
	BEGIN
		SET @AMOUNT_PARAMETER = 'EDTBAL, EDTBAL_OPBAL, EDTBAL_DATES_CREDIT, EDTBAL_DATES_DEBIT'
		SET @DISPLAY_AMOUNT = '-AMOUNT,-OPENING_AMOUNT, PERIOD_CREDIT, PERIOD_DEBIT'
	END
END


SET @@SQL = "INSERT INTO #FORMULA_CLIENT_MASTER "
SET @@SQL = @@SQL + "SELECT CLTCODE "
SET @@SQL = @@SQL + "FROM ACMAST A "
SET @@SQL = @@SQL + "WHERE CLTCODE >= '" + @FROM_GL_CODE + "' AND CLTCODE <= '" + @TO_GL_CODE + "'"
IF UPPER(@VIEWOPTION) = 'GL'
	SET @@SQL = @@SQL + " AND ACCAT = 3 "
ELSE IF UPPER(@VIEWOPTION) = 'BANK'
	SET @@SQL = @@SQL + " AND ACCAT = 2 "	
ELSE IF UPPER(@VIEWOPTION) = 'CASH'
	SET @@SQL = @@SQL + " AND ACCAT = 1 "	
IF UPPER(@STATUSID) <> 'BROKER'
	SET @@SQL = @@SQL + "AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE COSTNAME = BRANCHCODE) "

EXEC(@@SQL)	

IF UPPER(@STATUSID) = 'BROKER'
BEGIN

	INSERT INTO #TB
	EXEC CLS_GET_ACC_LEDGER_FORMULA_BALANCES @FR_DATE, @VDT, 0, @AMOUNT_PARAMETER, @EXCHANGE, @SEGMENT , 'CLTCODE = ''''', ''
END
ELSE
BEGIN
	INSERT INTO #TB
	EXEC CLS_GET_LEDGER2_FORMULA_BALANCES @VDT, 0, @AMOUNT_PARAMETER, @EXCHANGE, @SEGMENT , 'CLTCODE = ''''', ''
END

DROP TABLE #FORMULA_CLIENT_MASTER

SET @@SQL = "INSERT INTO ACCOUNT.." + @TABLE_NAME
SET @@SQL = @@SQL + " SELECT TB.CLTCODE, ACNAME, BRANCHCODE,	'" + @EXCHANGE + "','" +  @SEGMENT + "', " + @DISPLAY_AMOUNT + ", ACCAT, A.GRPCODE, GRPNAME "
SET @@SQL = @@SQL + "FROM "
SET @@SQL = @@SQL + "	#TB TB , ACMAST A, GRPMAST G "
SET @@SQL = @@SQL + "WHERE A.GRPCODE = G.GRPCODE AND TB.CLTCODE = A.CLTCODE "
/*SET @@SQL = @@SQL + "UNION "
SET @@SQL = @@SQL + "SELECT CLTCODE, ACNAME = 'PARTY TOTAL', BRANCHCODE = '', -AMOUNT, 0,	'" + @EXCHANGE + "','" +  @SEGMENT + "', '', '' "
SET @@SQL = @@SQL + "FROM #TB WHERE CLTCODE = '' AND ISNULL(AMOUNT, 0) <> 0 "*/
PRINT @@SQL
EXEC(@@SQL)

GO

-- --------------------------------------------------
-- PROCEDURE dbo.CLS_TRIALBALANCE
-- --------------------------------------------------
CREATE PROCEDURE [dbo].[CLS_TRIALBALANCE]
	@FR_DATE VARCHAR(11), /* AS ON DATE ENTERED BY USER */
	@VDT VARCHAR(11), /* AS ON DATE ENTERED BY USER */
	@VIEWOPTION VARCHAR(10), /* OPTIONS FOR ACCOUNTS SELECTION - ALL, GL, PARTY */
	@STATUSID VARCHAR(20), /* AS BROKER/BRANCH/CLIENT ETC. */
	@STATUSNAME VARCHAR(20), /* IN CASE OF BRANCH LOGIN BRANCHCODE */
	@SORTBYDATE VARCHAR(3), /* WHETHER REPORT IS BASED ON VDT OR EDT */
	@SHOWZEROBAL VARCHAR(1) = 'N', /* SHOW ZERO BAL   */
	@GRPCODE VARCHAR(20),
	@SHAREDB VARCHAR(20),
	@EXCHANGE VARCHAR(10),
	@SEGMENT VARCHAR(9),
	@TABLE_NAME VARCHAR(100),
	@BRANCHCODE VARCHAR(10) = '',
	@WITHOPENING BIT = 0,
	@SORT_BY VARCHAR(10) = 'ACCODE',
	@SHOW_MARGIN CHAR(1) = 'N'
AS

CREATE TABLE #FORMULA_CLIENT_MASTER
(
	CLTCODE VARCHAR(10) NOT NULL
)

ALTER TABLE #FORMULA_CLIENT_MASTER
 ADD PRIMARY KEY (CLTCODE)

DECLARE @@COSTCODE AS INT,
	@@SQL AS VARCHAR(1000)

CREATE TABLE #COSTMAST (COSTCODE INT, COSTNAME VARCHAR(100))

IF @STATUSID = 'REGION'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE, COSTNAME FROM COSTMAST C, " + @SHAREDB + ".DBO.REGION R WHERE REGIONCODE = RTRIM('" + @STATUSNAME + "') AND COSTNAME = BRANCH_CODE "
	
	EXEC (@@SQL)
END

IF @STATUSID = 'AREA'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE, COSTNAME FROM COSTMAST C, " + @SHAREDB + ".DBO.AREA A WHERE AREACODE = RTRIM('" + @STATUSNAME + "') AND COSTNAME = BRANCH_CODE "
	
	EXEC (@@SQL)
END

IF @STATUSID = 'BROKER' AND @BRANCHCODE <> ''
BEGIN
	SET @STATUSID = 'BRANCH'
	SET @STATUSNAME = @BRANCHCODE
END

IF @STATUSID = 'BRANCH'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE, COSTNAME FROM COSTMAST WHERE COSTNAME = RTRIM('" + @STATUSNAME + "') "
	
	EXEC (@@SQL)
END


CREATE TABLE #TB
(
	CLTCODE VARCHAR(10),
	AMOUNT MONEY
)

IF @WITHOPENING = 1
BEGIN
	ALTER TABLE #TB
	ADD
		OPENING_AMOUNT MONEY,
		PERIOD_CREDIT MONEY,
		PERIOD_DEBIT MONEY
END

DECLARE
	@AMOUNT_PARAMETER VARCHAR(200),
	@NET_AMOUNT_PARAMETER VARCHAR(200),
	@DISPLAY_AMOUNT VARCHAR(300)
	
IF UPPER(@SORTBYDATE) = 'VDT'
BEGIN
	SET @NET_AMOUNT_PARAMETER = 'VDTBAL = SUM(VDTBAL)'
	IF @WITHOPENING = 0
	BEGIN
		SET @AMOUNT_PARAMETER = 'VDTBAL'
		SET @DISPLAY_AMOUNT = '-AMOUNT'
	END
	ELSE
	BEGIN
		SET @AMOUNT_PARAMETER = 'VDTBAL_OPBAL, VDTBAL_DATES_CREDIT, VDTBAL_DATES_DEBIT,VDTBAL'
		SET @DISPLAY_AMOUNT = '-OPENING_AMOUNT, PERIOD_CREDIT, PERIOD_DEBIT, -AMOUNT'
	END
END
ELSE
BEGIN
	SET @NET_AMOUNT_PARAMETER = 'EDTBAL = SUM(EDTBAL)'
	IF @WITHOPENING = 0
	BEGIN
		SET @AMOUNT_PARAMETER = 'EDTBAL'
		SET @DISPLAY_AMOUNT = '-AMOUNT'
	END
	ELSE
	BEGIN
		SET @AMOUNT_PARAMETER = 'EDTBAL_OPBAL, EDTBAL_DATES_CREDIT, EDTBAL_DATES_DEBIT, EDTBAL'
		SET @DISPLAY_AMOUNT = '-OPENING_AMOUNT, PERIOD_CREDIT, PERIOD_DEBIT, -AMOUNT'
	END
END


IF UPPER(@VIEWOPTION) = 'GL'
BEGIN
	IF UPPER(@STATUSID) = 'BROKER'
	BEGIN
		INSERT INTO #FORMULA_CLIENT_MASTER
		SELECT CLTCODE
		FROM ACMAST A
		WHERE ACCAT = 4
	
		INSERT INTO #TB
		EXEC CLS_GET_ACC_LEDGER_FORMULA_BALANCES @FR_DATE, @VDT, 0, @NET_AMOUNT_PARAMETER, @EXCHANGE, @SEGMENT , 'CLTCODE = ''''', ''
		
		TRUNCATE TABLE #FORMULA_CLIENT_MASTER
	END
	ELSE
	BEGIN
		INSERT INTO #FORMULA_CLIENT_MASTER
		SELECT CLTCODE
		FROM ACMAST A
		WHERE ACCAT = 4
		AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE COSTNAME = BRANCHCODE)
		
		INSERT INTO #TB
		EXEC CLS_GET_ACC_LEDGER_FORMULA_BALANCES @FR_DATE, @VDT, 0, @NET_AMOUNT_PARAMETER, @EXCHANGE, @SEGMENT , 'CLTCODE = ''''', ''
		
		TRUNCATE TABLE #FORMULA_CLIENT_MASTER
	END
END	


SET @@SQL = "INSERT INTO #FORMULA_CLIENT_MASTER "
SET @@SQL = @@SQL + "SELECT CLTCODE "
SET @@SQL = @@SQL + "FROM ACMAST A "
IF UPPER(@VIEWOPTION) = 'GL'
	SET @@SQL = @@SQL + "WHERE ACCAT <> 4 "
ELSE IF UPPER(@VIEWOPTION) = 'PARTY'
	SET @@SQL = @@SQL + "WHERE ACCAT = 4 "	
ELSE IF UPPER(@VIEWOPTION) = 'ALL'
	SET @@SQL = @@SQL + "WHERE ACCAT = ACCAT "	
IF UPPER(@STATUSID) <> 'BROKER'
	SET @@SQL = @@SQL + "AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE COSTNAME = BRANCHCODE) "
	
EXEC(@@SQL)	




IF UPPER(@STATUSID) = 'BROKER'
BEGIN
	INSERT INTO #TB
	EXEC CLS_GET_ACC_LEDGER_FORMULA_BALANCES @FR_DATE, @VDT, 0, @AMOUNT_PARAMETER, @EXCHANGE, @SEGMENT , 'M.CLTCODE', ''
END
ELSE
BEGIN
	INSERT INTO #TB
	EXEC CLS_GET_LEDGER2_FORMULA_BALANCES @VDT, 0, @AMOUNT_PARAMETER, @EXCHANGE, @SEGMENT , 'CLTCODE', ''
END

DROP TABLE #FORMULA_CLIENT_MASTER

SET @@SQL = "INSERT INTO ACCOUNT.." + @TABLE_NAME
SET @@SQL = @@SQL + " SELECT TB.CLTCODE, ACNAME, BRANCHCODE,	'" + @EXCHANGE + "','" +  @SEGMENT + "', " + @DISPLAY_AMOUNT + ", ACCAT, A.GRPCODE, GRPNAME "
SET @@SQL = @@SQL + "FROM "
SET @@SQL = @@SQL + "	#TB TB , ACMAST A, GRPMAST G "
SET @@SQL = @@SQL + "WHERE A.GRPCODE = G.GRPCODE AND TB.CLTCODE = A.CLTCODE "
/*SET @@SQL = @@SQL + "UNION "
SET @@SQL = @@SQL + "SELECT CLTCODE, ACNAME = 'PARTY TOTAL', BRANCHCODE = '', -AMOUNT, 0,	'" + @EXCHANGE + "','" +  @SEGMENT + "', '', '' "
SET @@SQL = @@SQL + "FROM #TB WHERE CLTCODE = '' AND ISNULL(AMOUNT, 0) <> 0 "*/
PRINT @@SQL
EXEC(@@SQL)

GO

-- --------------------------------------------------
-- PROCEDURE dbo.GET_LEDGER_AUDIT_DATA
-- --------------------------------------------------





--EXEC V2_GET_LEDGER_FORMULA_BALANCES 'MAR 31 2013', '9999999999', 0, ''  
--EXEC [MTSRVR06\DEV].ACCOUNT..V2_GET_LEDGER_FORMULA_BALANCES 'MAR 31 2013','9999999999','', 'VDTBAL_OPBAL, T_DAY_BILL, FDT_RECEIPT'  
CREATE PROCEDURE [dbo].[GET_LEDGER_AUDIT_DATA]    
 @EFFDATE VARCHAR(11),  
 @SESSIONID VARCHAR(500),  
 @PROCESS_CODE VARCHAR(10),  
 @REPORT_FORMULA VARCHAR(MAX),
 @EXCHANGE VARCHAR(10),
 @SEGMENT VARCHAR(50)
AS    
  
DECLARE    
 @START_DATE VARCHAR(11)    
    
IF LEN(@EFFDATE) = 10    
BEGIN    
 SELECT @EFFDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @EFFDATE, 103), 109)    
END    
    
SELECT @START_DATE = CONVERT(VARCHAR(11), SDTCUR, 109)    
FROM PARAMETER    
WHERE @EFFDATE BETWEEN SDTCUR AND LDTCUR    
  
  
CREATE TABLE #REPORT_DATA  
(  
 CLTCODE VARCHAR(10),  
 PARTY_NAME VARCHAR(100),     
 ENTITY_LEVEL VARCHAR(20),  
 ENTITY_CODE VARCHAR(25),    
 VDTBAL MONEY,    
 EDTBAL MONEY,    
 FDT_RECEIPT MONEY,    
 FDT_PAYMENTS MONEY,
 MARGIN_BAL MONEY  
)  
  
DECLARE  
 @@SQL VARCHAR(MAX)  
  
INSERT INTO #REPORT_DATA    
SELECT     
 CLTCODE,  
 PARTY_NAME,     
 ENTITY_LEVEL,  
 ENTITY_CODE,    
 VDTBAL = SUM(VDTBAL),    
 EDTBAL = SUM(EDTBAL),    
 FDT_RECEIPT = SUM(FDT_RECEIPT),    
 FDT_PAYMENTS = SUM(FDT_PAYMENTS),
 MARGIN_BAL = 0
FROM    
(SELECT     
 CLTCODE = L.CLTCODE,  
 PARTY_NAME,  
 ENTITY_LEVEL,  
 ENTITY_CODE,    
 VDTBAL = CASE WHEN VDT >= @START_DATE THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END,    
 EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END     
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END,    
 FDT_RECEIPT = CASE WHEN (/*RELDT = '' OR */RELDT > @EFFDATE + ' 23:59') AND L.VTYP = 2 THEN SUM(VAMT) ELSE 0 END,    
 FDT_PAYMENTS = CASE WHEN (/*RELDT = '' OR */RELDT > @EFFDATE + ' 23:59') AND L.VTYP = 3 THEN SUM(VAMT) ELSE 0 END
FROM     
 (SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION FROM LEDGER WHERE (VDT >= @START_DATE OR EDT >= @START_DATE OR VDT >= DATEADD(M, -6, @EFFDATE))    
 AND VDT <= @EFFDATE + ' 23:59')    L  
 LEFT OUTER JOIN (SELECT RELDT, VTYP,VNO,LNO,BOOKTYPE FROM LEDGER1 WHERE (RELDT > @EFFDATE + ' 23:59' OR RELDT = '')) L1
 ON L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.VNO = L1.VNO AND L.LNO = L1.LNO,
 FORMULA_CLIENT_MASTER A    
WHERE    
 A.CLTCODE = L.CLTCODE AND SESSION_ID = @SESSIONID  
 
 GROUP BY     
 L.CLTCODE, PARTY_NAME, ENTITY_LEVEL, ENTITY_CODE,  L.VDT, EDT, L.VTYP, DRCR, L1.RELDT    
) A    
GROUP BY CLTCODE, PARTY_NAME, ENTITY_LEVEL, ENTITY_CODE      
--HAVING SUM(VDTBAL) <> 0 AND SUM(EDTBAL) <> 0    

/*
UPDATE RD SET MARGIN_BAL = ML.AMOUNT
FROM #REPORT_DATA RD, (
	SELECT PARTY_CODE, AMOUNT = SUM(CASE DRCR WHEN 'C' THEN AMOUNT ELSE -AMOUNT END)
	FROM MARGINLEDGER ML
	WHERE VDT >= @START_DATE AND VDT <= @EFFDATE + ' 23:59'
	GROUP BY PARTY_CODE
)ML
WHERE RD.CLTCODE = PARTY_CODE
*/

SET @@SQL = " SELECT "  
SET @@SQL = @@SQL + " CLTCODE, "  
SET @@SQL = @@SQL + " PARTY_NAME, "  
SET @@SQL = @@SQL + " ENTITY_LEVEL,"  
SET @@SQL = @@SQL + " ENTITY_CODE, "  
SET @@SQL = @@SQL + @REPORT_FORMULA + ", EXCHANGE = '" + @EXCHANGE + "', SEGMENT = '" + @SEGMENT + "', SESSIONID = '" + @SESSIONID + "', POPULATE_DATE = GETDATE() "  
SET @@SQL = @@SQL + " FROM "  
SET @@SQL = @@SQL + " #REPORT_DATA"  
  
EXEC (@@SQL)

GO

-- --------------------------------------------------
-- PROCEDURE dbo.PR_GET_LEDBAL_COMBINE
-- --------------------------------------------------
CREATE PROCEDURE [dbo].[PR_GET_LEDBAL_COMBINE]     
(    
 @MARGINDATE VARCHAR(11) 
) 

AS

-- EXEC PR_GET_LEDBAL_COMBINE 'DEC 12 2019'
DECLARE 
		@SDTCUR			DATETIME,
		@LDTCUR			DATETIME 

DECLARE @T5DAY VARCHAR(11)

SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR FROM ACCOUNT.DBO.PARAMETER    
WHERE CONVERT(DATETIME,@MARGINDATE) BETWEEN SDTCUR AND LDTCUR
 
SELECT @T5DAY = LEFT(ISNULL(MAX(SEC_PAYIN),@MARGINDATE),11) FROM    
(SELECT DISTINCT TOP 5 SEC_PAYIN = CONVERT(DATETIME,LEFT(SEC_PAYIN,11)) FROM MSAJAG.DBO.SETT_MST (NOLOCK)     
WHERE SEC_PAYIN >= @MARGINDATE     
AND SETT_TYPE = 'N') S    

SELECT CLTCODE, VAMT=SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END) 
INTO #CASH_LED_BAL FROM LEDGER L (NOLOCK)
WHERE VDT <= @MARGINDATE + ' 23:59:59'
AND VDT >= @SDTCUR AND VDT<= @LDTCUR
AND CONVERT(DATETIME,@MARGINDATE) BETWEEN @SDTCUR AND @LDTCUR 
GROUP BY CLTCODE

INSERT INTO #CASH_LED_BAL 
SELECT CLTCODE, VAMT=SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END) 
FROM ACCOUNT.DBO.LEDGER L (NOLOCK)
WHERE VDT <= @MARGINDATE + ' 23:59:59' and EDT > @MARGINDATE + ' 23:59:59'
AND VDT >=CONVERT(DATETIME,@MARGINDATE,120)-7
AND VTYP IN (15,35) 
GROUP BY CLTCODE

/* NEW LOGIC ADDED TO REVERSE THE T DAY PAYMENT AND DEBIT JV */
INSERT INTO #CASH_LED_BAL 
SELECT CLTCODE, VAMT=SUM(VAMT) 
FROM ACCOUNT.DBO.LEDGER L (NOLOCK)
WHERE VDT BETWEEN @MARGINDATE AND @MARGINDATE + ' 23:59:59'
AND VDT >=CONVERT(DATETIME,@MARGINDATE,120)-7
AND VTYP IN (3, 8) AND DRCR = 'D'
GROUP BY CLTCODE
/* NEW LOGIC ADDED TO REVERSE THE T DAY PAYMENT AND DEBIT JV */

INSERT INTO #CASH_LED_BAL
SELECT       
CLTCODE, /*CHEQUE CANCELED TILL T+5 OF VDT TILL T+1*/      
SUM( CASE WHEN A.DRCR ='C' THEN VAMT ELSE - VAMT END) VAMT    
FROM LEDGER A (NOLOCK), LEDGER1 B (NOLOCK)       
WHERE       
A.VTYP = '17'      
AND A.VTYP = B.VTYP AND A.VNO = B.VNO       
AND A.BOOKTYPE = B.BOOKTYPE AND A.LNO = B.LNO                    
AND A.VDT BETWEEN DATEADD(D, 1, @MARGINDATE) AND @T5DAY + ' 23:59:58'      
AND EXISTS (SELECT L1.CLTCODE,L1.VAMT,L2.DDNO       
    FROM LEDGER L1 (NOLOCK), LEDGER1 L2 (NOLOCK)        
    WHERE L1.VTYP = '2' /*RECEIPTS VDT TILL T+1*/      
    AND L1.VTYP = L2.VTYP AND L1.VNO = L2.VNO       
    AND L1.BOOKTYPE = L2.BOOKTYPE      
    AND L1.LNO = L2.LNO       
    AND L1.VDT >= @SDTCUR AND L1.VDT <= @MARGINDATE + ' 23:59:58'      
    AND A.CLTCODE = L1.CLTCODE      
    AND A.VAMT = L1.VAMT      
    AND B.DDNO = L2.DDNO      
    AND L2.CLEAR_MODE = 'R')      
GROUP BY CLTCODE      
           		    
DELETE FOMARGINNEW_LEDGERBAL WHERE MARGINDATE < DATEADD(M,-1,@MARGINDATE)    
DELETE FOMARGINNEW_LEDGERBAL WHERE MARGINDATE = @MARGINDATE  

INSERT INTO FOMARGINNEW_LEDGERBAL    
 SELECT     
  @MARGINDATE,    
  CLTCODE,    
  SUM(VAMT) VAMT,    
  GETDATE()    
  FROM #CASH_LED_BAL
  GROUP BY CLTCODE

DROP TABLE #CASH_LED_BAL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.SEBI_BANK_BOOK_WEEKLY_BALANCES
-- --------------------------------------------------


CREATE PROCEDURE [dbo].[SEBI_BANK_BOOK_WEEKLY_BALANCES]
	@DATE_FROM VARCHAR(11),
	@REPORT_DATE VARCHAR(11),
	@REPORT_TYPE VARCHAR(3) = 'VDT'
AS

--SEBI_BANK_BOOK_WEEKLY_BALANCES_WRAPPER 'MAY 29 2020'


CREATE TABLE #BANK_BOOK_BAL
(
	BANK_CODE VARCHAR(30),
	BANK_IFSC VARCHAR(30),
	BANK_TYPE VARCHAR(10),
	REPORT_DATE DATETIME,
	AMOUNT MONEY,
	BANK_BALANCE MONEY,
	SNO INT IDENTITY(1, 1)
)

DECLARE
	@SDTCUR VARCHAR(11)

SELECT @SDTCUR = CONVERT(VARCHAR(11), SDTCUR, 109) FROM PARAMETER WHERE @DATE_FROM BETWEEN SDTCUR AND LDTCUR
	
	
--SELECT * FROM #BANK_BOOK_BALANCES
IF @REPORT_TYPE = 'VDT'
BEGIN
	INSERT INTO #BANK_BOOK_BAL
	SELECT BANK_CODE = B.ACCOUNTNO, BANK_IFSC = BANK_IFSC, BANK_TYPE = PURPOSE, REPORT_DATE = @DATE_FROM, AMOUNT = SUM(cASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END),BANK_BALANCE =  0
	FROM LEDGER L, ACMAST A, MSAJAG..BANK_PURPOSE_MASTER B
	WHERE L.CLTCODE = A.CLTCODE AND ACCAT = 2
	AND A.Cltcode = BANKCODE AND EXCHANGE + SEGMENT = (SELECT EXCHANGE + SEGMENT FROM OWNER)
	AND VDT BETWEEN @SDTCUR AND @DATE_FROM + ' 23:59'
	GROUP BY B.ACCOUNTNO, BANK_IFSC, PURPOSE

	INSERT INTO #BANK_BOOK_BAL
	SELECT BANK_CODE = B.ACCOUNTNO, BANK_IFSC = BANK_IFSC, BANK_TYPE = PURPOSE, REPORT_DATE = CONVERT(DATETIME, CONVERT(VARCHAR(11), VDT, 109)), AMOUNT = SUM(cASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END),BANK_BALANCE =  0
	FROM LEDGER L, ACMAST A, MSAJAG..BANK_PURPOSE_MASTER B
	WHERE L.CLTCODE = A.CLTCODE AND ACCAT = 2
	AND A.Cltcode = BANKCODE AND EXCHANGE + SEGMENT = (SELECT EXCHANGE + SEGMENT FROM OWNER)
	AND VDT BETWEEN DATEADD(D, 1, @DATE_FROM) AND @REPORT_DATE + ' 23:59'
	GROUP BY B.ACCOUNTNO, BANK_IFSC, PURPOSE, CONVERT(DATETIME, CONVERT(VARCHAR(11), VDT, 109))
	ORDER BY B.ACCOUNTNO, CONVERT(DATETIME, CONVERT(VARCHAR(11), VDT, 109))
END
ELSE
BEGIN
	INSERT INTO #BANK_BOOK_BAL
	SELECT BANK_CODE, BANK_IFSC, BANK_TYPE, REPORT_DATE, AMOUNT = SUM(AMOUNT),BANK_BALANCE =  0
	FROM(
	SELECT BANK_CODE = B.ACCOUNTNO, BANK_IFSC = BANK_IFSC, BANK_TYPE = PURPOSE, REPORT_DATE = @DATE_FROM, AMOUNT = SUM(cASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, ACMAST A, MSAJAG..BANK_PURPOSE_MASTER B
	WHERE L.CLTCODE = A.CLTCODE AND ACCAT = 2
	AND A.Cltcode = BANKCODE AND EXCHANGE + SEGMENT = (SELECT EXCHANGE + SEGMENT FROM OWNER)
	AND EDT BETWEEN @SDTCUR AND @DATE_FROM + ' 23:59'
	GROUP BY B.ACCOUNTNO, BANK_IFSC, PURPOSE
	UNION ALL
	SELECT BANK_CODE = B.ACCOUNTNO, BANK_IFSC = BANK_IFSC, BANK_TYPE = PURPOSE, REPORT_DATE = @DATE_FROM, AMOUNT = SUM(cASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, ACMAST A, MSAJAG..BANK_PURPOSE_MASTER B
	WHERE L.CLTCODE = A.CLTCODE AND ACCAT = 2
	AND A.Cltcode = BANKCODE AND EXCHANGE + SEGMENT = (SELECT EXCHANGE + SEGMENT FROM OWNER)
	AND EDT >= @SDTCUR AND VDT < @SDTCUR
	GROUP BY B.ACCOUNTNO, BANK_IFSC, PURPOSE ) A
	GROUP BY BANK_CODE, BANK_IFSC, BANK_TYPE, REPORT_DATE

	INSERT INTO #BANK_BOOK_BAL
	SELECT BANK_CODE = B.ACCOUNTNO, BANK_IFSC = BANK_IFSC, BANK_TYPE = PURPOSE, REPORT_DATE = CONVERT(DATETIME, CONVERT(VARCHAR(11), EDT, 109)), AMOUNT = SUM(cASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END),BANK_BALANCE =  0
	FROM LEDGER L, ACMAST A, MSAJAG..BANK_PURPOSE_MASTER B
	WHERE L.CLTCODE = A.CLTCODE AND ACCAT = 2
	AND A.Cltcode = BANKCODE AND EXCHANGE + SEGMENT = (SELECT EXCHANGE + SEGMENT FROM OWNER)
	AND EDT BETWEEN DATEADD(D, 1, @DATE_FROM) AND @REPORT_DATE + ' 23:59'
	GROUP BY B.ACCOUNTNO, BANK_IFSC, PURPOSE, CONVERT(DATETIME, CONVERT(VARCHAR(11), EDT, 109))
	ORDER BY B.ACCOUNTNO, CONVERT(DATETIME, CONVERT(VARCHAR(11), EDT, 109))
END

INSERT INTO #BANK_BOOK_BAL
SELECT BANK_CODE, BANK_IFSC, BANK_TYPE, CAL_DATES, AMOUNT = 0, BANK_BALANCE = 0 FROM
(
SELECT * FROM
(SELECT DISTINCT BANK_CODE, BANK_IFSC, BANK_TYPE FROM #BANK_BOOK_BAL) B , CAL_DATES C
) A
WHERE NOT EXISTS(SELECT BANK_CODE FROM #BANK_BOOK_BAL B1 WHERE A.BANK_CODE = B1.BANK_CODE AND A.CAL_DATES = B1.REPORT_DATE)


--UPDATE B SET B.BANK_BALANCE = B1.BANK_BALANCE FROM #BANK_BOOK_BAL B,
--(SELECT BANK_CODE,BANK_IFSC, BANK_TYPE, REPORT_DATE, AMOUNT,
--SUM (AMOUNT) OVER (ORDER BY BANK_CODE, REPORT_DATE) AS BANK_BALANCE
--FROM #BANK_BOOK_BAL) B1
--WHERE B.BANK_CODE = B1.BANK_CODE AND B.REPORT_DATE = B1.

UPDATE B SET BANK_BALANCE = (SELECT SUM(AMOUNT) FROM #BANK_BOOK_BAL B1 WHERE B.BANK_CODE = B1.BANK_CODE AND B1.SNO <= B.SNO) FROM #BANK_BOOK_BAL B

SELECT * FROM #BANK_BOOK_BAL

GO

-- --------------------------------------------------
-- PROCEDURE dbo.SP
-- --------------------------------------------------
  
CREATE PROC SP @spName VARCHAR(25)AS               
Select * from sysobjects where name Like '%' + @spName + '%' and xtype='P' Order By Name

GO

-- --------------------------------------------------
-- PROCEDURE dbo.Tbl
-- --------------------------------------------------
  

  
CREATE PROC Tbl @TblName VARCHAR(25)AS             
Select * from sysobjects where name Like '%' + @TblName + '%' and xtype='U' Order By Name

GO

-- --------------------------------------------------
-- PROCEDURE dbo.Vw
-- --------------------------------------------------
    
CREATE PROC Vw @VwName VARCHAR(25)AS                   
Select * from sysobjects where name Like '%' + @VwName + '%' and xtype='V' Order By Name

GO

-- --------------------------------------------------
-- TABLE dbo.AUDIT_DATA
-- --------------------------------------------------
CREATE TABLE [dbo].[AUDIT_DATA]
(
    [CLTCODE] VARCHAR(10) NULL,
    [PARTY_NAME] VARCHAR(100) NULL,
    [ENTITY_LEVEL] VARCHAR(20) NULL,
    [ENTITY_CODE] VARCHAR(25) NULL,
    [VDTBAL] MONEY NULL,
    [EDTBAL] MONEY NULL,
    [FDT_RECEIPT] MONEY NULL,
    [FDT_PAYMENTS] MONEY NULL,
    [EXCHANGE] VARCHAR(20) NULL,
    [SEGMENT] VARCHAR(20) NULL,
    [SESSIONID] VARCHAR(50) NULL,
    [POPULATE_DATE] DATETIME NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.BillPosted
-- --------------------------------------------------
CREATE TABLE [dbo].[BillPosted]
(
    [vno] VARCHAR(12) NULL,
    [vtyp] SMALLINT NOT NULL,
    [BookType] CHAR(2) NULL,
    [vdt] DATETIME NULL,
    [BillDate] DATETIME NULL,
    [Sett_No] VARCHAR(12) NULL,
    [Sett_Type] VARCHAR(2) NULL,
    [narration] VARCHAR(500) NULL,
    [UserName] VARCHAR(25) NULL,
    [PostDate] DATETIME NULL,
    [EdtDr] DATETIME NULL,
    [EdtCr] DATETIME NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.CAL_DATES
-- --------------------------------------------------
CREATE TABLE [dbo].[CAL_DATES]
(
    [CAL_DATES] DATETIME NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.FORMULA_CLIENT_MASTER
-- --------------------------------------------------
CREATE TABLE [dbo].[FORMULA_CLIENT_MASTER]
(
    [CLTCODE] VARCHAR(10) NOT NULL,
    [PARTY_NAME] VARCHAR(100) NULL,
    [ENTITY_LEVEL] VARCHAR(20) NULL,
    [ENTITY_CODE] VARCHAR(25) NULL,
    [SESSION_ID] VARCHAR(500) NOT NULL,
    [POPULATE_DATE] DATETIME NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.FORMULA_MASTER
-- --------------------------------------------------
CREATE TABLE [dbo].[FORMULA_MASTER]
(
    [SRNO] INT IDENTITY(1,1) NOT NULL,
    [PROCESSCODE] VARCHAR(10) NULL,
    [PROCESSNAME] VARCHAR(50) NULL,
    [EXCHANGE] VARCHAR(5) NULL,
    [SEGMENT] VARCHAR(10) NULL,
    [FORMULANAME] VARCHAR(MAX) NULL,
    [COMPAREWITH] VARCHAR(20) NULL,
    [COMPARISON] VARCHAR(10) NULL,
    [TR_TYPE] TINYINT NULL,
    [DBTYPE] VARCHAR(30) NULL,
    [ADDITIONAL_PARAMETERS] VARCHAR(1000) NULL,
    [FORMULA_FIELDS] VARCHAR(1000) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.Ledger
-- --------------------------------------------------
CREATE TABLE [dbo].[Ledger]
(
    [Vtyp] SMALLINT NOT NULL,
    [Vno] VARCHAR(12) NOT NULL,
    [Edt] DATETIME NULL,
    [Lno] INT NOT NULL,
    [Acname] VARCHAR(100) NOT NULL,
    [Drcr] CHAR(1) NULL,
    [Vamt] MONEY NULL,
    [Vdt] DATETIME NULL,
    [Vno1] VARCHAR(12) NULL,
    [Refno] CHAR(12) NULL,
    [Balamt] MONEY NOT NULL,
    [Nodays] INT NULL,
    [Cdt] DATETIME NULL,
    [Cltcode] VARCHAR(10) NOT NULL,
    [Booktype] CHAR(2) NOT NULL,
    [Enteredby] VARCHAR(25) NULL,
    [Pdt] DATETIME NULL,
    [Checkedby] VARCHAR(50) NULL,
    [Actnodays] INT NULL,
    [Narration] VARCHAR(234) NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.ledger1
-- --------------------------------------------------
CREATE TABLE [dbo].[ledger1]
(
    [bnkname] VARCHAR(100) NULL,
    [brnname] VARCHAR(100) NULL,
    [dd] CHAR(1) NULL,
    [ddno] VARCHAR(30) NULL,
    [dddt] DATETIME NULL,
    [reldt] DATETIME NULL,
    [relamt] MONEY NULL,
    [refno] CHAR(12) NOT NULL,
    [receiptno] INT NULL,
    [vtyp] SMALLINT NULL,
    [vno] VARCHAR(12) NULL,
    [lno] INT NULL,
    [drcr] CHAR(1) NULL,
    [BookType] CHAR(2) NULL,
    [MicrNo] INT NULL,
    [SlipNo] INT NULL,
    [slipdate] DATETIME NULL,
    [ChequeInName] VARCHAR(100) NULL,
    [Chqprinted] TINYINT NULL,
    [clear_mode] CHAR(1) NULL,
    [L1_SNo] BIGINT IDENTITY(1,1) NOT NULL
);

GO

-- --------------------------------------------------
-- TABLE dbo.parameter
-- --------------------------------------------------
CREATE TABLE [dbo].[parameter]
(
    [sdtcur] DATETIME NULL,
    [ldtcur] DATETIME NULL,
    [ldtprv] DATETIME NULL,
    [sdtnxt] DATETIME NULL,
    [curyear] TINYINT NULL,
    [vnoflag] SMALLINT NULL,
    [Match_BtoB] SMALLINT NULL,
    [Match_CtoC] SMALLINT NULL,
    [Maker_Checker] SMALLINT NULL,
    [branchflag] TINYINT NULL,
    [voucherprintflag] TINYINT NULL,
    [reportdays] INT NULL
);

GO

-- --------------------------------------------------
-- VIEW dbo.RECON_BANK_MASTER_VW_F2
-- --------------------------------------------------


CREATE VIEW [dbo].[RECON_BANK_MASTER_VW_F2] 
AS
SELECT DISTINCT SEGMENT ,BANKNAME,BANKCODE FROM   ACCOUNT..RECON_BANK_MASTER (NOLOCK)

GO

